package handler

import (
	"hrbackend/internal/domain/permission"

	"github.com/gin-gonic/gin"
)

func RegisterEmployeeRoutes(
	rg *gin.RouterGroup,
	handler *EmployeeHandler,
	auth gin.HandlerFunc,
	requirePermission func(permission.Permission) gin.HandlerFunc,
) {
	rg.POST(
		"/employees",
		auth,
		requirePermission(permission.Employee.Create),
		handler.CreateEmployee,
	)
	rg.GET("/employees", auth, requirePermission(permission.Employee.View), handler.ListEmployee)
	rg.GET(
		"/employees/counts",
		auth,
		requirePermission(permission.Employee.View),
		handler.GetEmployeeCounts,
	)
	rg.GET(
		"/employees/:id",
		auth,
		requirePermission(permission.Employee.View),
		handler.GetEmployeeByID,
	)
	rg.PUT(
		"/employees/:id",
		auth,
		requirePermission(permission.Employee.Update),
		handler.UpdateEmployee,
	)
	rg.GET("/employees/profile", auth, handler.GetEmployeeProfile)
	rg.POST(
		"/employees/:id/education",
		auth,
		requirePermission(permission.Employee.Create),
		handler.AddEducation,
	)
	rg.GET(
		"/employees/:id/education",
		auth,
		requirePermission(permission.Employee.View),
		handler.ListEducation,
	)
	rg.PUT(
		"/employees/:id/education/:education_id",
		auth,
		requirePermission(permission.Employee.Update),
		handler.UpdateEducation,
	)
	rg.DELETE(
		"/employees/:id/education/:education_id",
		auth,
		requirePermission(permission.Employee.Delete),
		handler.DeleteEducation,
	)
	rg.POST(
		"/employees/:id/experience",
		auth,
		requirePermission(permission.Employee.Create),
		handler.AddExperience,
	)
	rg.GET(
		"/employees/:id/experience",
		auth,
		requirePermission(permission.Employee.View),
		handler.ListExperience,
	)
	rg.PUT(
		"/employees/:id/experience/:experience_id",
		auth,
		requirePermission(permission.Employee.Update),
		handler.UpdateExperience,
	)
	rg.DELETE(
		"/employees/:id/experience/:experience_id",
		auth,
		requirePermission(permission.Employee.Delete),
		handler.DeleteExperience,
	)
	rg.POST(
		"/employees/:id/qualifications",
		auth,
		requirePermission(permission.Employee.Create),
		handler.AddQualification,
	)
	rg.GET(
		"/employees/:id/qualifications",
		auth,
		requirePermission(permission.Employee.View),
		handler.ListQualification,
	)
	rg.PUT(
		"/employees/:id/qualifications/:qualification_id",
		auth,
		requirePermission(permission.Employee.Update),
		handler.UpdateQualification,
	)
	rg.DELETE(
		"/employees/:id/qualifications/:qualification_id",
		auth,
		requirePermission(permission.Employee.Delete),
		handler.DeleteQualification,
	)
	rg.POST(
		"/employees/:id/authorizations",
		auth,
		requirePermission(permission.Employee.Create),
		handler.AddEmployeeAuthorization,
	)
	rg.GET(
		"/employees/:id/authorizations",
		auth,
		requirePermission(permission.Employee.View),
		handler.ListEmployeeAuthorizations,
	)
	rg.PUT(
		"/employees/:id/authorizations/:authorization_id",
		auth,
		requirePermission(permission.Employee.Update),
		handler.UpdateEmployeeAuthorization,
	)
	rg.DELETE(
		"/employees/:id/authorizations/:authorization_id",
		auth,
		requirePermission(permission.Employee.Delete),
		handler.DeleteEmployeeAuthorization,
	)
	rg.GET(
		"/employees/:id/contracts",
		auth,
		requirePermission(permission.Employee.View),
		handler.ListEmployeeContracts,
	)
	rg.POST(
		"/employees/:id/contracts",
		auth,
		requirePermission(permission.Employee.Update),
		handler.CreateContract,
	)
	rg.PUT(
		"/employees/:id/contracts/:contract_id",
		auth,
		requirePermission(permission.Employee.Update),
		handler.UpdateContract,
	)
	rg.PUT(
		"/employees/:id/contracts/:contract_id/salary",
		auth,
		requirePermission(permission.Employee.Update),
		handler.UpdateContractSalary,
	)
	rg.POST(
		"/employees/:id/contracts/:contract_id/amendments",
		auth,
		requirePermission(permission.Employee.Update),
		handler.CreateContractAmendment,
	)
	rg.POST(
		"/employees/:id/reset_password",
		auth,
		requirePermission(permission.Employee.Update),
		handler.ResetPassword,
	)
	rg.GET(
		"/employees/emails",
		auth,
		requirePermission(permission.Employee.View),
		handler.SearchEmployeesByNameOrEmail,
	)
}
