package handler

import (
	"hrbackend/internal/domain/permission"

	"github.com/gin-gonic/gin"
)

func RegisterPayoutRoutes(
	rg *gin.RouterGroup,
	handler *PayoutHandler,
	auth gin.HandlerFunc,
	requirePermission func(permission.Permission) gin.HandlerFunc,
) {
	rg.GET(
		"/payouts/salary-page/mine",
		auth,
		requirePermission(permission.Payout.Request.View),
		handler.GetMySalaryPage,
	)
	rg.GET(
		"/payouts/detail/pdf",
		auth,
		requirePermission(permission.Payout.Request.View),
		handler.ExportMyPayrollMonthPDF,
	)
	rg.GET(
		"/salary-page/mine",
		auth,
		requirePermission(permission.Payout.Request.View),
		handler.GetMySalaryPage,
	)
	rg.GET(
		"/payroll-preview/my",
		auth,
		requirePermission(permission.Payout.Request.View),
		handler.PreviewMyPayroll,
	)
	rg.GET(
		"/payroll-preview",
		auth,
		requirePermission(permission.Payout.Request.ViewAll),
		handler.PreviewPayroll,
	)
	rg.GET(
		"/payroll/ort-rules",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetORTRules,
	)
	rg.GET(
		"/payroll-month-summary/fixed",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetFixedPayrollMonthSummary,
	)
	rg.GET(
		"/payroll-month-summary/on-call",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetOnCallPayrollMonthSummary,
	)
	rg.GET(
		"/payroll-month-summary/ort-overview",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetPayrollMonthORTOverview,
	)
	rg.GET(
		"/payroll-month-summary/details",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetPayrollMonthDetail,
	)
	rg.GET(
		"/payroll-month-summary/export-pdf",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.ExportPayrollMonthSummaryPDF,
	)
	rg.POST(
		"/pay-periods/close",
		auth,
		requirePermission(permission.PayPeriod.Close),
		handler.ClosePayPeriod,
	)
	rg.GET("/pay-periods", auth, requirePermission(permission.PayPeriod.ViewAll), handler.ListPayPeriods)
	rg.GET(
		"/pay-periods/:id",
		auth,
		requirePermission(permission.PayPeriod.ViewAll),
		handler.GetPayPeriodByID,
	)
	rg.POST(
		"/pay-periods/:id/mark-paid",
		auth,
		requirePermission(permission.PayPeriod.MarkPaid),
		handler.MarkPayPeriodPaidByAdmin,
	)
	rg.POST(
		"/payout-requests/admin",
		auth,
		requirePermission(permission.Payout.Request.Decide),
		handler.CreatePayoutRequestByAdmin,
	)
	rg.POST(
		"/payout-requests",
		auth,
		requirePermission(permission.Payout.Request.Create),
		handler.CreatePayoutRequest,
	)
	rg.GET(
		"/payout-requests/my",
		auth,
		requirePermission(permission.Payout.Request.View),
		handler.ListMyPayoutRequests,
	)
	rg.GET(
		"/payout-requests",
		auth,
		requirePermission(permission.Payout.Request.ViewAll),
		handler.ListPayoutRequests,
	)
	rg.POST(
		"/payout-requests/:id/decision",
		auth,
		requirePermission(permission.Payout.Request.Decide),
		handler.DecidePayoutRequestByAdmin,
	)
	rg.POST(
		"/payout-requests/:id/mark-paid",
		auth,
		requirePermission(permission.Payout.Request.MarkPaid),
		handler.MarkPayoutRequestPaidByAdmin,
	)
}
