package handler

import (
	"hrbackend/internal/domain/permission"

	"github.com/gin-gonic/gin"
)

func RegisterSalaryRoutes(
	rg *gin.RouterGroup,
	handler *SalaryHandler,
	auth gin.HandlerFunc,
	requirePermission func(permission.Permission) gin.HandlerFunc,
) {
	rg.GET(
		"/salary-scale-steps",
		auth,
		requirePermission(permission.Employee.Create),
		handler.ListSalaryScaleSteps,
	)
	// Legacy routes kept for backwards compatibility
	rg.GET(
		"/payouts/salary-page/mine",
		auth,
		requirePermission(permission.Payout.Request.View),
		handler.GetMySalaryPage,
	)
	rg.GET(
		"/payouts/detail/pdf",
		auth,
		requirePermission(permission.Payout.Request.View),
		handler.ExportMyPayrollMonthPDF,
	)
	rg.GET(
		"/salary-page/mine",
		auth,
		requirePermission(permission.Payout.Request.View),
		handler.GetMySalaryPage,
	)
	rg.GET(
		"/payroll-preview/my",
		auth,
		requirePermission(permission.Payout.Request.View),
		handler.PreviewMyPayroll,
	)
	rg.GET(
		"/payroll-preview",
		auth,
		requirePermission(permission.Payout.Request.ViewAll),
		handler.PreviewPayroll,
	)
	rg.GET(
		"/payroll/ort-rules",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetORTRules,
	)
	rg.GET(
		"/payroll-month-summary/fixed",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetFixedPayrollMonthSummary,
	)
	rg.GET(
		"/payroll-month-summary/fixed/stats",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetFixedPayrollMonthStats,
	)
	rg.POST(
		"/payroll-month-summary/fixed/close-preview",
		auth,
		requirePermission(permission.PayPeriod.Close),
		handler.PreviewFixedPayrollMonthClose,
	)
	rg.POST(
		"/payroll-month-summary/fixed/close",
		auth,
		requirePermission(permission.PayPeriod.Close),
		handler.CloseFixedPayrollMonth,
	)
	rg.GET(
		"/payroll-month-summary/on-call",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetOnCallPayrollMonthSummary,
	)
	rg.GET(
		"/payroll-month-summary/on-call/stats",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetOnCallPayrollMonthStats,
	)
	rg.POST(
		"/payroll-month-summary/on-call/close-preview",
		auth,
		requirePermission(permission.PayPeriod.Close),
		handler.PreviewOnCallPayrollMonthClose,
	)
	rg.POST(
		"/payroll-month-summary/on-call/close",
		auth,
		requirePermission(permission.PayPeriod.Close),
		handler.CloseOnCallPayrollMonth,
	)
	rg.GET(
		"/payroll-month-summary/ort-overview",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetPayrollMonthORTOverview,
	)
	rg.GET(
		"/payroll-month-summary/details",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.GetPayrollMonthDetail,
	)
	rg.GET(
		"/payroll-month-summary/export-pdf",
		auth,
		requirePermission(permission.PayPeriod.MonthSummaryView),
		handler.ExportPayrollMonthSummaryPDF,
	)
	rg.POST(
		"/pay-periods/close",
		auth,
		requirePermission(permission.PayPeriod.Close),
		handler.ClosePayPeriod,
	)
	rg.GET("/pay-periods", auth, requirePermission(permission.PayPeriod.ViewAll), handler.ListPayPeriods)
	rg.GET(
		"/pay-periods/:id",
		auth,
		requirePermission(permission.PayPeriod.ViewAll),
		handler.GetPayPeriodByID,
	)
	rg.POST(
		"/pay-periods/:id/mark-paid",
		auth,
		requirePermission(permission.PayPeriod.MarkPaid),
		handler.MarkPayPeriodPaidByAdmin,
	)
}
