// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachment_file (
    name,
    file,
    size,
    is_used,
    tag
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING uuid, name, file, size, is_used, tag, updated, created
`

type CreateAttachmentParams struct {
	Name   string  `json:"name"`
	File   string  `json:"file"`
	Size   int32   `json:"size"`
	IsUsed bool    `json:"is_used"`
	Tag    *string `json:"tag"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (AttachmentFile, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.Name,
		arg.File,
		arg.Size,
		arg.IsUsed,
		arg.Tag,
	)
	var i AttachmentFile
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.File,
		&i.Size,
		&i.IsUsed,
		&i.Tag,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const createEmployeeAttachments = `-- name: CreateEmployeeAttachments :exec
INSERT INTO employee_attachment (
    employee_id,
    attachment_id,
    category
)
SELECT 
    $1::uuid,
    unnest($2::uuid[]),
    $3::varchar
`

type CreateEmployeeAttachmentsParams struct {
	EmployeeID    uuid.UUID   `json:"employee_id"`
	AttachmentIds []uuid.UUID `json:"attachment_ids"`
	Category      string      `json:"category"`
}

func (q *Queries) CreateEmployeeAttachments(ctx context.Context, arg CreateEmployeeAttachmentsParams) error {
	_, err := q.db.Exec(ctx, createEmployeeAttachments, arg.EmployeeID, arg.AttachmentIds, arg.Category)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachment_file
WHERE uuid = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, argUuid)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT uuid, name, file, size, is_used, tag, updated, created FROM attachment_file
WHERE uuid = $1 LIMIT 1
`

func (q *Queries) GetAttachment(ctx context.Context, argUuid uuid.UUID) (AttachmentFile, error) {
	row := q.db.QueryRow(ctx, getAttachment, argUuid)
	var i AttachmentFile
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.File,
		&i.Size,
		&i.IsUsed,
		&i.Tag,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const listEmployeeAttachments = `-- name: ListEmployeeAttachments :many
SELECT 
    ea.id,
    ea.employee_id,
    ea.attachment_id,
    ea.category,
    ea.created_at,
    ea.updated_at,
    af.name,
    af.file,
    af.size,
    af.tag
FROM employee_attachment ea
JOIN attachment_file af ON af.uuid = ea.attachment_id
WHERE ea.employee_id = $1
`

type ListEmployeeAttachmentsRow struct {
	ID           uuid.UUID          `json:"id"`
	EmployeeID   uuid.UUID          `json:"employee_id"`
	AttachmentID uuid.UUID          `json:"attachment_id"`
	Category     string             `json:"category"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Name         string             `json:"name"`
	File         string             `json:"file"`
	Size         int32              `json:"size"`
	Tag          *string            `json:"tag"`
}

func (q *Queries) ListEmployeeAttachments(ctx context.Context, employeeID uuid.UUID) ([]ListEmployeeAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeAttachments, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeAttachmentsRow{}
	for rows.Next() {
		var i ListEmployeeAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AttachmentID,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.File,
			&i.Size,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttachmentUsed = `-- name: UpdateAttachmentUsed :one
UPDATE attachment_file
SET is_used = $2,
    updated = CURRENT_TIMESTAMP
WHERE uuid = $1
RETURNING uuid, name, file, size, is_used, tag, updated, created
`

type UpdateAttachmentUsedParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	IsUsed bool      `json:"is_used"`
}

func (q *Queries) UpdateAttachmentUsed(ctx context.Context, arg UpdateAttachmentUsedParams) (AttachmentFile, error) {
	row := q.db.QueryRow(ctx, updateAttachmentUsed, arg.Uuid, arg.IsUsed)
	var i AttachmentFile
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.File,
		&i.Size,
		&i.IsUsed,
		&i.Tag,
		&i.Updated,
		&i.Created,
	)
	return i, err
}

const updateAttachmentsUsed = `-- name: UpdateAttachmentsUsed :exec
UPDATE attachment_file
SET is_used = $1::boolean,
    updated = CURRENT_TIMESTAMP
WHERE uuid = ANY($2::uuid[])
`

type UpdateAttachmentsUsedParams struct {
	IsUsed        bool        `json:"is_used"`
	AttachmentIds []uuid.UUID `json:"attachment_ids"`
}

func (q *Queries) UpdateAttachmentsUsed(ctx context.Context, arg UpdateAttachmentsUsedParams) error {
	_, err := q.db.Exec(ctx, updateAttachmentsUsed, arg.IsUsed, arg.AttachmentIds)
	return err
}
