// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAuthorization = `-- name: CreateAuthorization :one
INSERT INTO authorizations (
    name,
    description,
    category,
    requires_expiry
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, description, category, requires_expiry, is_active, created_at, updated_at
`

type CreateAuthorizationParams struct {
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	Category       string  `json:"category"`
	RequiresExpiry bool    `json:"requires_expiry"`
}

func (q *Queries) CreateAuthorization(ctx context.Context, arg CreateAuthorizationParams) (Authorization, error) {
	row := q.db.QueryRow(ctx, createAuthorization,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.RequiresExpiry,
	)
	var i Authorization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.RequiresExpiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthorizations = `-- name: ListAuthorizations :many
SELECT id, name, description, category, requires_expiry, is_active, created_at, updated_at FROM authorizations WHERE is_active = TRUE ORDER BY name
`

func (q *Queries) ListAuthorizations(ctx context.Context) ([]Authorization, error) {
	rows, err := q.db.Query(ctx, listAuthorizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Authorization{}
	for rows.Next() {
		var i Authorization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.RequiresExpiry,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthorization = `-- name: UpdateAuthorization :one
UPDATE authorizations
SET
    name = $2,
    description = $3,
    category = $4,
    requires_expiry = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, description, category, requires_expiry, is_active, created_at, updated_at
`

type UpdateAuthorizationParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	Category       string    `json:"category"`
	RequiresExpiry bool      `json:"requires_expiry"`
}

func (q *Queries) UpdateAuthorization(ctx context.Context, arg UpdateAuthorizationParams) (Authorization, error) {
	row := q.db.QueryRow(ctx, updateAuthorization,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.RequiresExpiry,
	)
	var i Authorization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.RequiresExpiry,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
