// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bug_report.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBugReport = `-- name: CreateBugReport :one
INSERT INTO bug_reports (
    user_id,
    subject,
    category,
    severity,
    description,
    steps,
    debug_info
) VALUES (
    $1,
    $2,
    $3::bug_report_category_enum,
    $4::bug_report_severity_enum,
    $5,
    $6,
    COALESCE($7, '{}'::jsonb)
)
RETURNING id, user_id, subject, category, severity, description, steps, debug_info, status, created_at, updated_at
`

type CreateBugReportParams struct {
	UserID      uuid.UUID             `json:"user_id"`
	Subject     string                `json:"subject"`
	Category    BugReportCategoryEnum `json:"category"`
	Severity    BugReportSeverityEnum `json:"severity"`
	Description string                `json:"description"`
	Steps       *string               `json:"steps"`
	DebugInfo   interface{}           `json:"debug_info"`
}

func (q *Queries) CreateBugReport(ctx context.Context, arg CreateBugReportParams) (BugReport, error) {
	row := q.db.QueryRow(ctx, createBugReport,
		arg.UserID,
		arg.Subject,
		arg.Category,
		arg.Severity,
		arg.Description,
		arg.Steps,
		arg.DebugInfo,
	)
	var i BugReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Severity,
		&i.Description,
		&i.Steps,
		&i.DebugInfo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
