// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForAddEmployeeAuthorizationsBatch implements pgx.CopyFromSource.
type iteratorForAddEmployeeAuthorizationsBatch struct {
	rows                 []AddEmployeeAuthorizationsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddEmployeeAuthorizationsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddEmployeeAuthorizationsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].EmployeeID,
		r.rows[0].AuthorizationID,
		r.rows[0].GrantedDate,
		r.rows[0].ExpiryDate,
		r.rows[0].IsActive,
		r.rows[0].Notes,
	}, nil
}

func (r iteratorForAddEmployeeAuthorizationsBatch) Err() error {
	return nil
}

func (q *Queries) AddEmployeeAuthorizationsBatch(ctx context.Context, arg []AddEmployeeAuthorizationsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"employee_authorizations"}, []string{"employee_id", "authorization_id", "granted_date", "expiry_date", "is_active", "notes"}, &iteratorForAddEmployeeAuthorizationsBatch{rows: arg})
}

// iteratorForAddEmployeeQualificationsBatch implements pgx.CopyFromSource.
type iteratorForAddEmployeeQualificationsBatch struct {
	rows                 []AddEmployeeQualificationsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddEmployeeQualificationsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddEmployeeQualificationsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].EmployeeID,
		r.rows[0].QualificationID,
		r.rows[0].AchievedOn,
		r.rows[0].ExpirationDate,
		r.rows[0].CertificateNumber,
	}, nil
}

func (r iteratorForAddEmployeeQualificationsBatch) Err() error {
	return nil
}

func (q *Queries) AddEmployeeQualificationsBatch(ctx context.Context, arg []AddEmployeeQualificationsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"employee_qualifications"}, []string{"employee_id", "qualification_id", "achieved_on", "expiration_date", "certificate_number"}, &iteratorForAddEmployeeQualificationsBatch{rows: arg})
}
