// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
    name,
    description,
    department_head_employee_id
) VALUES (
    $1, $2, $3
)
RETURNING id, name, description, department_head_employee_id, created_at, updated_at
`

type CreateDepartmentParams struct {
	Name                     string     `json:"name"`
	Description              *string    `json:"description"`
	DepartmentHeadEmployeeID *uuid.UUID `json:"department_head_employee_id"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.Name, arg.Description, arg.DepartmentHeadEmployeeID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DepartmentHeadEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :one
DELETE FROM departments
WHERE id = $1
RETURNING id, name, description, department_head_employee_id, created_at, updated_at
`

func (q *Queries) DeleteDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, deleteDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DepartmentHeadEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, description, department_head_employee_id, created_at, updated_at
FROM departments
WHERE id = $1
`

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DepartmentHeadEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepartmentsPaginated = `-- name: ListDepartmentsPaginated :many
SELECT d.id, d.name, d.description, d.department_head_employee_id, d.created_at, d.updated_at,
       COUNT(*) OVER() AS total_count
FROM departments d
WHERE ($3::text IS NULL OR d.name ILIKE '%' || $3 || '%')
ORDER BY d.name
LIMIT $1 OFFSET $2
`

type ListDepartmentsPaginatedParams struct {
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Column3 string `json:"column_3"`
}

type ListDepartmentsPaginatedRow struct {
	ID                       uuid.UUID          `json:"id"`
	Name                     string             `json:"name"`
	Description              *string            `json:"description"`
	DepartmentHeadEmployeeID *uuid.UUID         `json:"department_head_employee_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	TotalCount               int64              `json:"total_count"`
}

func (q *Queries) ListDepartmentsPaginated(ctx context.Context, arg ListDepartmentsPaginatedParams) ([]ListDepartmentsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listDepartmentsPaginated, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepartmentsPaginatedRow{}
	for rows.Next() {
		var i ListDepartmentsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DepartmentHeadEmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    department_head_employee_id = COALESCE($4, department_head_employee_id),
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, department_head_employee_id, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID                       uuid.UUID  `json:"id"`
	Name                     *string    `json:"name"`
	Description              *string    `json:"description"`
	DepartmentHeadEmployeeID *uuid.UUID `json:"department_head_employee_id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DepartmentHeadEmployeeID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DepartmentHeadEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
