// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee_authorizations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEmployeeAuthorization = `-- name: AddEmployeeAuthorization :one
INSERT INTO employee_authorizations (
    employee_id,
    authorization_id,
    granted_date,
    expiry_date,
    is_active,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, employee_id, authorization_id, granted_date, expiry_date, is_active, notes, created_at, updated_at
`

type AddEmployeeAuthorizationParams struct {
	EmployeeID      uuid.UUID   `json:"employee_id"`
	AuthorizationID uuid.UUID   `json:"authorization_id"`
	GrantedDate     pgtype.Date `json:"granted_date"`
	ExpiryDate      pgtype.Date `json:"expiry_date"`
	IsActive        bool        `json:"is_active"`
	Notes           *string     `json:"notes"`
}

func (q *Queries) AddEmployeeAuthorization(ctx context.Context, arg AddEmployeeAuthorizationParams) (EmployeeAuthorization, error) {
	row := q.db.QueryRow(ctx, addEmployeeAuthorization,
		arg.EmployeeID,
		arg.AuthorizationID,
		arg.GrantedDate,
		arg.ExpiryDate,
		arg.IsActive,
		arg.Notes,
	)
	var i EmployeeAuthorization
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AuthorizationID,
		&i.GrantedDate,
		&i.ExpiryDate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type AddEmployeeAuthorizationsBatchParams struct {
	EmployeeID      uuid.UUID   `json:"employee_id"`
	AuthorizationID uuid.UUID   `json:"authorization_id"`
	GrantedDate     pgtype.Date `json:"granted_date"`
	ExpiryDate      pgtype.Date `json:"expiry_date"`
	IsActive        bool        `json:"is_active"`
	Notes           *string     `json:"notes"`
}

const deleteEmployeeAuthorization = `-- name: DeleteEmployeeAuthorization :one
DELETE FROM employee_authorizations WHERE id = $1 RETURNING id, employee_id, authorization_id, granted_date, expiry_date, is_active, notes, created_at, updated_at
`

func (q *Queries) DeleteEmployeeAuthorization(ctx context.Context, id uuid.UUID) (EmployeeAuthorization, error) {
	row := q.db.QueryRow(ctx, deleteEmployeeAuthorization, id)
	var i EmployeeAuthorization
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AuthorizationID,
		&i.GrantedDate,
		&i.ExpiryDate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployeeAuthorizations = `-- name: ListEmployeeAuthorizations :many
SELECT id, employee_id, authorization_id, granted_date, expiry_date, is_active, notes, created_at, updated_at FROM employee_authorizations WHERE employee_id = $1
`

func (q *Queries) ListEmployeeAuthorizations(ctx context.Context, employeeID uuid.UUID) ([]EmployeeAuthorization, error) {
	rows, err := q.db.Query(ctx, listEmployeeAuthorizations, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmployeeAuthorization{}
	for rows.Next() {
		var i EmployeeAuthorization
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AuthorizationID,
			&i.GrantedDate,
			&i.ExpiryDate,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeeAuthorization = `-- name: UpdateEmployeeAuthorization :one
UPDATE employee_authorizations
SET
    authorization_id = COALESCE($2, authorization_id),
    granted_date = COALESCE($3, granted_date),
    expiry_date = COALESCE($4, expiry_date),
    is_active = COALESCE($5, is_active),
    notes = COALESCE($6, notes),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, employee_id, authorization_id, granted_date, expiry_date, is_active, notes, created_at, updated_at
`

type UpdateEmployeeAuthorizationParams struct {
	ID              uuid.UUID   `json:"id"`
	AuthorizationID *uuid.UUID  `json:"authorization_id"`
	GrantedDate     pgtype.Date `json:"granted_date"`
	ExpiryDate      pgtype.Date `json:"expiry_date"`
	IsActive        *bool       `json:"is_active"`
	Notes           *string     `json:"notes"`
}

func (q *Queries) UpdateEmployeeAuthorization(ctx context.Context, arg UpdateEmployeeAuthorizationParams) (EmployeeAuthorization, error) {
	row := q.db.QueryRow(ctx, updateEmployeeAuthorization,
		arg.ID,
		arg.AuthorizationID,
		arg.GrantedDate,
		arg.ExpiryDate,
		arg.IsActive,
		arg.Notes,
	)
	var i EmployeeAuthorization
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.AuthorizationID,
		&i.GrantedDate,
		&i.ExpiryDate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
