// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee_salary.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployeeSalaryAssignment = `-- name: CreateEmployeeSalaryAssignment :one
INSERT INTO employee_salary_assignments (
    employee_id,
    contract_id,
    salary_scale_step_id,
    effective_from,
    effective_to,
    created_by_employee_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, employee_id, contract_id, salary_scale_step_id, effective_from, effective_to, created_by_employee_id, created_at, updated_at
`

type CreateEmployeeSalaryAssignmentParams struct {
	EmployeeID          uuid.UUID   `json:"employee_id"`
	ContractID          *uuid.UUID  `json:"contract_id"`
	SalaryScaleStepID   uuid.UUID   `json:"salary_scale_step_id"`
	EffectiveFrom       pgtype.Date `json:"effective_from"`
	EffectiveTo         pgtype.Date `json:"effective_to"`
	CreatedByEmployeeID *uuid.UUID  `json:"created_by_employee_id"`
}

func (q *Queries) CreateEmployeeSalaryAssignment(ctx context.Context, arg CreateEmployeeSalaryAssignmentParams) (EmployeeSalaryAssignment, error) {
	row := q.db.QueryRow(ctx, createEmployeeSalaryAssignment,
		arg.EmployeeID,
		arg.ContractID,
		arg.SalaryScaleStepID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.CreatedByEmployeeID,
	)
	var i EmployeeSalaryAssignment
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ContractID,
		&i.SalaryScaleStepID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedByEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
