// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee_profile_utility.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getEmployeeCounts = `-- name: GetEmployeeCounts :one
SELECT
    COUNT(*) FILTER (WHERE ec.contract_type = 'permanent') AS total_permanent,
    COUNT(*) FILTER (WHERE ec.contract_type = 'temporary') AS total_temporary,
    COUNT(*) FILTER (WHERE ec.contract_type = 'on_call') AS total_on_call,
    COUNT(*) FILTER (WHERE ep.out_of_service = TRUE) AS total_out_of_service
FROM employee_profile ep
LEFT JOIN LATERAL (
    SELECT c.contract_type
    FROM employee_contracts c
    WHERE c.employee_id = ep.id
      AND c.start_date <= CURRENT_DATE
      AND (c.effective_end_date IS NULL OR c.effective_end_date >= CURRENT_DATE)
      AND (c.contract_end_date IS NULL OR c.contract_end_date >= CURRENT_DATE)
    ORDER BY c.start_date DESC, c.created_at DESC
    LIMIT 1
) ec ON TRUE
`

type GetEmployeeCountsRow struct {
	TotalPermanent    int64 `json:"total_permanent"`
	TotalTemporary    int64 `json:"total_temporary"`
	TotalOnCall       int64 `json:"total_on_call"`
	TotalOutOfService int64 `json:"total_out_of_service"`
}

func (q *Queries) GetEmployeeCounts(ctx context.Context) (GetEmployeeCountsRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeCounts)
	var i GetEmployeeCountsRow
	err := row.Scan(
		&i.TotalPermanent,
		&i.TotalTemporary,
		&i.TotalOnCall,
		&i.TotalOutOfService,
	)
	return i, err
}

const getEmployeeDetailStats = `-- name: GetEmployeeDetailStats :one
WITH ranges AS (
    SELECT
        date_trunc('month', CURRENT_DATE)::date AS month_start,
        (date_trunc('month', CURRENT_DATE) + INTERVAL '1 month')::date AS next_month_start,
        date_trunc('year', CURRENT_DATE)::date AS year_start,
        (date_trunc('year', CURRENT_DATE) + INTERVAL '1 year')::date AS next_year_start,
        EXTRACT(YEAR FROM CURRENT_DATE)::int AS balance_year
), time_entry_minutes AS (
    SELECT
        COALESCE(SUM(worked_minutes) FILTER (
            WHERE te.status = 'approved'::time_entry_status_enum
              AND te.entry_date >= r.month_start
              AND te.entry_date < r.next_month_start
        ), 0)::double precision AS approved_month_minutes,
        COALESCE(SUM(worked_minutes) FILTER (
            WHERE te.status = 'submitted'::time_entry_status_enum
              AND te.entry_date >= r.month_start
              AND te.entry_date < r.next_month_start
        ), 0)::double precision AS pending_month_minutes,
        COALESCE(SUM(worked_minutes) FILTER (
            WHERE te.status = 'approved'::time_entry_status_enum
              AND te.entry_date >= r.year_start
              AND te.entry_date < r.next_year_start
        ), 0)::double precision AS approved_year_minutes
    FROM ranges r
    LEFT JOIN LATERAL (
        SELECT
            te.status,
            te.entry_date,
            GREATEST(
                0,
                (
                    CASE
                        WHEN te.end_time > te.start_time THEN
                            EXTRACT(EPOCH FROM te.end_time) - EXTRACT(EPOCH FROM te.start_time)
                        ELSE
                            EXTRACT(EPOCH FROM te.end_time) + 86400 - EXTRACT(EPOCH FROM te.start_time)
                    END
                ) / 60 - te.break_minutes
            ) AS worked_minutes
        FROM time_entries te
        WHERE te.employee_id = $1
          AND te.hour_type IN (
              'normal'::time_entry_hour_type_enum,
              'overtime'::time_entry_hour_type_enum,
              'travel'::time_entry_hour_type_enum,
              'training'::time_entry_hour_type_enum
          )
          AND te.status IN (
              'approved'::time_entry_status_enum,
              'submitted'::time_entry_status_enum
          )
          AND te.entry_date >= r.year_start
          AND te.entry_date < r.next_year_start
    ) te ON TRUE
), leave_balance AS (
    SELECT
        COALESCE(
            (lb.legal_total_hours - lb.legal_used_hours)
            + (lb.extra_total_hours - lb.extra_used_hours),
            0
        )::int AS remaining_leave_balance_hours
    FROM ranges r
    LEFT JOIN leave_balances lb ON lb.employee_id = $1
      AND lb.year = r.balance_year
), last_review AS (
    SELECT pa.total_score::double precision AS last_performance_review_score
    FROM performance_assessments pa
    WHERE pa.employee_id = $1
      AND pa.status = 'completed'::performance_assessment_status_enum
    ORDER BY pa.assessment_date DESC, pa.created_at DESC
    LIMIT 1
)
SELECT
    lb.remaining_leave_balance_hours,
    (tem.approved_month_minutes / 60.0)::double precision AS hours_worked_this_month,
    (tem.pending_month_minutes / 60.0)::double precision AS hours_pending_approval,
    (tem.approved_year_minutes / 60.0)::double precision AS total_hours_worked_this_year,
    lr.last_performance_review_score
FROM leave_balance lb
CROSS JOIN time_entry_minutes tem
LEFT JOIN last_review lr ON TRUE
`

type GetEmployeeDetailStatsRow struct {
	RemainingLeaveBalanceHours int32    `json:"remaining_leave_balance_hours"`
	HoursWorkedThisMonth       float64  `json:"hours_worked_this_month"`
	HoursPendingApproval       float64  `json:"hours_pending_approval"`
	TotalHoursWorkedThisYear   float64  `json:"total_hours_worked_this_year"`
	LastPerformanceReviewScore *float64 `json:"last_performance_review_score"`
}

func (q *Queries) GetEmployeeDetailStats(ctx context.Context, employeeID uuid.UUID) (GetEmployeeDetailStatsRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeDetailStats, employeeID)
	var i GetEmployeeDetailStatsRow
	err := row.Scan(
		&i.RemainingLeaveBalanceHours,
		&i.HoursWorkedThisMonth,
		&i.HoursPendingApproval,
		&i.TotalHoursWorkedThisYear,
		&i.LastPerformanceReviewScore,
	)
	return i, err
}

const getUserIDByEmployeeID = `-- name: GetUserIDByEmployeeID :one
SELECT user_id FROM employee_profile
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserIDByEmployeeID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmployeeID, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listEmployeeNamesByIDs = `-- name: ListEmployeeNamesByIDs :many
SELECT
    id,
    first_name,
    last_name
FROM employee_profile
WHERE id = ANY($1::uuid[])
`

type ListEmployeeNamesByIDsRow struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
}

func (q *Queries) ListEmployeeNamesByIDs(ctx context.Context, employeeIds []uuid.UUID) ([]ListEmployeeNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeNamesByIDs, employeeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeNamesByIDsRow{}
	for rows.Next() {
		var i ListEmployeeNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesWithContractHours = `-- name: ListEmployeesWithContractHours :many
SELECT
    ep.id,
    ep.first_name,
    ep.last_name,
    ec.hours_per_week AS contract_hours
FROM employee_profile ep
JOIN LATERAL (
    SELECT hours_per_week
    FROM employee_contracts c
    WHERE c.employee_id = ep.id
    ORDER BY c.start_date DESC, c.created_at DESC
    LIMIT 1
) ec ON true
WHERE ep.id = ANY($1::uuid[])
AND ec.hours_per_week IS NOT NULL
AND ec.hours_per_week > 0
`

type ListEmployeesWithContractHoursRow struct {
	ID            uuid.UUID `json:"id"`
	FirstName     string    `json:"first_name"`
	LastName      string    `json:"last_name"`
	ContractHours *float64  `json:"contract_hours"`
}

func (q *Queries) ListEmployeesWithContractHours(ctx context.Context, dollar_1 []uuid.UUID) ([]ListEmployeesWithContractHoursRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesWithContractHours, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesWithContractHoursRow{}
	for rows.Next() {
		var i ListEmployeesWithContractHoursRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ContractHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsByEmployeeIDs = `-- name: ListUserIDsByEmployeeIDs :many
SELECT user_id
FROM employee_profile
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListUserIDsByEmployeeIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDsByEmployeeIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEmployeesByNameOrEmail = `-- name: SearchEmployeesByNameOrEmail :many
SELECT
    id,
    first_name,
    last_name,
    work_email_address
FROM employee_profile
WHERE
    first_name ILIKE '%' || $1 || '%' OR
    last_name ILIKE '%' || $1 || '%' OR
    email ILIKE '%' || $1 || '%'
LIMIT 10
`

type SearchEmployeesByNameOrEmailRow struct {
	ID               uuid.UUID `json:"id"`
	FirstName        string    `json:"first_name"`
	LastName         string    `json:"last_name"`
	WorkEmailAddress *string   `json:"work_email_address"`
}

func (q *Queries) SearchEmployeesByNameOrEmail(ctx context.Context, search *string) ([]SearchEmployeesByNameOrEmailRow, error) {
	rows, err := q.db.Query(ctx, searchEmployeesByNameOrEmail, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEmployeesByNameOrEmailRow{}
	for rows.Next() {
		var i SearchEmployeesByNameOrEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.WorkEmailAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmployeeProfilePicture = `-- name: SetEmployeeProfilePicture :one
UPDATE custom_user
SET profile_picture = $2
WHERE id = (
    SELECT user_id
    FROM employee_profile
    WHERE employee_profile.id = $1
)
RETURNING id, password, last_login, email, is_active, date_joined, profile_picture, two_factor_enabled, two_factor_secret, two_factor_secret_temp, recovery_codes
`

type SetEmployeeProfilePictureParams struct {
	ID             uuid.UUID `json:"id"`
	ProfilePicture *string   `json:"profile_picture"`
}

func (q *Queries) SetEmployeeProfilePicture(ctx context.Context, arg SetEmployeeProfilePictureParams) (CustomUser, error) {
	row := q.db.QueryRow(ctx, setEmployeeProfilePicture, arg.ID, arg.ProfilePicture)
	var i CustomUser
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.LastLogin,
		&i.Email,
		&i.IsActive,
		&i.DateJoined,
		&i.ProfilePicture,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.TwoFactorSecretTemp,
		&i.RecoveryCodes,
	)
	return i, err
}
