// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employee_profile_contracts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEmployeeContractDetails = `-- name: AddEmployeeContractDetails :one
INSERT INTO employee_contracts (
    employee_id,
    job_title,
    department_id,
    location_id,
    organizational_role_id,
    contract_type,
    contract_hours_type,
    start_date,
    contract_end_date,
    hours_per_week,
    min_hours_per_week,
    max_hours_per_week,
    roster_free_day,
    wage_tax_table,
    created_by_employee_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING id, employee_id, job_title, department_id, location_id, organizational_role_id, contract_type, contract_hours_type, start_date, contract_end_date, hours_per_week, min_hours_per_week, max_hours_per_week, roster_free_day, wage_tax_table, created_by_employee_id, created_at, updated_at
`

type AddEmployeeContractDetailsParams struct {
	EmployeeID           uuid.UUID                `json:"employee_id"`
	JobTitle             EmployeeJobTitleEnum     `json:"job_title"`
	DepartmentID         uuid.UUID                `json:"department_id"`
	LocationID           uuid.UUID                `json:"location_id"`
	OrganizationalRoleID *uuid.UUID               `json:"organizational_role_id"`
	ContractType         EmployeeContractTypeEnum `json:"contract_type"`
	ContractHoursType    ContractHoursTypeEnum    `json:"contract_hours_type"`
	StartDate            pgtype.Date              `json:"start_date"`
	ContractEndDate      pgtype.Date              `json:"contract_end_date"`
	HoursPerWeek         *float64                 `json:"hours_per_week"`
	MinHoursPerWeek      *float64                 `json:"min_hours_per_week"`
	MaxHoursPerWeek      *float64                 `json:"max_hours_per_week"`
	RosterFreeDay        *int16                   `json:"roster_free_day"`
	WageTaxTable         *WageTaxTableEnum        `json:"wage_tax_table"`
	CreatedByEmployeeID  *uuid.UUID               `json:"created_by_employee_id"`
}

func (q *Queries) AddEmployeeContractDetails(ctx context.Context, arg AddEmployeeContractDetailsParams) (EmployeeContract, error) {
	row := q.db.QueryRow(ctx, addEmployeeContractDetails,
		arg.EmployeeID,
		arg.JobTitle,
		arg.DepartmentID,
		arg.LocationID,
		arg.OrganizationalRoleID,
		arg.ContractType,
		arg.ContractHoursType,
		arg.StartDate,
		arg.ContractEndDate,
		arg.HoursPerWeek,
		arg.MinHoursPerWeek,
		arg.MaxHoursPerWeek,
		arg.RosterFreeDay,
		arg.WageTaxTable,
		arg.CreatedByEmployeeID,
	)
	var i EmployeeContract
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.JobTitle,
		&i.DepartmentID,
		&i.LocationID,
		&i.OrganizationalRoleID,
		&i.ContractType,
		&i.ContractHoursType,
		&i.StartDate,
		&i.ContractEndDate,
		&i.HoursPerWeek,
		&i.MinHoursPerWeek,
		&i.MaxHoursPerWeek,
		&i.RosterFreeDay,
		&i.WageTaxTable,
		&i.CreatedByEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployeeIsSubcontractor = `-- name: UpdateEmployeeIsSubcontractor :one
UPDATE employee_contracts ec
SET contract_type = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = (
    SELECT c.id
    FROM employee_contracts c
    WHERE c.employee_id = $1
    ORDER BY c.start_date DESC, c.created_at DESC
    LIMIT 1
)
RETURNING id, employee_id, job_title, department_id, location_id, organizational_role_id, contract_type, contract_hours_type, start_date, contract_end_date, hours_per_week, min_hours_per_week, max_hours_per_week, roster_free_day, wage_tax_table, created_by_employee_id, created_at, updated_at
`

type UpdateEmployeeIsSubcontractorParams struct {
	EmployeeID   uuid.UUID                `json:"employee_id"`
	ContractType EmployeeContractTypeEnum `json:"contract_type"`
}

func (q *Queries) UpdateEmployeeIsSubcontractor(ctx context.Context, arg UpdateEmployeeIsSubcontractorParams) (EmployeeContract, error) {
	row := q.db.QueryRow(ctx, updateEmployeeIsSubcontractor, arg.EmployeeID, arg.ContractType)
	var i EmployeeContract
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.JobTitle,
		&i.DepartmentID,
		&i.LocationID,
		&i.OrganizationalRoleID,
		&i.ContractType,
		&i.ContractHoursType,
		&i.StartDate,
		&i.ContractEndDate,
		&i.HoursPerWeek,
		&i.MinHoursPerWeek,
		&i.MaxHoursPerWeek,
		&i.RosterFreeDay,
		&i.WageTaxTable,
		&i.CreatedByEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
