// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leave_balance.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyLeaveBalanceDeduction = `-- name: ApplyLeaveBalanceDeduction :one
UPDATE leave_balances
SET
    extra_used_minutes = extra_used_minutes + $1,
    legal_used_minutes = legal_used_minutes + $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, employee_id, year, legal_adjustment_minutes, extra_total_minutes, legal_used_minutes, extra_used_minutes, created_at, updated_at
`

type ApplyLeaveBalanceDeductionParams struct {
	ExtraMinutes int32     `json:"extra_minutes"`
	LegalMinutes int32     `json:"legal_minutes"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) ApplyLeaveBalanceDeduction(ctx context.Context, arg ApplyLeaveBalanceDeductionParams) (LeaveBalance, error) {
	row := q.db.QueryRow(ctx, applyLeaveBalanceDeduction, arg.ExtraMinutes, arg.LegalMinutes, arg.ID)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Year,
		&i.LegalAdjustmentMinutes,
		&i.ExtraTotalMinutes,
		&i.LegalUsedMinutes,
		&i.ExtraUsedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const applyLeaveBalanceTotalAdjustment = `-- name: ApplyLeaveBalanceTotalAdjustment :one
UPDATE leave_balances
SET
    legal_adjustment_minutes = legal_adjustment_minutes + $1,
    extra_total_minutes = extra_total_minutes + $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, employee_id, year, legal_adjustment_minutes, extra_total_minutes, legal_used_minutes, extra_used_minutes, created_at, updated_at
`

type ApplyLeaveBalanceTotalAdjustmentParams struct {
	LegalAdjustmentMinutesDelta int32     `json:"legal_adjustment_minutes_delta"`
	ExtraTotalMinutesDelta      int32     `json:"extra_total_minutes_delta"`
	ID                          uuid.UUID `json:"id"`
}

func (q *Queries) ApplyLeaveBalanceTotalAdjustment(ctx context.Context, arg ApplyLeaveBalanceTotalAdjustmentParams) (LeaveBalance, error) {
	row := q.db.QueryRow(ctx, applyLeaveBalanceTotalAdjustment, arg.LegalAdjustmentMinutesDelta, arg.ExtraTotalMinutesDelta, arg.ID)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Year,
		&i.LegalAdjustmentMinutes,
		&i.ExtraTotalMinutes,
		&i.LegalUsedMinutes,
		&i.ExtraUsedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const computeLegalLeaveTotalForYear = `-- name: ComputeLegalLeaveTotalForYear :one
SELECT calculate_legal_leave_minutes(
    $1,
    $2::int,
    $3::timestamptz
)::int AS legal_total_minutes
`

type ComputeLegalLeaveTotalForYearParams struct {
	EmployeeID uuid.UUID          `json:"employee_id"`
	Year       int32              `json:"year"`
	AsOf       pgtype.Timestamptz `json:"as_of"`
}

func (q *Queries) ComputeLegalLeaveTotalForYear(ctx context.Context, arg ComputeLegalLeaveTotalForYearParams) (int32, error) {
	row := q.db.QueryRow(ctx, computeLegalLeaveTotalForYear, arg.EmployeeID, arg.Year, arg.AsOf)
	var legal_total_minutes int32
	err := row.Scan(&legal_total_minutes)
	return legal_total_minutes, err
}

const createLeaveBalanceAdjustmentAudit = `-- name: CreateLeaveBalanceAdjustmentAudit :one
INSERT INTO leave_balance_adjustments (
    leave_balance_id,
    employee_id,
    year,
    legal_adjustment_minutes_delta,
    extra_total_minutes_delta,
    reason,
    adjusted_by_employee_id,
    legal_adjustment_minutes_before,
    extra_total_minutes_before,
    legal_adjustment_minutes_after,
    extra_total_minutes_after
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, leave_balance_id, employee_id, year, legal_adjustment_minutes_delta, extra_total_minutes_delta, reason, adjusted_by_employee_id, legal_adjustment_minutes_before, extra_total_minutes_before, legal_adjustment_minutes_after, extra_total_minutes_after, created_at
`

type CreateLeaveBalanceAdjustmentAuditParams struct {
	LeaveBalanceID               uuid.UUID `json:"leave_balance_id"`
	EmployeeID                   uuid.UUID `json:"employee_id"`
	Year                         int32     `json:"year"`
	LegalAdjustmentMinutesDelta  int32     `json:"legal_adjustment_minutes_delta"`
	ExtraTotalMinutesDelta       int32     `json:"extra_total_minutes_delta"`
	Reason                       string    `json:"reason"`
	AdjustedByEmployeeID         uuid.UUID `json:"adjusted_by_employee_id"`
	LegalAdjustmentMinutesBefore int32     `json:"legal_adjustment_minutes_before"`
	ExtraTotalMinutesBefore      int32     `json:"extra_total_minutes_before"`
	LegalAdjustmentMinutesAfter  int32     `json:"legal_adjustment_minutes_after"`
	ExtraTotalMinutesAfter       int32     `json:"extra_total_minutes_after"`
}

func (q *Queries) CreateLeaveBalanceAdjustmentAudit(ctx context.Context, arg CreateLeaveBalanceAdjustmentAuditParams) (LeaveBalanceAdjustment, error) {
	row := q.db.QueryRow(ctx, createLeaveBalanceAdjustmentAudit,
		arg.LeaveBalanceID,
		arg.EmployeeID,
		arg.Year,
		arg.LegalAdjustmentMinutesDelta,
		arg.ExtraTotalMinutesDelta,
		arg.Reason,
		arg.AdjustedByEmployeeID,
		arg.LegalAdjustmentMinutesBefore,
		arg.ExtraTotalMinutesBefore,
		arg.LegalAdjustmentMinutesAfter,
		arg.ExtraTotalMinutesAfter,
	)
	var i LeaveBalanceAdjustment
	err := row.Scan(
		&i.ID,
		&i.LeaveBalanceID,
		&i.EmployeeID,
		&i.Year,
		&i.LegalAdjustmentMinutesDelta,
		&i.ExtraTotalMinutesDelta,
		&i.Reason,
		&i.AdjustedByEmployeeID,
		&i.LegalAdjustmentMinutesBefore,
		&i.ExtraTotalMinutesBefore,
		&i.LegalAdjustmentMinutesAfter,
		&i.ExtraTotalMinutesAfter,
		&i.CreatedAt,
	)
	return i, err
}

const ensureLeaveBalanceForYear = `-- name: EnsureLeaveBalanceForYear :exec
INSERT INTO leave_balances (
    employee_id,
    year,
    legal_adjustment_minutes,
    extra_total_minutes,
    legal_used_minutes,
    extra_used_minutes
) SELECT
    ep.id,
    $1,
    0,
    0,
    0,
    0
FROM employee_profile ep
WHERE ep.id = $2
ON CONFLICT (employee_id, year) DO NOTHING
`

type EnsureLeaveBalanceForYearParams struct {
	Year       int32     `json:"year"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

func (q *Queries) EnsureLeaveBalanceForYear(ctx context.Context, arg EnsureLeaveBalanceForYearParams) error {
	_, err := q.db.Exec(ctx, ensureLeaveBalanceForYear, arg.Year, arg.EmployeeID)
	return err
}

const getEmployeeContractForLeave = `-- name: GetEmployeeContractForLeave :one
SELECT
    hours_per_week AS contract_hours,
    contract_type
FROM employee_contracts
WHERE employee_id = $1
ORDER BY start_date DESC, created_at DESC
LIMIT 1
`

type GetEmployeeContractForLeaveRow struct {
	ContractHours *float64                 `json:"contract_hours"`
	ContractType  EmployeeContractTypeEnum `json:"contract_type"`
}

func (q *Queries) GetEmployeeContractForLeave(ctx context.Context, employeeID uuid.UUID) (GetEmployeeContractForLeaveRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeContractForLeave, employeeID)
	var i GetEmployeeContractForLeaveRow
	err := row.Scan(&i.ContractHours, &i.ContractType)
	return i, err
}

const listLeaveBalancesForEmployeeFromYearForUpdate = `-- name: ListLeaveBalancesForEmployeeFromYearForUpdate :many
SELECT id, employee_id, year, legal_adjustment_minutes, extra_total_minutes, legal_used_minutes, extra_used_minutes, created_at, updated_at
FROM leave_balances
WHERE employee_id = $1
  AND year >= $2
ORDER BY year
FOR UPDATE
`

type ListLeaveBalancesForEmployeeFromYearForUpdateParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	YearFrom   int32     `json:"year_from"`
}

func (q *Queries) ListLeaveBalancesForEmployeeFromYearForUpdate(ctx context.Context, arg ListLeaveBalancesForEmployeeFromYearForUpdateParams) ([]LeaveBalance, error) {
	rows, err := q.db.Query(ctx, listLeaveBalancesForEmployeeFromYearForUpdate, arg.EmployeeID, arg.YearFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaveBalance{}
	for rows.Next() {
		var i LeaveBalance
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Year,
			&i.LegalAdjustmentMinutes,
			&i.ExtraTotalMinutes,
			&i.LegalUsedMinutes,
			&i.ExtraUsedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveBalancesPaginated = `-- name: ListLeaveBalancesPaginated :many
SELECT
    lb.id,
    lb.employee_id,
    lb.year,
    (ent.legal_calculated_minutes + lb.legal_adjustment_minutes)::int AS legal_total_minutes,
    lb.legal_adjustment_minutes,
    lb.extra_total_minutes,
    lb.legal_used_minutes,
    lb.extra_used_minutes,
    lb.created_at,
    lb.updated_at,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ec.hours_per_week AS contract_hours,
    ec.contract_type,
    ec.start_date AS contract_start_date,
    ec.contract_end_date,
    ec.effective_end_date,
    COUNT(*) OVER() AS total_count
FROM leave_balances lb
JOIN employee_profile ep ON ep.id = lb.employee_id
JOIN LATERAL (
    SELECT calculate_legal_leave_minutes(
        lb.employee_id,
        lb.year,
        CASE
            WHEN lb.year < EXTRACT(YEAR FROM CURRENT_DATE)::int THEN
                (make_date(lb.year, 12, 31)::timestamp + INTERVAL '23 hours 59 minutes 59 seconds')::timestamptz
            WHEN lb.year = EXTRACT(YEAR FROM CURRENT_DATE)::int THEN
                CURRENT_TIMESTAMP
            ELSE
                make_date(lb.year, 1, 1)::timestamptz
        END
    )::int AS legal_calculated_minutes
) ent ON true
LEFT JOIN LATERAL (
    SELECT id, employee_id, job_title, department_id, location_id, organizational_role_id, contract_type, start_date, contract_end_date, effective_end_date, hours_per_week, roster_free_day, wage_tax_table, previous_contract_id, contract_event_type, change_reason, updated_by_employee_id, created_by_employee_id, created_at, updated_at
    FROM employee_contracts c
    WHERE c.employee_id = ep.id
    ORDER BY c.start_date DESC, c.created_at DESC
    LIMIT 1
) ec ON true
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR ep.first_name ILIKE '%' || $1::text || '%'
    OR ep.last_name ILIKE '%' || $1::text || '%'
    OR (ep.first_name || ' ' || ep.last_name) ILIKE '%' || $1::text || '%'
    OR (ep.last_name || ' ' || ep.first_name) ILIKE '%' || $1::text || '%'
)
  AND (
    $2::int IS NULL
    OR lb.year = $2::int
)
ORDER BY lb.year DESC, lb.updated_at DESC
LIMIT $4 OFFSET $3
`

type ListLeaveBalancesPaginatedParams struct {
	EmployeeSearch *string `json:"employee_search"`
	Year           *int32  `json:"year"`
	Offset         int32   `json:"offset"`
	Limit          int32   `json:"limit"`
}

type ListLeaveBalancesPaginatedRow struct {
	ID                     uuid.UUID                `json:"id"`
	EmployeeID             uuid.UUID                `json:"employee_id"`
	Year                   int32                    `json:"year"`
	LegalTotalMinutes      int32                    `json:"legal_total_minutes"`
	LegalAdjustmentMinutes int32                    `json:"legal_adjustment_minutes"`
	ExtraTotalMinutes      int32                    `json:"extra_total_minutes"`
	LegalUsedMinutes       int32                    `json:"legal_used_minutes"`
	ExtraUsedMinutes       int32                    `json:"extra_used_minutes"`
	CreatedAt              pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz       `json:"updated_at"`
	EmployeeFirstName      string                   `json:"employee_first_name"`
	EmployeeLastName       string                   `json:"employee_last_name"`
	ContractHours          *float64                 `json:"contract_hours"`
	ContractType           EmployeeContractTypeEnum `json:"contract_type"`
	ContractStartDate      pgtype.Date              `json:"contract_start_date"`
	ContractEndDate        pgtype.Date              `json:"contract_end_date"`
	EffectiveEndDate       pgtype.Date              `json:"effective_end_date"`
	TotalCount             int64                    `json:"total_count"`
}

func (q *Queries) ListLeaveBalancesPaginated(ctx context.Context, arg ListLeaveBalancesPaginatedParams) ([]ListLeaveBalancesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listLeaveBalancesPaginated,
		arg.EmployeeSearch,
		arg.Year,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeaveBalancesPaginatedRow{}
	for rows.Next() {
		var i ListLeaveBalancesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Year,
			&i.LegalTotalMinutes,
			&i.LegalAdjustmentMinutes,
			&i.ExtraTotalMinutes,
			&i.LegalUsedMinutes,
			&i.ExtraUsedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.ContractHours,
			&i.ContractType,
			&i.ContractStartDate,
			&i.ContractEndDate,
			&i.EffectiveEndDate,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyLeaveBalancesPaginated = `-- name: ListMyLeaveBalancesPaginated :many
SELECT
    lb.id,
    lb.employee_id,
    lb.year,
    (ent.legal_calculated_minutes + lb.legal_adjustment_minutes)::int AS legal_total_minutes,
    lb.legal_adjustment_minutes,
    lb.extra_total_minutes,
    lb.legal_used_minutes,
    lb.extra_used_minutes,
    lb.created_at,
    lb.updated_at,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ec.hours_per_week AS contract_hours,
    ec.contract_type,
    ec.start_date AS contract_start_date,
    ec.contract_end_date,
    ec.effective_end_date,
    COUNT(*) OVER() AS total_count
FROM leave_balances lb
JOIN employee_profile ep ON ep.id = lb.employee_id
JOIN LATERAL (
    SELECT calculate_legal_leave_minutes(
        lb.employee_id,
        lb.year,
        CASE
            WHEN lb.year < EXTRACT(YEAR FROM CURRENT_DATE)::int THEN
                (make_date(lb.year, 12, 31)::timestamp + INTERVAL '23 hours 59 minutes 59 seconds')::timestamptz
            WHEN lb.year = EXTRACT(YEAR FROM CURRENT_DATE)::int THEN
                CURRENT_TIMESTAMP
            ELSE
                make_date(lb.year, 1, 1)::timestamptz
        END
    )::int AS legal_calculated_minutes
) ent ON true
LEFT JOIN LATERAL (
    SELECT id, employee_id, job_title, department_id, location_id, organizational_role_id, contract_type, start_date, contract_end_date, effective_end_date, hours_per_week, roster_free_day, wage_tax_table, previous_contract_id, contract_event_type, change_reason, updated_by_employee_id, created_by_employee_id, created_at, updated_at
    FROM employee_contracts c
    WHERE c.employee_id = ep.id
    ORDER BY c.start_date DESC, c.created_at DESC
    LIMIT 1
) ec ON true
WHERE lb.employee_id = $1
  AND (
    $2::int IS NULL
    OR lb.year = $2::int
)
ORDER BY lb.year DESC, lb.updated_at DESC
LIMIT $4 OFFSET $3
`

type ListMyLeaveBalancesPaginatedParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	Year       *int32    `json:"year"`
	Offset     int32     `json:"offset"`
	Limit      int32     `json:"limit"`
}

type ListMyLeaveBalancesPaginatedRow struct {
	ID                     uuid.UUID                `json:"id"`
	EmployeeID             uuid.UUID                `json:"employee_id"`
	Year                   int32                    `json:"year"`
	LegalTotalMinutes      int32                    `json:"legal_total_minutes"`
	LegalAdjustmentMinutes int32                    `json:"legal_adjustment_minutes"`
	ExtraTotalMinutes      int32                    `json:"extra_total_minutes"`
	LegalUsedMinutes       int32                    `json:"legal_used_minutes"`
	ExtraUsedMinutes       int32                    `json:"extra_used_minutes"`
	CreatedAt              pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz       `json:"updated_at"`
	EmployeeFirstName      string                   `json:"employee_first_name"`
	EmployeeLastName       string                   `json:"employee_last_name"`
	ContractHours          *float64                 `json:"contract_hours"`
	ContractType           EmployeeContractTypeEnum `json:"contract_type"`
	ContractStartDate      pgtype.Date              `json:"contract_start_date"`
	ContractEndDate        pgtype.Date              `json:"contract_end_date"`
	EffectiveEndDate       pgtype.Date              `json:"effective_end_date"`
	TotalCount             int64                    `json:"total_count"`
}

func (q *Queries) ListMyLeaveBalancesPaginated(ctx context.Context, arg ListMyLeaveBalancesPaginatedParams) ([]ListMyLeaveBalancesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listMyLeaveBalancesPaginated,
		arg.EmployeeID,
		arg.Year,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyLeaveBalancesPaginatedRow{}
	for rows.Next() {
		var i ListMyLeaveBalancesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Year,
			&i.LegalTotalMinutes,
			&i.LegalAdjustmentMinutes,
			&i.ExtraTotalMinutes,
			&i.LegalUsedMinutes,
			&i.ExtraUsedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.ContractHours,
			&i.ContractType,
			&i.ContractStartDate,
			&i.ContractEndDate,
			&i.EffectiveEndDate,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLeaveBalanceByEmployeeYear = `-- name: LockLeaveBalanceByEmployeeYear :one
SELECT id, employee_id, year, legal_adjustment_minutes, extra_total_minutes, legal_used_minutes, extra_used_minutes, created_at, updated_at
FROM leave_balances
WHERE employee_id = $1
  AND year = $2
FOR UPDATE
`

type LockLeaveBalanceByEmployeeYearParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	Year       int32     `json:"year"`
}

func (q *Queries) LockLeaveBalanceByEmployeeYear(ctx context.Context, arg LockLeaveBalanceByEmployeeYearParams) (LeaveBalance, error) {
	row := q.db.QueryRow(ctx, lockLeaveBalanceByEmployeeYear, arg.EmployeeID, arg.Year)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Year,
		&i.LegalAdjustmentMinutes,
		&i.ExtraTotalMinutes,
		&i.LegalUsedMinutes,
		&i.ExtraUsedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
