// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AttendeeResponseEnum string

const (
	AttendeeResponseEnumNeedsAction AttendeeResponseEnum = "needs_action"
	AttendeeResponseEnumAccepted    AttendeeResponseEnum = "accepted"
	AttendeeResponseEnumDeclined    AttendeeResponseEnum = "declined"
	AttendeeResponseEnumTentative   AttendeeResponseEnum = "tentative"
)

func (e *AttendeeResponseEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttendeeResponseEnum(s)
	case string:
		*e = AttendeeResponseEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AttendeeResponseEnum: %T", src)
	}
	return nil
}

type NullAttendeeResponseEnum struct {
	AttendeeResponseEnum AttendeeResponseEnum `json:"attendee_response_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if AttendeeResponseEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttendeeResponseEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AttendeeResponseEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttendeeResponseEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttendeeResponseEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttendeeResponseEnum), nil
}

type CalendarEventKindEnum string

const (
	CalendarEventKindEnumAppointment CalendarEventKindEnum = "appointment"
	CalendarEventKindEnumReminder    CalendarEventKindEnum = "reminder"
)

func (e *CalendarEventKindEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CalendarEventKindEnum(s)
	case string:
		*e = CalendarEventKindEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CalendarEventKindEnum: %T", src)
	}
	return nil
}

type NullCalendarEventKindEnum struct {
	CalendarEventKindEnum CalendarEventKindEnum `json:"calendar_event_kind_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if CalendarEventKindEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCalendarEventKindEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CalendarEventKindEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CalendarEventKindEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCalendarEventKindEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CalendarEventKindEnum), nil
}

type CalendarEventStatusEnum string

const (
	CalendarEventStatusEnumConfirmed CalendarEventStatusEnum = "confirmed"
	CalendarEventStatusEnumCancelled CalendarEventStatusEnum = "cancelled"
)

func (e *CalendarEventStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CalendarEventStatusEnum(s)
	case string:
		*e = CalendarEventStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CalendarEventStatusEnum: %T", src)
	}
	return nil
}

type NullCalendarEventStatusEnum struct {
	CalendarEventStatusEnum CalendarEventStatusEnum `json:"calendar_event_status_enum"`
	Valid                   bool                    `json:"valid"` // Valid is true if CalendarEventStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCalendarEventStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CalendarEventStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CalendarEventStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCalendarEventStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CalendarEventStatusEnum), nil
}

type CalendarEventWorkApprovalStatusEnum string

const (
	CalendarEventWorkApprovalStatusEnumPending  CalendarEventWorkApprovalStatusEnum = "pending"
	CalendarEventWorkApprovalStatusEnumApproved CalendarEventWorkApprovalStatusEnum = "approved"
	CalendarEventWorkApprovalStatusEnumRejected CalendarEventWorkApprovalStatusEnum = "rejected"
)

func (e *CalendarEventWorkApprovalStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CalendarEventWorkApprovalStatusEnum(s)
	case string:
		*e = CalendarEventWorkApprovalStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CalendarEventWorkApprovalStatusEnum: %T", src)
	}
	return nil
}

type NullCalendarEventWorkApprovalStatusEnum struct {
	CalendarEventWorkApprovalStatusEnum CalendarEventWorkApprovalStatusEnum `json:"calendar_event_work_approval_status_enum"`
	Valid                               bool                                `json:"valid"` // Valid is true if CalendarEventWorkApprovalStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCalendarEventWorkApprovalStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CalendarEventWorkApprovalStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CalendarEventWorkApprovalStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCalendarEventWorkApprovalStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CalendarEventWorkApprovalStatusEnum), nil
}

type EmployeeContractTypeEnum string

const (
	EmployeeContractTypeEnumLoondienst EmployeeContractTypeEnum = "loondienst"
	EmployeeContractTypeEnumZZP        EmployeeContractTypeEnum = "ZZP"
	EmployeeContractTypeEnumNone       EmployeeContractTypeEnum = "none"
)

func (e *EmployeeContractTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmployeeContractTypeEnum(s)
	case string:
		*e = EmployeeContractTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EmployeeContractTypeEnum: %T", src)
	}
	return nil
}

type NullEmployeeContractTypeEnum struct {
	EmployeeContractTypeEnum EmployeeContractTypeEnum `json:"employee_contract_type_enum"`
	Valid                    bool                     `json:"valid"` // Valid is true if EmployeeContractTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmployeeContractTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EmployeeContractTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmployeeContractTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmployeeContractTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmployeeContractTypeEnum), nil
}

type GenderEnum string

const (
	GenderEnumMale    GenderEnum = "male"
	GenderEnumFemale  GenderEnum = "female"
	GenderEnumOther   GenderEnum = "other"
	GenderEnumUnknown GenderEnum = "unknown"
)

func (e *GenderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderEnum(s)
	case string:
		*e = GenderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderEnum: %T", src)
	}
	return nil
}

type NullGenderEnum struct {
	GenderEnum GenderEnum `json:"gender_enum"`
	Valid      bool       `json:"valid"` // Valid is true if GenderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GenderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderEnum), nil
}

type HandbookAssignmentEventEnum string

const (
	HandbookAssignmentEventEnumAssigned   HandbookAssignmentEventEnum = "assigned"
	HandbookAssignmentEventEnumReassigned HandbookAssignmentEventEnum = "reassigned"
	HandbookAssignmentEventEnumWaived     HandbookAssignmentEventEnum = "waived"
	HandbookAssignmentEventEnumStarted    HandbookAssignmentEventEnum = "started"
	HandbookAssignmentEventEnumCompleted  HandbookAssignmentEventEnum = "completed"
)

func (e *HandbookAssignmentEventEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HandbookAssignmentEventEnum(s)
	case string:
		*e = HandbookAssignmentEventEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for HandbookAssignmentEventEnum: %T", src)
	}
	return nil
}

type NullHandbookAssignmentEventEnum struct {
	HandbookAssignmentEventEnum HandbookAssignmentEventEnum `json:"handbook_assignment_event_enum"`
	Valid                       bool                        `json:"valid"` // Valid is true if HandbookAssignmentEventEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHandbookAssignmentEventEnum) Scan(value interface{}) error {
	if value == nil {
		ns.HandbookAssignmentEventEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HandbookAssignmentEventEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHandbookAssignmentEventEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HandbookAssignmentEventEnum), nil
}

type HandbookAssignmentStatusEnum string

const (
	HandbookAssignmentStatusEnumNotStarted HandbookAssignmentStatusEnum = "not_started"
	HandbookAssignmentStatusEnumInProgress HandbookAssignmentStatusEnum = "in_progress"
	HandbookAssignmentStatusEnumCompleted  HandbookAssignmentStatusEnum = "completed"
	HandbookAssignmentStatusEnumWaived     HandbookAssignmentStatusEnum = "waived"
)

func (e *HandbookAssignmentStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HandbookAssignmentStatusEnum(s)
	case string:
		*e = HandbookAssignmentStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for HandbookAssignmentStatusEnum: %T", src)
	}
	return nil
}

type NullHandbookAssignmentStatusEnum struct {
	HandbookAssignmentStatusEnum HandbookAssignmentStatusEnum `json:"handbook_assignment_status_enum"`
	Valid                        bool                         `json:"valid"` // Valid is true if HandbookAssignmentStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHandbookAssignmentStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.HandbookAssignmentStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HandbookAssignmentStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHandbookAssignmentStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HandbookAssignmentStatusEnum), nil
}

type HandbookStepKindEnum string

const (
	HandbookStepKindEnumContent HandbookStepKindEnum = "content"
	HandbookStepKindEnumAck     HandbookStepKindEnum = "ack"
	HandbookStepKindEnumLink    HandbookStepKindEnum = "link"
	HandbookStepKindEnumQuiz    HandbookStepKindEnum = "quiz"
)

func (e *HandbookStepKindEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HandbookStepKindEnum(s)
	case string:
		*e = HandbookStepKindEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for HandbookStepKindEnum: %T", src)
	}
	return nil
}

type NullHandbookStepKindEnum struct {
	HandbookStepKindEnum HandbookStepKindEnum `json:"handbook_step_kind_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if HandbookStepKindEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHandbookStepKindEnum) Scan(value interface{}) error {
	if value == nil {
		ns.HandbookStepKindEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HandbookStepKindEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHandbookStepKindEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HandbookStepKindEnum), nil
}

type HandbookStepStatusEnum string

const (
	HandbookStepStatusEnumPending   HandbookStepStatusEnum = "pending"
	HandbookStepStatusEnumCompleted HandbookStepStatusEnum = "completed"
	HandbookStepStatusEnumSkipped   HandbookStepStatusEnum = "skipped"
)

func (e *HandbookStepStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HandbookStepStatusEnum(s)
	case string:
		*e = HandbookStepStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for HandbookStepStatusEnum: %T", src)
	}
	return nil
}

type NullHandbookStepStatusEnum struct {
	HandbookStepStatusEnum HandbookStepStatusEnum `json:"handbook_step_status_enum"`
	Valid                  bool                   `json:"valid"` // Valid is true if HandbookStepStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHandbookStepStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.HandbookStepStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HandbookStepStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHandbookStepStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HandbookStepStatusEnum), nil
}

type HandbookTemplateStatusEnum string

const (
	HandbookTemplateStatusEnumDraft     HandbookTemplateStatusEnum = "draft"
	HandbookTemplateStatusEnumPublished HandbookTemplateStatusEnum = "published"
	HandbookTemplateStatusEnumArchived  HandbookTemplateStatusEnum = "archived"
)

func (e *HandbookTemplateStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HandbookTemplateStatusEnum(s)
	case string:
		*e = HandbookTemplateStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for HandbookTemplateStatusEnum: %T", src)
	}
	return nil
}

type NullHandbookTemplateStatusEnum struct {
	HandbookTemplateStatusEnum HandbookTemplateStatusEnum `json:"handbook_template_status_enum"`
	Valid                      bool                       `json:"valid"` // Valid is true if HandbookTemplateStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHandbookTemplateStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.HandbookTemplateStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HandbookTemplateStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHandbookTemplateStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HandbookTemplateStatusEnum), nil
}

type LeaveRequestStatusEnum string

const (
	LeaveRequestStatusEnumPending   LeaveRequestStatusEnum = "pending"
	LeaveRequestStatusEnumApproved  LeaveRequestStatusEnum = "approved"
	LeaveRequestStatusEnumRejected  LeaveRequestStatusEnum = "rejected"
	LeaveRequestStatusEnumCancelled LeaveRequestStatusEnum = "cancelled"
	LeaveRequestStatusEnumExpired   LeaveRequestStatusEnum = "expired"
)

func (e *LeaveRequestStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaveRequestStatusEnum(s)
	case string:
		*e = LeaveRequestStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaveRequestStatusEnum: %T", src)
	}
	return nil
}

type NullLeaveRequestStatusEnum struct {
	LeaveRequestStatusEnum LeaveRequestStatusEnum `json:"leave_request_status_enum"`
	Valid                  bool                   `json:"valid"` // Valid is true if LeaveRequestStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeaveRequestStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.LeaveRequestStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeaveRequestStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeaveRequestStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeaveRequestStatusEnum), nil
}

type LeaveRequestTypeEnum string

const (
	LeaveRequestTypeEnumVacation  LeaveRequestTypeEnum = "vacation"
	LeaveRequestTypeEnumPersonal  LeaveRequestTypeEnum = "personal"
	LeaveRequestTypeEnumSick      LeaveRequestTypeEnum = "sick"
	LeaveRequestTypeEnumPregnancy LeaveRequestTypeEnum = "pregnancy"
	LeaveRequestTypeEnumUnpaid    LeaveRequestTypeEnum = "unpaid"
	LeaveRequestTypeEnumOther     LeaveRequestTypeEnum = "other"
)

func (e *LeaveRequestTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaveRequestTypeEnum(s)
	case string:
		*e = LeaveRequestTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaveRequestTypeEnum: %T", src)
	}
	return nil
}

type NullLeaveRequestTypeEnum struct {
	LeaveRequestTypeEnum LeaveRequestTypeEnum `json:"leave_request_type_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if LeaveRequestTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeaveRequestTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.LeaveRequestTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeaveRequestTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeaveRequestTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeaveRequestTypeEnum), nil
}

type LocationTypeEnum string

const (
	LocationTypeEnumCareHome LocationTypeEnum = "care_home"
	LocationTypeEnumOffice   LocationTypeEnum = "office"
	LocationTypeEnumOther    LocationTypeEnum = "other"
)

func (e *LocationTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationTypeEnum(s)
	case string:
		*e = LocationTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationTypeEnum: %T", src)
	}
	return nil
}

type NullLocationTypeEnum struct {
	LocationTypeEnum LocationTypeEnum `json:"location_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if LocationTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.LocationTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationTypeEnum), nil
}

type NotificationTypeEnum string

const (
	NotificationTypeEnumGeneral NotificationTypeEnum = "general"
)

func (e *NotificationTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationTypeEnum(s)
	case string:
		*e = NotificationTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationTypeEnum: %T", src)
	}
	return nil
}

type NullNotificationTypeEnum struct {
	NotificationTypeEnum NotificationTypeEnum `json:"notification_type_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if NotificationTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationTypeEnum), nil
}

type PermissionOverrideEffect string

const (
	PermissionOverrideEffectAllow PermissionOverrideEffect = "allow"
	PermissionOverrideEffectDeny  PermissionOverrideEffect = "deny"
)

func (e *PermissionOverrideEffect) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionOverrideEffect(s)
	case string:
		*e = PermissionOverrideEffect(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionOverrideEffect: %T", src)
	}
	return nil
}

type NullPermissionOverrideEffect struct {
	PermissionOverrideEffect PermissionOverrideEffect `json:"permission_override_effect"`
	Valid                    bool                     `json:"valid"` // Valid is true if PermissionOverrideEffect is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionOverrideEffect) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionOverrideEffect, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionOverrideEffect.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionOverrideEffect) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionOverrideEffect), nil
}

type ReminderChannelEnum string

const (
	ReminderChannelEnumInApp ReminderChannelEnum = "in_app"
)

func (e *ReminderChannelEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderChannelEnum(s)
	case string:
		*e = ReminderChannelEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderChannelEnum: %T", src)
	}
	return nil
}

type NullReminderChannelEnum struct {
	ReminderChannelEnum ReminderChannelEnum `json:"reminder_channel_enum"`
	Valid               bool                `json:"valid"` // Valid is true if ReminderChannelEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderChannelEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderChannelEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderChannelEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderChannelEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderChannelEnum), nil
}

type ShiftSwapStatusEnum string

const (
	ShiftSwapStatusEnumPendingRecipient  ShiftSwapStatusEnum = "pending_recipient"
	ShiftSwapStatusEnumRecipientRejected ShiftSwapStatusEnum = "recipient_rejected"
	ShiftSwapStatusEnumPendingAdmin      ShiftSwapStatusEnum = "pending_admin"
	ShiftSwapStatusEnumAdminRejected     ShiftSwapStatusEnum = "admin_rejected"
	ShiftSwapStatusEnumConfirmed         ShiftSwapStatusEnum = "confirmed"
	ShiftSwapStatusEnumCancelled         ShiftSwapStatusEnum = "cancelled"
	ShiftSwapStatusEnumExpired           ShiftSwapStatusEnum = "expired"
)

func (e *ShiftSwapStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShiftSwapStatusEnum(s)
	case string:
		*e = ShiftSwapStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ShiftSwapStatusEnum: %T", src)
	}
	return nil
}

type NullShiftSwapStatusEnum struct {
	ShiftSwapStatusEnum ShiftSwapStatusEnum `json:"shift_swap_status_enum"`
	Valid               bool                `json:"valid"` // Valid is true if ShiftSwapStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShiftSwapStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ShiftSwapStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShiftSwapStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShiftSwapStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShiftSwapStatusEnum), nil
}

type AppOrganizationProfile struct {
	Singleton             bool               `json:"singleton"`
	Name                  string             `json:"name"`
	DefaultTimezone       string             `json:"default_timezone"`
	Email                 *string            `json:"email"`
	PhoneNumber           *string            `json:"phone_number"`
	Website               *string            `json:"website"`
	HqStreet              *string            `json:"hq_street"`
	HqHouseNumber         *string            `json:"hq_house_number"`
	HqHouseNumberAddition *string            `json:"hq_house_number_addition"`
	HqPostalCode          *string            `json:"hq_postal_code"`
	HqCity                *string            `json:"hq_city"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AttachmentFile struct {
	Uuid    uuid.UUID          `json:"uuid"`
	Name    string             `json:"name"`
	File    string             `json:"file"`
	Size    int32              `json:"size"`
	IsUsed  bool               `json:"is_used"`
	Tag     *string            `json:"tag"`
	Updated pgtype.Timestamptz `json:"updated"`
	Created pgtype.Timestamptz `json:"created"`
}

type CalendarEvent struct {
	ID                  uuid.UUID                           `json:"id"`
	OrganizerEmployeeID uuid.UUID                           `json:"organizer_employee_id"`
	CreatedByEmployeeID uuid.UUID                           `json:"created_by_employee_id"`
	Kind                CalendarEventKindEnum               `json:"kind"`
	Status              CalendarEventStatusEnum             `json:"status"`
	WorkApprovalStatus  CalendarEventWorkApprovalStatusEnum `json:"work_approval_status"`
	WorkApprovedBy      *uuid.UUID                          `json:"work_approved_by"`
	WorkApprovedAt      pgtype.Timestamptz                  `json:"work_approved_at"`
	WorkRejectedBy      *uuid.UUID                          `json:"work_rejected_by"`
	WorkRejectedAt      pgtype.Timestamptz                  `json:"work_rejected_at"`
	WorkRejectionReason *string                             `json:"work_rejection_reason"`
	Title               string                              `json:"title"`
	Description         *string                             `json:"description"`
	Location            *string                             `json:"location"`
	Color               *string                             `json:"color"`
	StartAt             pgtype.Timestamptz                  `json:"start_at"`
	EndAt               pgtype.Timestamptz                  `json:"end_at"`
	Timezone            string                              `json:"timezone"`
	Rrule               *string                             `json:"rrule"`
	RecurringEventID    *uuid.UUID                          `json:"recurring_event_id"`
	RecurrenceID        pgtype.Timestamptz                  `json:"recurrence_id"`
	CreatedAt           pgtype.Timestamptz                  `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz                  `json:"updated_at"`
}

type CalendarEventAttendee struct {
	ID         uuid.UUID            `json:"id"`
	EventID    uuid.UUID            `json:"event_id"`
	EmployeeID *uuid.UUID           `json:"employee_id"`
	Email      *string              `json:"email"`
	Response   AttendeeResponseEnum `json:"response"`
	CreatedAt  pgtype.Timestamptz   `json:"created_at"`
}

type CalendarEventReminder struct {
	ID            uuid.UUID           `json:"id"`
	EventID       uuid.UUID           `json:"event_id"`
	Channel       ReminderChannelEnum `json:"channel"`
	MinutesBefore *int32              `json:"minutes_before"`
	RemindAt      pgtype.Timestamptz  `json:"remind_at"`
	CreatedAt     pgtype.Timestamptz  `json:"created_at"`
}

type Certification struct {
	ID         uuid.UUID          `json:"id"`
	EmployeeID uuid.UUID          `json:"employee_id"`
	Name       string             `json:"name"`
	IssuedBy   string             `json:"issued_by"`
	DateIssued pgtype.Date        `json:"date_issued"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CustomUser struct {
	ID                  uuid.UUID          `json:"id"`
	Password            string             `json:"password"`
	LastLogin           pgtype.Timestamptz `json:"last_login"`
	Email               string             `json:"email"`
	IsActive            bool               `json:"is_active"`
	DateJoined          pgtype.Timestamptz `json:"date_joined"`
	ProfilePicture      *string            `json:"profile_picture"`
	TwoFactorEnabled    bool               `json:"two_factor_enabled"`
	TwoFactorSecret     *string            `json:"two_factor_secret"`
	TwoFactorSecretTemp *string            `json:"two_factor_secret_temp"`
	RecoveryCodes       []string           `json:"recovery_codes"`
}

type Department struct {
	ID                       uuid.UUID          `json:"id"`
	Name                     string             `json:"name"`
	Description              *string            `json:"description"`
	DepartmentHeadEmployeeID *uuid.UUID         `json:"department_head_employee_id"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type EmployeeEducation struct {
	ID              uuid.UUID          `json:"id"`
	EmployeeID      uuid.UUID          `json:"employee_id"`
	InstitutionName string             `json:"institution_name"`
	Degree          string             `json:"degree"`
	FieldOfStudy    string             `json:"field_of_study"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type EmployeeExperience struct {
	ID          uuid.UUID          `json:"id"`
	EmployeeID  uuid.UUID          `json:"employee_id"`
	JobTitle    string             `json:"job_title"`
	CompanyName string             `json:"company_name"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EmployeeHandbook struct {
	ID                   uuid.UUID                    `json:"id"`
	EmployeeID           uuid.UUID                    `json:"employee_id"`
	TemplateID           uuid.UUID                    `json:"template_id"`
	TemplateVersion      int32                        `json:"template_version"`
	AssignedByEmployeeID *uuid.UUID                   `json:"assigned_by_employee_id"`
	Status               HandbookAssignmentStatusEnum `json:"status"`
	AssignedAt           pgtype.Timestamptz           `json:"assigned_at"`
	StartedAt            pgtype.Timestamptz           `json:"started_at"`
	CompletedAt          pgtype.Timestamptz           `json:"completed_at"`
	DueAt                pgtype.Timestamptz           `json:"due_at"`
}

type EmployeeHandbookAssignmentHistory struct {
	ID                 uuid.UUID                   `json:"id"`
	EmployeeHandbookID *uuid.UUID                  `json:"employee_handbook_id"`
	EmployeeID         uuid.UUID                   `json:"employee_id"`
	TemplateID         uuid.UUID                   `json:"template_id"`
	TemplateVersion    int32                       `json:"template_version"`
	Event              HandbookAssignmentEventEnum `json:"event"`
	ActorEmployeeID    *uuid.UUID                  `json:"actor_employee_id"`
	Metadata           []byte                      `json:"metadata"`
	CreatedAt          pgtype.Timestamptz          `json:"created_at"`
}

type EmployeeHandbookStepProgress struct {
	EmployeeHandbookID uuid.UUID              `json:"employee_handbook_id"`
	StepID             uuid.UUID              `json:"step_id"`
	Status             HandbookStepStatusEnum `json:"status"`
	StartedAt          pgtype.Timestamptz     `json:"started_at"`
	CompletedAt        pgtype.Timestamptz     `json:"completed_at"`
	Response           []byte                 `json:"response"`
}

type EmployeeProfile struct {
	ID                  uuid.UUID                `json:"id"`
	UserID              uuid.UUID                `json:"user_id"`
	FirstName           string                   `json:"first_name"`
	LastName            string                   `json:"last_name"`
	Bsn                 string                   `json:"bsn"`
	Street              string                   `json:"street"`
	HouseNumber         string                   `json:"house_number"`
	HouseNumberAddition *string                  `json:"house_number_addition"`
	PostalCode          string                   `json:"postal_code"`
	City                string                   `json:"city"`
	Position            *string                  `json:"position"`
	EmployeeNumber      *string                  `json:"employee_number"`
	EmploymentNumber    *string                  `json:"employment_number"`
	PrivateEmailAddress *string                  `json:"private_email_address"`
	WorkEmailAddress    *string                  `json:"work_email_address"`
	PrivatePhoneNumber  *string                  `json:"private_phone_number"`
	WorkPhoneNumber     *string                  `json:"work_phone_number"`
	DateOfBirth         pgtype.Date              `json:"date_of_birth"`
	HomeTelephoneNumber *string                  `json:"home_telephone_number"`
	CreatedAt           pgtype.Timestamptz       `json:"created_at"`
	Gender              GenderEnum               `json:"gender"`
	LocationID          *uuid.UUID               `json:"location_id"`
	DepartmentID        *uuid.UUID               `json:"department_id"`
	ManagerEmployeeID   *uuid.UUID               `json:"manager_employee_id"`
	HasBorrowed         bool                     `json:"has_borrowed"`
	OutOfService        *bool                    `json:"out_of_service"`
	IsArchived          bool                     `json:"is_archived"`
	ContractHours       *float64                 `json:"contract_hours"`
	ContractEndDate     pgtype.Date              `json:"contract_end_date"`
	ContractStartDate   pgtype.Date              `json:"contract_start_date"`
	ContractType        EmployeeContractTypeEnum `json:"contract_type"`
	ContractRate        *float64                 `json:"contract_rate"`
}

type HandbookStep struct {
	ID         uuid.UUID            `json:"id"`
	TemplateID uuid.UUID            `json:"template_id"`
	SortOrder  int32                `json:"sort_order"`
	Kind       HandbookStepKindEnum `json:"kind"`
	Title      string               `json:"title"`
	Body       *string              `json:"body"`
	Content    []byte               `json:"content"`
	IsRequired bool                 `json:"is_required"`
	CreatedAt  pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz   `json:"updated_at"`
}

type HandbookTemplate struct {
	ID                    uuid.UUID                  `json:"id"`
	DepartmentID          uuid.UUID                  `json:"department_id"`
	Title                 string                     `json:"title"`
	Description           *string                    `json:"description"`
	Version               int32                      `json:"version"`
	Status                HandbookTemplateStatusEnum `json:"status"`
	CreatedByEmployeeID   *uuid.UUID                 `json:"created_by_employee_id"`
	PublishedByEmployeeID *uuid.UUID                 `json:"published_by_employee_id"`
	PublishedAt           pgtype.Timestamptz         `json:"published_at"`
	ArchivedAt            pgtype.Timestamptz         `json:"archived_at"`
	CreatedAt             pgtype.Timestamptz         `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz         `json:"updated_at"`
}

type LateArrival struct {
	ID                  uuid.UUID          `json:"id"`
	ScheduleID          uuid.UUID          `json:"schedule_id"`
	EmployeeID          uuid.UUID          `json:"employee_id"`
	CreatedByEmployeeID *uuid.UUID         `json:"created_by_employee_id"`
	ArrivalDate         pgtype.Date        `json:"arrival_date"`
	ArrivalTime         pgtype.Time        `json:"arrival_time"`
	Reason              string             `json:"reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type LeaveBalance struct {
	ID             uuid.UUID          `json:"id"`
	EmployeeID     uuid.UUID          `json:"employee_id"`
	Year           int32              `json:"year"`
	LegalTotalDays int32              `json:"legal_total_days"`
	ExtraTotalDays int32              `json:"extra_total_days"`
	LegalUsedDays  int32              `json:"legal_used_days"`
	ExtraUsedDays  int32              `json:"extra_used_days"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LeaveBalanceAdjustment struct {
	ID                   uuid.UUID          `json:"id"`
	LeaveBalanceID       uuid.UUID          `json:"leave_balance_id"`
	EmployeeID           uuid.UUID          `json:"employee_id"`
	Year                 int32              `json:"year"`
	LegalDaysDelta       int32              `json:"legal_days_delta"`
	ExtraDaysDelta       int32              `json:"extra_days_delta"`
	Reason               string             `json:"reason"`
	AdjustedByEmployeeID uuid.UUID          `json:"adjusted_by_employee_id"`
	LegalTotalDaysBefore int32              `json:"legal_total_days_before"`
	ExtraTotalDaysBefore int32              `json:"extra_total_days_before"`
	LegalTotalDaysAfter  int32              `json:"legal_total_days_after"`
	ExtraTotalDaysAfter  int32              `json:"extra_total_days_after"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type LeavePolicy struct {
	LeaveType        LeaveRequestTypeEnum `json:"leave_type"`
	RequiresApproval bool                 `json:"requires_approval"`
	DeductsBalance   bool                 `json:"deducts_balance"`
	IsActive         bool                 `json:"is_active"`
	CreatedAt        pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz   `json:"updated_at"`
}

type LeaveRequest struct {
	ID                  uuid.UUID              `json:"id"`
	EmployeeID          uuid.UUID              `json:"employee_id"`
	CreatedByEmployeeID *uuid.UUID             `json:"created_by_employee_id"`
	LeaveType           LeaveRequestTypeEnum   `json:"leave_type"`
	Status              LeaveRequestStatusEnum `json:"status"`
	StartDate           pgtype.Date            `json:"start_date"`
	EndDate             pgtype.Date            `json:"end_date"`
	Reason              *string                `json:"reason"`
	DecisionNote        *string                `json:"decision_note"`
	DecidedByEmployeeID *uuid.UUID             `json:"decided_by_employee_id"`
	RequestedAt         pgtype.Timestamptz     `json:"requested_at"`
	DecidedAt           pgtype.Timestamptz     `json:"decided_at"`
	CancelledAt         pgtype.Timestamptz     `json:"cancelled_at"`
	CreatedAt           pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz     `json:"updated_at"`
}

type Location struct {
	ID                  uuid.UUID          `json:"id"`
	OrganisationID      uuid.UUID          `json:"organisation_id"`
	Name                string             `json:"name"`
	Street              string             `json:"street"`
	HouseNumber         string             `json:"house_number"`
	HouseNumberAddition *string            `json:"house_number_addition"`
	PostalCode          string             `json:"postal_code"`
	City                string             `json:"city"`
	Timezone            string             `json:"timezone"`
	LocationType        LocationTypeEnum   `json:"location_type"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type LocationShift struct {
	ID         uuid.UUID        `json:"id"`
	LocationID uuid.UUID        `json:"location_id"`
	Slot       int16            `json:"slot"`
	ShiftName  string           `json:"shift_name"`
	StartTime  pgtype.Time      `json:"start_time"`
	EndTime    pgtype.Time      `json:"end_time"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Notification struct {
	ID        uuid.UUID            `json:"id"`
	UserID    uuid.UUID            `json:"user_id"`
	Type      NotificationTypeEnum `json:"type"`
	Message   string               `json:"message"`
	IsRead    bool                 `json:"is_read"`
	Data      []byte               `json:"data"`
	ReadAt    pgtype.Timestamptz   `json:"read_at"`
	CreatedAt pgtype.Timestamptz   `json:"created_at"`
}

type Organisation struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Street              string             `json:"street"`
	HouseNumber         string             `json:"house_number"`
	HouseNumberAddition *string            `json:"house_number_addition"`
	PostalCode          string             `json:"postal_code"`
	City                string             `json:"city"`
	PhoneNumber         *string            `json:"phone_number"`
	Email               *string            `json:"email"`
	KvkNumber           *string            `json:"kvk_number"`
	BtwNumber           *string            `json:"btw_number"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Resource    string    `json:"resource"`
	Method      string    `json:"method"`
	GroupKey    string    `json:"group_key"`
	SectionKey  string    `json:"section_key"`
	DisplayName string    `json:"display_name"`
	Description *string   `json:"description"`
	SortOrder   int32     `json:"sort_order"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type Schedule struct {
	ID                     uuid.UUID          `json:"id"`
	EmployeeID             uuid.UUID          `json:"employee_id"`
	LocationID             uuid.UUID          `json:"location_id"`
	LocationShiftID        *uuid.UUID         `json:"location_shift_id"`
	ShiftNameSnapshot      *string            `json:"shift_name_snapshot"`
	ShiftStartTimeSnapshot pgtype.Time        `json:"shift_start_time_snapshot"`
	ShiftEndTimeSnapshot   pgtype.Time        `json:"shift_end_time_snapshot"`
	IsCustom               bool               `json:"is_custom"`
	StartDatetime          pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime            pgtype.Timestamptz `json:"end_datetime"`
	CreatedByEmployeeID    uuid.UUID          `json:"created_by_employee_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID          `json:"id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserID       uuid.UUID          `json:"user_id"`
}

type ShiftSwapRequest struct {
	ID                    uuid.UUID           `json:"id"`
	RequesterEmployeeID   uuid.UUID           `json:"requester_employee_id"`
	RecipientEmployeeID   uuid.UUID           `json:"recipient_employee_id"`
	RequesterScheduleID   uuid.UUID           `json:"requester_schedule_id"`
	RecipientScheduleID   uuid.UUID           `json:"recipient_schedule_id"`
	Status                ShiftSwapStatusEnum `json:"status"`
	RequestedAt           pgtype.Timestamptz  `json:"requested_at"`
	RecipientRespondedAt  pgtype.Timestamptz  `json:"recipient_responded_at"`
	AdminDecidedAt        pgtype.Timestamptz  `json:"admin_decided_at"`
	RecipientResponseNote *string             `json:"recipient_response_note"`
	AdminDecisionNote     *string             `json:"admin_decision_note"`
	AdminEmployeeID       *uuid.UUID          `json:"admin_employee_id"`
	ExpiresAt             pgtype.Timestamptz  `json:"expires_at"`
	CreatedAt             pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz  `json:"updated_at"`
}

type TemporaryFile struct {
	ID         uuid.UUID          `json:"id"`
	File       string             `json:"file"`
	UploadedAt pgtype.Timestamptz `json:"uploaded_at"`
}

type UserPermissionOverride struct {
	UserID       uuid.UUID                `json:"user_id"`
	PermissionID uuid.UUID                `json:"permission_id"`
	Effect       PermissionOverrideEffect `json:"effect"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
