// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizational_roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listOrganizationalRoles = `-- name: ListOrganizationalRoles :many
SELECT id, name, description, is_active
FROM organizational_roles
WHERE (
    $1::bool IS NULL
    OR $1::bool = false
    OR is_active = true
)
AND (
    $2::text IS NULL
    OR name ILIKE '%' || $2::text || '%'
    OR description ILIKE '%' || $2::text || '%'
)
ORDER BY name
`

type ListOrganizationalRolesParams struct {
	ActiveOnly *bool   `json:"active_only"`
	Search     *string `json:"search"`
}

type ListOrganizationalRolesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsActive    bool      `json:"is_active"`
}

func (q *Queries) ListOrganizationalRoles(ctx context.Context, arg ListOrganizationalRolesParams) ([]ListOrganizationalRolesRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationalRoles, arg.ActiveOnly, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationalRolesRow{}
	for rows.Next() {
		var i ListOrganizationalRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
