// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payroll_month_summary.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listFixedPayrollContractSegments = `-- name: ListFixedPayrollContractSegments :many
WITH contract_windows AS (
    SELECT
        c.id AS contract_id,
        c.employee_id,
        c.contract_type,
        GREATEST(c.start_date, $1::date)::date AS active_from,
        LEAST(
            $2::date,
            COALESCE(c.effective_end_date, $2::date),
            COALESCE(c.contract_end_date, $2::date)
        )::date AS active_until,
        c.hours_per_week::double precision AS hours_per_week
    FROM employee_contracts c
    WHERE c.employee_id = ANY($3::uuid[])
      AND c.contract_type IN ('permanent'::employee_contract_type_enum, 'temporary'::employee_contract_type_enum)
      AND c.start_date <= $2
      AND (c.effective_end_date IS NULL OR c.effective_end_date >= $1)
      AND (c.contract_end_date IS NULL OR c.contract_end_date >= $1)
)
SELECT
    cw.employee_id,
    cw.contract_id,
    cw.contract_type,
    cw.active_from,
    cw.active_until,
    cw.hours_per_week,
    cst.full_time_hours_per_week::double precision AS full_time_hours_per_week,
    css.monthly_salary::double precision AS monthly_salary,
    css.hourly_rate::double precision AS hourly_rate
FROM contract_windows cw
JOIN LATERAL (
    SELECT esa.salary_scale_step_id
    FROM employee_salary_assignments esa
    WHERE esa.employee_id = cw.employee_id
      AND (esa.contract_id IS NULL OR esa.contract_id = cw.contract_id)
      AND esa.effective_from <= cw.active_until
      AND (esa.effective_to IS NULL OR esa.effective_to > cw.active_from)
    ORDER BY
      (esa.contract_id = cw.contract_id) DESC,
      esa.effective_from DESC,
      esa.created_at DESC
    LIMIT 1
) latest_salary ON TRUE
JOIN cao_salary_scale_steps css ON css.id = latest_salary.salary_scale_step_id
JOIN cao_salary_tables cst ON cst.id = css.salary_table_id
WHERE cw.active_until >= cw.active_from
ORDER BY cw.employee_id ASC, cw.active_from ASC, cw.contract_id ASC
`

type ListFixedPayrollContractSegmentsParams struct {
	MonthStart  pgtype.Date `json:"month_start"`
	MonthEnd    pgtype.Date `json:"month_end"`
	EmployeeIds []uuid.UUID `json:"employee_ids"`
}

type ListFixedPayrollContractSegmentsRow struct {
	EmployeeID           uuid.UUID                `json:"employee_id"`
	ContractID           uuid.UUID                `json:"contract_id"`
	ContractType         EmployeeContractTypeEnum `json:"contract_type"`
	ActiveFrom           pgtype.Date              `json:"active_from"`
	ActiveUntil          pgtype.Date              `json:"active_until"`
	HoursPerWeek         float64                  `json:"hours_per_week"`
	FullTimeHoursPerWeek float64                  `json:"full_time_hours_per_week"`
	MonthlySalary        float64                  `json:"monthly_salary"`
	HourlyRate           float64                  `json:"hourly_rate"`
}

func (q *Queries) ListFixedPayrollContractSegments(ctx context.Context, arg ListFixedPayrollContractSegmentsParams) ([]ListFixedPayrollContractSegmentsRow, error) {
	rows, err := q.db.Query(ctx, listFixedPayrollContractSegments, arg.MonthStart, arg.MonthEnd, arg.EmployeeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFixedPayrollContractSegmentsRow{}
	for rows.Next() {
		var i ListFixedPayrollContractSegmentsRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.ContractID,
			&i.ContractType,
			&i.ActiveFrom,
			&i.ActiveUntil,
			&i.HoursPerWeek,
			&i.FullTimeHoursPerWeek,
			&i.MonthlySalary,
			&i.HourlyRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFixedPayrollMonthEmployeesPaginated = `-- name: ListFixedPayrollMonthEmployeesPaginated :many
WITH fixed_month_employees AS (
    SELECT DISTINCT c.employee_id
    FROM employee_contracts c
    JOIN employee_salary_assignments esa ON esa.employee_id = c.employee_id
      AND (esa.contract_id IS NULL OR esa.contract_id = c.id)
    WHERE c.contract_type IN ('permanent'::employee_contract_type_enum, 'temporary'::employee_contract_type_enum)
      AND c.start_date <= $4
      AND (c.effective_end_date IS NULL OR c.effective_end_date >= $5)
      AND (c.contract_end_date IS NULL OR c.contract_end_date >= $5)
      AND esa.effective_from <= LEAST(
          $4::date,
          COALESCE(c.effective_end_date, $4::date),
          COALESCE(c.contract_end_date, $4::date)
      )
      AND (esa.effective_to IS NULL OR esa.effective_to > GREATEST($5::date, c.start_date))
)
SELECT
    ep.id AS employee_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    COUNT(*) OVER() AS total_count
FROM fixed_month_employees fme
JOIN employee_profile ep ON ep.id = fme.employee_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR ep.first_name ILIKE '%' || $1::text || '%'
    OR ep.last_name ILIKE '%' || $1::text || '%'
    OR (ep.first_name || ' ' || ep.last_name) ILIKE '%' || $1::text || '%'
    OR (ep.last_name || ' ' || ep.first_name) ILIKE '%' || $1::text || '%'
)
ORDER BY ep.first_name ASC, ep.last_name ASC, ep.id ASC
LIMIT $3 OFFSET $2
`

type ListFixedPayrollMonthEmployeesPaginatedParams struct {
	EmployeeSearch *string     `json:"employee_search"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
	MonthEnd       pgtype.Date `json:"month_end"`
	MonthStart     pgtype.Date `json:"month_start"`
}

type ListFixedPayrollMonthEmployeesPaginatedRow struct {
	EmployeeID        uuid.UUID `json:"employee_id"`
	EmployeeFirstName string    `json:"employee_first_name"`
	EmployeeLastName  string    `json:"employee_last_name"`
	TotalCount        int64     `json:"total_count"`
}

func (q *Queries) ListFixedPayrollMonthEmployeesPaginated(ctx context.Context, arg ListFixedPayrollMonthEmployeesPaginatedParams) ([]ListFixedPayrollMonthEmployeesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listFixedPayrollMonthEmployeesPaginated,
		arg.EmployeeSearch,
		arg.Offset,
		arg.Limit,
		arg.MonthEnd,
		arg.MonthStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFixedPayrollMonthEmployeesPaginatedRow{}
	for rows.Next() {
		var i ListFixedPayrollMonthEmployeesPaginatedRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLockedPayPeriodMultiplierSummaries = `-- name: ListLockedPayPeriodMultiplierSummaries :many
SELECT
    ppl.pay_period_id,
    ppl.applied_rate_percent,
    COALESCE(SUM(CASE WHEN ppl.line_type = 'leave_payout' THEN 0 ELSE ppl.minutes_worked END), 0)::double precision AS worked_minutes,
    COALESCE(SUM(ppl.minutes_worked), 0)::double precision AS paid_minutes,
    COALESCE(SUM(ppl.base_amount), 0)::double precision AS base_amount,
    COALESCE(SUM(ppl.premium_amount), 0)::double precision AS premium_amount
FROM pay_period_line_items ppl
WHERE ppl.pay_period_id = ANY($1::uuid[])
GROUP BY ppl.pay_period_id, ppl.applied_rate_percent
ORDER BY ppl.pay_period_id ASC, ppl.applied_rate_percent ASC
`

type ListLockedPayPeriodMultiplierSummariesRow struct {
	PayPeriodID        uuid.UUID `json:"pay_period_id"`
	AppliedRatePercent float64   `json:"applied_rate_percent"`
	WorkedMinutes      float64   `json:"worked_minutes"`
	PaidMinutes        float64   `json:"paid_minutes"`
	BaseAmount         float64   `json:"base_amount"`
	PremiumAmount      float64   `json:"premium_amount"`
}

func (q *Queries) ListLockedPayPeriodMultiplierSummaries(ctx context.Context, payPeriodIds []uuid.UUID) ([]ListLockedPayPeriodMultiplierSummariesRow, error) {
	rows, err := q.db.Query(ctx, listLockedPayPeriodMultiplierSummaries, payPeriodIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLockedPayPeriodMultiplierSummariesRow{}
	for rows.Next() {
		var i ListLockedPayPeriodMultiplierSummariesRow
		if err := rows.Scan(
			&i.PayPeriodID,
			&i.AppliedRatePercent,
			&i.WorkedMinutes,
			&i.PaidMinutes,
			&i.BaseAmount,
			&i.PremiumAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnCallPayrollMonthEmployeesPaginated = `-- name: ListOnCallPayrollMonthEmployeesPaginated :many
WITH on_call_month_employees AS (
    SELECT DISTINCT pp.employee_id
    FROM pay_periods pp
    JOIN pay_period_line_items ppl ON ppl.pay_period_id = pp.id
    WHERE pp.period_start = $4
      AND pp.period_end = $5
      AND ppl.contract_type = 'on_call'::employee_contract_type_enum

    UNION

    SELECT DISTINCT s.employee_id
    FROM schedules s
    JOIN LATERAL (
        SELECT c.id, c.contract_type
        FROM employee_contracts c
        WHERE c.employee_id = s.employee_id
          AND c.start_date <= DATE(s.start_datetime)
          AND (c.effective_end_date IS NULL OR c.effective_end_date >= DATE(s.start_datetime))
          AND (c.contract_end_date IS NULL OR c.contract_end_date >= DATE(s.start_datetime))
        ORDER BY c.start_date DESC, c.created_at DESC
        LIMIT 1
    ) cc ON TRUE
    WHERE DATE(s.start_datetime) >= $4
      AND DATE(s.start_datetime) <= $5
      AND cc.contract_type = 'on_call'::employee_contract_type_enum
      AND EXISTS (
          SELECT 1
          FROM employee_salary_assignments esa
          WHERE esa.employee_id = s.employee_id
            AND (esa.contract_id IS NULL OR esa.contract_id = cc.id)
            AND esa.effective_from <= DATE(s.start_datetime)
            AND (esa.effective_to IS NULL OR esa.effective_to > DATE(s.start_datetime))
      )

    UNION

    SELECT DISTINCT oe.employee_id
    FROM overtime_entries oe
    JOIN LATERAL (
        SELECT c.id, c.contract_type
        FROM employee_contracts c
        WHERE c.employee_id = oe.employee_id
          AND c.start_date <= oe.entry_date
          AND (c.effective_end_date IS NULL OR c.effective_end_date >= oe.entry_date)
          AND (c.contract_end_date IS NULL OR c.contract_end_date >= oe.entry_date)
        ORDER BY c.start_date DESC, c.created_at DESC
        LIMIT 1
    ) cc ON TRUE
    WHERE oe.entry_date >= $4
      AND oe.entry_date <= $5
      AND oe.status IN ('approved'::overtime_status_enum, 'submitted'::overtime_status_enum)
      AND cc.contract_type = 'on_call'::employee_contract_type_enum
      AND (
          oe.status = 'submitted'::overtime_status_enum
          OR EXISTS (
              SELECT 1
              FROM employee_salary_assignments esa
              WHERE esa.employee_id = oe.employee_id
                AND (esa.contract_id IS NULL OR esa.contract_id = cc.id)
                AND esa.effective_from <= oe.entry_date
                AND (esa.effective_to IS NULL OR esa.effective_to > oe.entry_date)
          )
      )

    UNION

    SELECT DISTINCT lpr.employee_id
    FROM leave_payout_requests lpr
    JOIN LATERAL (
        SELECT c.contract_type
        FROM employee_contracts c
        WHERE c.employee_id = lpr.employee_id
          AND c.start_date <= lpr.salary_month
          AND (c.effective_end_date IS NULL OR c.effective_end_date >= lpr.salary_month)
          AND (c.contract_end_date IS NULL OR c.contract_end_date >= lpr.salary_month)
        ORDER BY c.start_date DESC, c.created_at DESC
        LIMIT 1
    ) cc ON TRUE
    WHERE lpr.salary_month >= $4
      AND lpr.salary_month <= $5
      AND lpr.status = 'approved'::payout_request_status_enum
      AND lpr.paid_period_id IS NULL
      AND cc.contract_type = 'on_call'::employee_contract_type_enum
)
SELECT
    ep.id AS employee_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    COUNT(*) OVER() AS total_count
FROM on_call_month_employees ocme
JOIN employee_profile ep ON ep.id = ocme.employee_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR ep.first_name ILIKE '%' || $1::text || '%'
    OR ep.last_name ILIKE '%' || $1::text || '%'
    OR (ep.first_name || ' ' || ep.last_name) ILIKE '%' || $1::text || '%'
    OR (ep.last_name || ' ' || ep.first_name) ILIKE '%' || $1::text || '%'
)
ORDER BY ep.first_name ASC, ep.last_name ASC, ep.id ASC
LIMIT $3 OFFSET $2
`

type ListOnCallPayrollMonthEmployeesPaginatedParams struct {
	EmployeeSearch *string     `json:"employee_search"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
	MonthStart     pgtype.Date `json:"month_start"`
	MonthEnd       pgtype.Date `json:"month_end"`
}

type ListOnCallPayrollMonthEmployeesPaginatedRow struct {
	EmployeeID        uuid.UUID `json:"employee_id"`
	EmployeeFirstName string    `json:"employee_first_name"`
	EmployeeLastName  string    `json:"employee_last_name"`
	TotalCount        int64     `json:"total_count"`
}

func (q *Queries) ListOnCallPayrollMonthEmployeesPaginated(ctx context.Context, arg ListOnCallPayrollMonthEmployeesPaginatedParams) ([]ListOnCallPayrollMonthEmployeesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listOnCallPayrollMonthEmployeesPaginated,
		arg.EmployeeSearch,
		arg.Offset,
		arg.Limit,
		arg.MonthStart,
		arg.MonthEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOnCallPayrollMonthEmployeesPaginatedRow{}
	for rows.Next() {
		var i ListOnCallPayrollMonthEmployeesPaginatedRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayPeriodsByEmployeeIDsAndRange = `-- name: ListPayPeriodsByEmployeeIDsAndRange :many
SELECT
    pp.id,
    pp.employee_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    pp.period_start,
    pp.period_end,
    pp.payroll_group,
    pp.cutoff_at,
    pp.status,
    pp.base_gross_amount,
    pp.irregular_gross_amount,
    pp.gross_amount,
    pp.paid_at,
    pp.created_by_employee_id,
    pp.created_at,
    pp.updated_at
FROM pay_periods pp
JOIN employee_profile ep ON ep.id = pp.employee_id
WHERE pp.employee_id = ANY($1::uuid[])
  AND pp.period_start = $2
  AND pp.period_end = $3
ORDER BY pp.employee_id ASC, pp.created_at DESC
`

type ListPayPeriodsByEmployeeIDsAndRangeParams struct {
	EmployeeIds []uuid.UUID `json:"employee_ids"`
	MonthStart  pgtype.Date `json:"month_start"`
	MonthEnd    pgtype.Date `json:"month_end"`
}

type ListPayPeriodsByEmployeeIDsAndRangeRow struct {
	ID                   uuid.UUID           `json:"id"`
	EmployeeID           uuid.UUID           `json:"employee_id"`
	EmployeeFirstName    string              `json:"employee_first_name"`
	EmployeeLastName     string              `json:"employee_last_name"`
	PeriodStart          pgtype.Date         `json:"period_start"`
	PeriodEnd            pgtype.Date         `json:"period_end"`
	PayrollGroup         string              `json:"payroll_group"`
	CutoffAt             pgtype.Timestamptz  `json:"cutoff_at"`
	Status               PayPeriodStatusEnum `json:"status"`
	BaseGrossAmount      float64             `json:"base_gross_amount"`
	IrregularGrossAmount float64             `json:"irregular_gross_amount"`
	GrossAmount          float64             `json:"gross_amount"`
	PaidAt               pgtype.Timestamptz  `json:"paid_at"`
	CreatedByEmployeeID  *uuid.UUID          `json:"created_by_employee_id"`
	CreatedAt            pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz  `json:"updated_at"`
}

func (q *Queries) ListPayPeriodsByEmployeeIDsAndRange(ctx context.Context, arg ListPayPeriodsByEmployeeIDsAndRangeParams) ([]ListPayPeriodsByEmployeeIDsAndRangeRow, error) {
	rows, err := q.db.Query(ctx, listPayPeriodsByEmployeeIDsAndRange, arg.EmployeeIds, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayPeriodsByEmployeeIDsAndRangeRow{}
	for rows.Next() {
		var i ListPayPeriodsByEmployeeIDsAndRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PayrollGroup,
			&i.CutoffAt,
			&i.Status,
			&i.BaseGrossAmount,
			&i.IrregularGrossAmount,
			&i.GrossAmount,
			&i.PaidAt,
			&i.CreatedByEmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthApprovedWorkItems = `-- name: ListPayrollMonthApprovedWorkItems :many
WITH schedule_items AS (
    SELECT
        s.id AS source_id,
        s.employee_id,
        ep.first_name AS employee_first_name,
        ep.last_name AS employee_last_name,
        COALESCE(NULLIF(btrim(s.shift_name_snapshot), ''), 'Scheduled shift') AS label,
        DATE(s.start_datetime) AS work_date,
        s.start_datetime::time AS start_time_val,
        s.end_datetime::time AS end_time_val,
        0 AS break_minutes,
        EXTRACT(EPOCH FROM (s.end_datetime - s.start_datetime)) / 60 AS minutes_worked,
        'schedule'::text AS source_type,
        s.id AS schedule_id,
        NULL::uuid AS overtime_entry_id,
        NULL::uuid AS leave_payout_request_id,
        cc.contract_type,
        css.hourly_rate::double precision AS contract_rate,
        NULL::double precision AS gross_amount_override,
        'none'::text AS irregular_hours_profile
    FROM schedules s
    JOIN employee_profile ep ON ep.id = s.employee_id
    JOIN LATERAL (
        SELECT c.id, c.contract_type
        FROM employee_contracts c
        WHERE c.employee_id = s.employee_id
          AND c.start_date <= DATE(s.start_datetime)
          AND (c.effective_end_date IS NULL OR c.effective_end_date >= DATE(s.start_datetime))
          AND (c.contract_end_date IS NULL OR c.contract_end_date >= DATE(s.start_datetime))
        ORDER BY c.start_date DESC, c.created_at DESC
        LIMIT 1
    ) cc ON TRUE
    JOIN LATERAL (
        SELECT esa.salary_scale_step_id
        FROM employee_salary_assignments esa
        WHERE esa.employee_id = s.employee_id
          AND (esa.contract_id IS NULL OR esa.contract_id = cc.id)
          AND esa.effective_from <= DATE(s.start_datetime)
          AND (esa.effective_to IS NULL OR esa.effective_to > DATE(s.start_datetime))
        ORDER BY
          (esa.contract_id = cc.id) DESC,
          esa.effective_from DESC,
          esa.created_at DESC
        LIMIT 1
    ) latest_salary ON TRUE
    JOIN cao_salary_scale_steps css ON css.id = latest_salary.salary_scale_step_id
    WHERE s.employee_id = ANY($1::uuid[])
      AND DATE(s.start_datetime) >= $2
      AND DATE(s.start_datetime) <= $3
),
overtime_items AS (
    SELECT
        oe.id AS source_id,
        oe.employee_id,
        ep.first_name AS employee_first_name,
        ep.last_name AS employee_last_name,
        COALESCE(NULLIF(btrim(oe.reason::text), ''), 'Overtime') AS label,
        oe.entry_date AS work_date,
        NULL::time AS start_time_val,
        NULL::time AS end_time_val,
        0 AS break_minutes,
        oe.minutes::double precision AS minutes_worked,
        'overtime'::text AS source_type,
        NULL::uuid AS schedule_id,
        oe.id AS overtime_entry_id,
        NULL::uuid AS leave_payout_request_id,
        cc.contract_type,
        css.hourly_rate::double precision AS contract_rate,
        NULL::double precision AS gross_amount_override,
        'none'::text AS irregular_hours_profile
    FROM overtime_entries oe
    JOIN employee_profile ep ON ep.id = oe.employee_id
    JOIN LATERAL (
        SELECT c.id, c.contract_type
        FROM employee_contracts c
        WHERE c.employee_id = oe.employee_id
          AND c.start_date <= oe.entry_date
          AND (c.effective_end_date IS NULL OR c.effective_end_date >= oe.entry_date)
          AND (c.contract_end_date IS NULL OR c.contract_end_date >= oe.entry_date)
        ORDER BY c.start_date DESC, c.created_at DESC
        LIMIT 1
    ) cc ON TRUE
    JOIN LATERAL (
        SELECT esa.salary_scale_step_id
        FROM employee_salary_assignments esa
        WHERE esa.employee_id = oe.employee_id
          AND (esa.contract_id IS NULL OR esa.contract_id = cc.id)
          AND esa.effective_from <= oe.entry_date
          AND (esa.effective_to IS NULL OR esa.effective_to > oe.entry_date)
        ORDER BY
          (esa.contract_id = cc.id) DESC,
          esa.effective_from DESC,
          esa.created_at DESC
        LIMIT 1
    ) latest_salary ON TRUE
    JOIN cao_salary_scale_steps css ON css.id = latest_salary.salary_scale_step_id
    WHERE oe.employee_id = ANY($1::uuid[])
      AND oe.status = 'approved'::overtime_status_enum
      AND oe.entry_date >= $2
      AND oe.entry_date <= $3
),
leave_payout_items AS (
    SELECT
        lpr.id AS source_id,
        lpr.employee_id,
        ep.first_name AS employee_first_name,
        ep.last_name AS employee_last_name,
        'Leave payout'::text AS label,
        lpr.salary_month AS work_date,
        NULL::time AS start_time_val,
        NULL::time AS end_time_val,
        0 AS break_minutes,
        (lpr.requested_hours * 60)::double precision AS minutes_worked,
        'leave_payout'::text AS source_type,
        NULL::uuid AS schedule_id,
        NULL::uuid AS overtime_entry_id,
        lpr.id AS leave_payout_request_id,
        cc.contract_type,
        lpr.hourly_rate::double precision AS contract_rate,
        lpr.gross_amount::double precision AS gross_amount_override,
        'none'::text AS irregular_hours_profile
    FROM leave_payout_requests lpr
    JOIN employee_profile ep ON ep.id = lpr.employee_id
    JOIN LATERAL (
        SELECT c.contract_type
        FROM employee_contracts c
        WHERE c.employee_id = lpr.employee_id
          AND c.start_date <= lpr.salary_month
          AND (c.effective_end_date IS NULL OR c.effective_end_date >= lpr.salary_month)
          AND (c.contract_end_date IS NULL OR c.contract_end_date >= lpr.salary_month)
        ORDER BY c.start_date DESC, c.created_at DESC
        LIMIT 1
    ) cc ON TRUE
    WHERE lpr.employee_id = ANY($1::uuid[])
      AND lpr.status = 'approved'::payout_request_status_enum
      AND lpr.paid_period_id IS NULL
      AND lpr.salary_month >= $2
      AND lpr.salary_month <= $3
)
SELECT source_id, employee_id, employee_first_name, employee_last_name, label, work_date, start_time_val, end_time_val, break_minutes, minutes_worked, source_type, schedule_id, overtime_entry_id, leave_payout_request_id, contract_type, contract_rate, gross_amount_override, irregular_hours_profile FROM schedule_items
UNION ALL
SELECT source_id, employee_id, employee_first_name, employee_last_name, label, work_date, start_time_val, end_time_val, break_minutes, minutes_worked, source_type, schedule_id, overtime_entry_id, leave_payout_request_id, contract_type, contract_rate, gross_amount_override, irregular_hours_profile FROM overtime_items
UNION ALL
SELECT source_id, employee_id, employee_first_name, employee_last_name, label, work_date, start_time_val, end_time_val, break_minutes, minutes_worked, source_type, schedule_id, overtime_entry_id, leave_payout_request_id, contract_type, contract_rate, gross_amount_override, irregular_hours_profile FROM leave_payout_items
ORDER BY employee_id ASC, work_date ASC, source_type ASC, source_id ASC
`

type ListPayrollMonthApprovedWorkItemsParams struct {
	EmployeeIds []uuid.UUID        `json:"employee_ids"`
	MonthStart  pgtype.Timestamptz `json:"month_start"`
	MonthEnd    pgtype.Timestamptz `json:"month_end"`
}

type ListPayrollMonthApprovedWorkItemsRow struct {
	SourceID              uuid.UUID                `json:"source_id"`
	EmployeeID            uuid.UUID                `json:"employee_id"`
	EmployeeFirstName     string                   `json:"employee_first_name"`
	EmployeeLastName      string                   `json:"employee_last_name"`
	Label                 interface{}              `json:"label"`
	WorkDate              pgtype.Date              `json:"work_date"`
	StartTimeVal          pgtype.Time              `json:"start_time_val"`
	EndTimeVal            pgtype.Time              `json:"end_time_val"`
	BreakMinutes          int32                    `json:"break_minutes"`
	MinutesWorked         int32                    `json:"minutes_worked"`
	SourceType            string                   `json:"source_type"`
	ScheduleID            uuid.UUID                `json:"schedule_id"`
	OvertimeEntryID       *uuid.UUID               `json:"overtime_entry_id"`
	LeavePayoutRequestID  *uuid.UUID               `json:"leave_payout_request_id"`
	ContractType          EmployeeContractTypeEnum `json:"contract_type"`
	ContractRate          float64                  `json:"contract_rate"`
	GrossAmountOverride   *float64                 `json:"gross_amount_override"`
	IrregularHoursProfile string                   `json:"irregular_hours_profile"`
}

func (q *Queries) ListPayrollMonthApprovedWorkItems(ctx context.Context, arg ListPayrollMonthApprovedWorkItemsParams) ([]ListPayrollMonthApprovedWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthApprovedWorkItems, arg.EmployeeIds, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthApprovedWorkItemsRow{}
	for rows.Next() {
		var i ListPayrollMonthApprovedWorkItemsRow
		if err := rows.Scan(
			&i.SourceID,
			&i.EmployeeID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.Label,
			&i.WorkDate,
			&i.StartTimeVal,
			&i.EndTimeVal,
			&i.BreakMinutes,
			&i.MinutesWorked,
			&i.SourceType,
			&i.ScheduleID,
			&i.OvertimeEntryID,
			&i.LeavePayoutRequestID,
			&i.ContractType,
			&i.ContractRate,
			&i.GrossAmountOverride,
			&i.IrregularHoursProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthEmployeesAll = `-- name: ListPayrollMonthEmployeesAll :many
WITH month_employees AS (
    SELECT DISTINCT pp.employee_id
    FROM pay_periods pp
    WHERE pp.period_start = $2
      AND pp.period_end = $3

    UNION

    SELECT DISTINCT s.employee_id
    FROM schedules s
    WHERE DATE(s.start_datetime) >= $2
      AND DATE(s.start_datetime) <= $3

    UNION

    SELECT DISTINCT oe.employee_id
    FROM overtime_entries oe
    WHERE oe.entry_date >= $2
      AND oe.entry_date <= $3
      AND oe.status IN ('approved'::overtime_status_enum, 'submitted'::overtime_status_enum)

    UNION

    SELECT DISTINCT lpr.employee_id
    FROM leave_payout_requests lpr
    WHERE lpr.salary_month >= $2
      AND lpr.salary_month <= $3
      AND lpr.status = 'approved'::payout_request_status_enum
      AND lpr.paid_period_id IS NULL
)
SELECT
    ep.id AS employee_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name
FROM month_employees me
JOIN employee_profile ep ON ep.id = me.employee_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR ep.first_name ILIKE '%' || $1::text || '%'
    OR ep.last_name ILIKE '%' || $1::text || '%'
    OR (ep.first_name || ' ' || ep.last_name) ILIKE '%' || $1::text || '%'
    OR (ep.last_name || ' ' || ep.first_name) ILIKE '%' || $1::text || '%'
)
ORDER BY ep.first_name ASC, ep.last_name ASC, ep.id ASC
`

type ListPayrollMonthEmployeesAllParams struct {
	EmployeeSearch *string     `json:"employee_search"`
	MonthStart     pgtype.Date `json:"month_start"`
	MonthEnd       pgtype.Date `json:"month_end"`
}

type ListPayrollMonthEmployeesAllRow struct {
	EmployeeID        uuid.UUID `json:"employee_id"`
	EmployeeFirstName string    `json:"employee_first_name"`
	EmployeeLastName  string    `json:"employee_last_name"`
}

func (q *Queries) ListPayrollMonthEmployeesAll(ctx context.Context, arg ListPayrollMonthEmployeesAllParams) ([]ListPayrollMonthEmployeesAllRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthEmployeesAll, arg.EmployeeSearch, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthEmployeesAllRow{}
	for rows.Next() {
		var i ListPayrollMonthEmployeesAllRow
		if err := rows.Scan(&i.EmployeeID, &i.EmployeeFirstName, &i.EmployeeLastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthEmployeesPaginated = `-- name: ListPayrollMonthEmployeesPaginated :many
WITH month_employees AS (
    SELECT DISTINCT pp.employee_id
    FROM pay_periods pp
    WHERE pp.period_start = $4
      AND pp.period_end = $5

    UNION

    SELECT DISTINCT s.employee_id
    FROM schedules s
    WHERE DATE(s.start_datetime) >= $4
      AND DATE(s.start_datetime) <= $5

    UNION

    SELECT DISTINCT oe.employee_id
    FROM overtime_entries oe
    WHERE oe.entry_date >= $4
      AND oe.entry_date <= $5
      AND oe.status IN ('approved'::overtime_status_enum, 'submitted'::overtime_status_enum)

    UNION

    SELECT DISTINCT lpr.employee_id
    FROM leave_payout_requests lpr
    WHERE lpr.salary_month >= $4
      AND lpr.salary_month <= $5
      AND lpr.status = 'approved'::payout_request_status_enum
      AND lpr.paid_period_id IS NULL
)
SELECT
    ep.id AS employee_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    COUNT(*) OVER() AS total_count
FROM month_employees me
JOIN employee_profile ep ON ep.id = me.employee_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR ep.first_name ILIKE '%' || $1::text || '%'
    OR ep.last_name ILIKE '%' || $1::text || '%'
    OR (ep.first_name || ' ' || ep.last_name) ILIKE '%' || $1::text || '%'
    OR (ep.last_name || ' ' || ep.first_name) ILIKE '%' || $1::text || '%'
)
ORDER BY ep.first_name ASC, ep.last_name ASC, ep.id ASC
LIMIT $3 OFFSET $2
`

type ListPayrollMonthEmployeesPaginatedParams struct {
	EmployeeSearch *string     `json:"employee_search"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
	MonthStart     pgtype.Date `json:"month_start"`
	MonthEnd       pgtype.Date `json:"month_end"`
}

type ListPayrollMonthEmployeesPaginatedRow struct {
	EmployeeID        uuid.UUID `json:"employee_id"`
	EmployeeFirstName string    `json:"employee_first_name"`
	EmployeeLastName  string    `json:"employee_last_name"`
	TotalCount        int64     `json:"total_count"`
}

func (q *Queries) ListPayrollMonthEmployeesPaginated(ctx context.Context, arg ListPayrollMonthEmployeesPaginatedParams) ([]ListPayrollMonthEmployeesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthEmployeesPaginated,
		arg.EmployeeSearch,
		arg.Offset,
		arg.Limit,
		arg.MonthStart,
		arg.MonthEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthEmployeesPaginatedRow{}
	for rows.Next() {
		var i ListPayrollMonthEmployeesPaginatedRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthPendingOvertimeEntries = `-- name: ListPayrollMonthPendingOvertimeEntries :many
SELECT
    oe.employee_id,
    oe.minutes AS worked_minutes,
    cc.contract_type
FROM overtime_entries oe
JOIN employee_profile ep ON ep.id = oe.employee_id
LEFT JOIN LATERAL (
    SELECT c.contract_type
    FROM employee_contracts c
    WHERE c.employee_id = oe.employee_id
      AND c.start_date <= oe.entry_date
      AND (c.contract_end_date IS NULL OR c.contract_end_date >= oe.entry_date)
    ORDER BY c.start_date DESC, c.created_at DESC
    LIMIT 1
) cc ON TRUE
WHERE oe.employee_id = ANY($1::uuid[])
  AND oe.status = 'submitted'::overtime_status_enum
  AND oe.entry_date >= $2
  AND oe.entry_date <= $3
ORDER BY oe.employee_id ASC, oe.entry_date ASC, oe.created_at ASC
`

type ListPayrollMonthPendingOvertimeEntriesParams struct {
	EmployeeIds []uuid.UUID `json:"employee_ids"`
	MonthStart  pgtype.Date `json:"month_start"`
	MonthEnd    pgtype.Date `json:"month_end"`
}

type ListPayrollMonthPendingOvertimeEntriesRow struct {
	EmployeeID    uuid.UUID                `json:"employee_id"`
	WorkedMinutes int32                    `json:"worked_minutes"`
	ContractType  EmployeeContractTypeEnum `json:"contract_type"`
}

func (q *Queries) ListPayrollMonthPendingOvertimeEntries(ctx context.Context, arg ListPayrollMonthPendingOvertimeEntriesParams) ([]ListPayrollMonthPendingOvertimeEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthPendingOvertimeEntries, arg.EmployeeIds, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthPendingOvertimeEntriesRow{}
	for rows.Next() {
		var i ListPayrollMonthPendingOvertimeEntriesRow
		if err := rows.Scan(&i.EmployeeID, &i.WorkedMinutes, &i.ContractType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthPendingOvertimeSummaries = `-- name: ListPayrollMonthPendingOvertimeSummaries :many
SELECT
    oe.employee_id,
    COUNT(*)::INT AS pending_entry_count,
    COALESCE(SUM(oe.minutes), 0)::INT AS pending_worked_minutes
FROM overtime_entries oe
WHERE oe.employee_id = ANY($1::uuid[])
  AND oe.status = 'submitted'::overtime_status_enum
  AND oe.entry_date >= $2
  AND oe.entry_date <= $3
GROUP BY oe.employee_id
ORDER BY oe.employee_id ASC
`

type ListPayrollMonthPendingOvertimeSummariesParams struct {
	EmployeeIds []uuid.UUID `json:"employee_ids"`
	MonthStart  pgtype.Date `json:"month_start"`
	MonthEnd    pgtype.Date `json:"month_end"`
}

type ListPayrollMonthPendingOvertimeSummariesRow struct {
	EmployeeID           uuid.UUID `json:"employee_id"`
	PendingEntryCount    int32     `json:"pending_entry_count"`
	PendingWorkedMinutes int32     `json:"pending_worked_minutes"`
}

func (q *Queries) ListPayrollMonthPendingOvertimeSummaries(ctx context.Context, arg ListPayrollMonthPendingOvertimeSummariesParams) ([]ListPayrollMonthPendingOvertimeSummariesRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthPendingOvertimeSummaries, arg.EmployeeIds, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthPendingOvertimeSummariesRow{}
	for rows.Next() {
		var i ListPayrollMonthPendingOvertimeSummariesRow
		if err := rows.Scan(&i.EmployeeID, &i.PendingEntryCount, &i.PendingWorkedMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
