// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payroll_month_summary.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listLockedPayPeriodMultiplierSummaries = `-- name: ListLockedPayPeriodMultiplierSummaries :many
SELECT
    ppl.pay_period_id,
    ppl.applied_rate_percent,
    COALESCE(SUM(ppl.minutes_worked), 0)::double precision AS worked_minutes,
    COALESCE(SUM(ppl.minutes_worked), 0)::double precision AS paid_minutes,
    COALESCE(SUM(ppl.base_amount), 0)::double precision AS base_amount,
    COALESCE(SUM(ppl.premium_amount), 0)::double precision AS premium_amount
FROM pay_period_line_items ppl
WHERE ppl.pay_period_id = ANY($1::uuid[])
GROUP BY ppl.pay_period_id, ppl.applied_rate_percent
ORDER BY ppl.pay_period_id ASC, ppl.applied_rate_percent ASC
`

type ListLockedPayPeriodMultiplierSummariesRow struct {
	PayPeriodID        uuid.UUID `json:"pay_period_id"`
	AppliedRatePercent float64   `json:"applied_rate_percent"`
	WorkedMinutes      float64   `json:"worked_minutes"`
	PaidMinutes        float64   `json:"paid_minutes"`
	BaseAmount         float64   `json:"base_amount"`
	PremiumAmount      float64   `json:"premium_amount"`
}

func (q *Queries) ListLockedPayPeriodMultiplierSummaries(ctx context.Context, payPeriodIds []uuid.UUID) ([]ListLockedPayPeriodMultiplierSummariesRow, error) {
	rows, err := q.db.Query(ctx, listLockedPayPeriodMultiplierSummaries, payPeriodIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLockedPayPeriodMultiplierSummariesRow{}
	for rows.Next() {
		var i ListLockedPayPeriodMultiplierSummariesRow
		if err := rows.Scan(
			&i.PayPeriodID,
			&i.AppliedRatePercent,
			&i.WorkedMinutes,
			&i.PaidMinutes,
			&i.BaseAmount,
			&i.PremiumAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayPeriodsByEmployeeIDsAndRange = `-- name: ListPayPeriodsByEmployeeIDsAndRange :many
SELECT
    pp.id,
    pp.employee_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    pp.period_start,
    pp.period_end,
    pp.status,
    pp.base_gross_amount,
    pp.irregular_gross_amount,
    pp.gross_amount,
    pp.paid_at,
    pp.created_by_employee_id,
    pp.created_at,
    pp.updated_at
FROM pay_periods pp
JOIN employee_profile ep ON ep.id = pp.employee_id
WHERE pp.employee_id = ANY($1::uuid[])
  AND pp.period_start = $2
  AND pp.period_end = $3
ORDER BY pp.employee_id ASC, pp.created_at DESC
`

type ListPayPeriodsByEmployeeIDsAndRangeParams struct {
	EmployeeIds []uuid.UUID `json:"employee_ids"`
	MonthStart  pgtype.Date `json:"month_start"`
	MonthEnd    pgtype.Date `json:"month_end"`
}

type ListPayPeriodsByEmployeeIDsAndRangeRow struct {
	ID                   uuid.UUID           `json:"id"`
	EmployeeID           uuid.UUID           `json:"employee_id"`
	EmployeeFirstName    string              `json:"employee_first_name"`
	EmployeeLastName     string              `json:"employee_last_name"`
	PeriodStart          pgtype.Date         `json:"period_start"`
	PeriodEnd            pgtype.Date         `json:"period_end"`
	Status               PayPeriodStatusEnum `json:"status"`
	BaseGrossAmount      float64             `json:"base_gross_amount"`
	IrregularGrossAmount float64             `json:"irregular_gross_amount"`
	GrossAmount          float64             `json:"gross_amount"`
	PaidAt               pgtype.Timestamptz  `json:"paid_at"`
	CreatedByEmployeeID  *uuid.UUID          `json:"created_by_employee_id"`
	CreatedAt            pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz  `json:"updated_at"`
}

func (q *Queries) ListPayPeriodsByEmployeeIDsAndRange(ctx context.Context, arg ListPayPeriodsByEmployeeIDsAndRangeParams) ([]ListPayPeriodsByEmployeeIDsAndRangeRow, error) {
	rows, err := q.db.Query(ctx, listPayPeriodsByEmployeeIDsAndRange, arg.EmployeeIds, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayPeriodsByEmployeeIDsAndRangeRow{}
	for rows.Next() {
		var i ListPayPeriodsByEmployeeIDsAndRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.BaseGrossAmount,
			&i.IrregularGrossAmount,
			&i.GrossAmount,
			&i.PaidAt,
			&i.CreatedByEmployeeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthApprovedTimeEntriesByEmployeeIDs = `-- name: ListPayrollMonthApprovedTimeEntriesByEmployeeIDs :many
SELECT
    te.id,
    te.employee_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    te.entry_date,
    te.start_time,
    te.end_time,
    te.break_minutes,
    te.hour_type,
    COALESCE(cc.contract_type, ep.contract_type) AS contract_type,
    COALESCE(cc.contract_rate, ep.contract_rate) AS contract_rate,
    COALESCE(cc.irregular_hours_profile, ep.irregular_hours_profile) AS irregular_hours_profile
FROM time_entries te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN LATERAL (
    SELECT
        c.contract_type,
        c.contract_rate,
        c.irregular_hours_profile
    FROM employee_contract_changes c
    WHERE c.employee_id = te.employee_id
      AND c.effective_from <= te.entry_date
    ORDER BY c.effective_from DESC, c.created_at DESC
    LIMIT 1
) cc ON TRUE
WHERE te.employee_id = ANY($1::uuid[])
  AND te.status = 'approved'::time_entry_status_enum
  AND te.hour_type IN (
      'normal'::time_entry_hour_type_enum,
      'overtime'::time_entry_hour_type_enum,
      'travel'::time_entry_hour_type_enum,
      'training'::time_entry_hour_type_enum
  )
  AND te.entry_date >= $2
  AND te.entry_date <= $3
ORDER BY te.employee_id ASC, te.entry_date ASC, te.start_time ASC, te.created_at ASC
`

type ListPayrollMonthApprovedTimeEntriesByEmployeeIDsParams struct {
	EmployeeIds []uuid.UUID `json:"employee_ids"`
	MonthStart  pgtype.Date `json:"month_start"`
	MonthEnd    pgtype.Date `json:"month_end"`
}

type ListPayrollMonthApprovedTimeEntriesByEmployeeIDsRow struct {
	ID                    uuid.UUID                 `json:"id"`
	EmployeeID            uuid.UUID                 `json:"employee_id"`
	EmployeeFirstName     string                    `json:"employee_first_name"`
	EmployeeLastName      string                    `json:"employee_last_name"`
	EntryDate             pgtype.Date               `json:"entry_date"`
	StartTime             pgtype.Time               `json:"start_time"`
	EndTime               pgtype.Time               `json:"end_time"`
	BreakMinutes          int32                     `json:"break_minutes"`
	HourType              TimeEntryHourTypeEnum     `json:"hour_type"`
	ContractType          EmployeeContractTypeEnum  `json:"contract_type"`
	ContractRate          *float64                  `json:"contract_rate"`
	IrregularHoursProfile IrregularHoursProfileEnum `json:"irregular_hours_profile"`
}

func (q *Queries) ListPayrollMonthApprovedTimeEntriesByEmployeeIDs(ctx context.Context, arg ListPayrollMonthApprovedTimeEntriesByEmployeeIDsParams) ([]ListPayrollMonthApprovedTimeEntriesByEmployeeIDsRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthApprovedTimeEntriesByEmployeeIDs, arg.EmployeeIds, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthApprovedTimeEntriesByEmployeeIDsRow{}
	for rows.Next() {
		var i ListPayrollMonthApprovedTimeEntriesByEmployeeIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.EntryDate,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMinutes,
			&i.HourType,
			&i.ContractType,
			&i.ContractRate,
			&i.IrregularHoursProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthEmployeesAll = `-- name: ListPayrollMonthEmployeesAll :many
WITH month_employees AS (
    SELECT DISTINCT pp.employee_id
    FROM pay_periods pp
    WHERE pp.period_start = $2
      AND pp.period_end = $3

    UNION

    SELECT DISTINCT te.employee_id
    FROM time_entries te
    WHERE te.entry_date >= $2
      AND te.entry_date <= $3
      AND te.hour_type IN (
          'normal'::time_entry_hour_type_enum,
          'overtime'::time_entry_hour_type_enum,
          'travel'::time_entry_hour_type_enum,
          'training'::time_entry_hour_type_enum
      )
      AND te.status IN (
          'approved'::time_entry_status_enum,
          'draft'::time_entry_status_enum,
          'submitted'::time_entry_status_enum
      )
)
SELECT
    ep.id AS employee_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name
FROM month_employees me
JOIN employee_profile ep ON ep.id = me.employee_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR ep.first_name ILIKE '%' || $1::text || '%'
    OR ep.last_name ILIKE '%' || $1::text || '%'
    OR (ep.first_name || ' ' || ep.last_name) ILIKE '%' || $1::text || '%'
    OR (ep.last_name || ' ' || ep.first_name) ILIKE '%' || $1::text || '%'
)
ORDER BY ep.first_name ASC, ep.last_name ASC, ep.id ASC
`

type ListPayrollMonthEmployeesAllParams struct {
	EmployeeSearch *string     `json:"employee_search"`
	MonthStart     pgtype.Date `json:"month_start"`
	MonthEnd       pgtype.Date `json:"month_end"`
}

type ListPayrollMonthEmployeesAllRow struct {
	EmployeeID        uuid.UUID `json:"employee_id"`
	EmployeeFirstName string    `json:"employee_first_name"`
	EmployeeLastName  string    `json:"employee_last_name"`
}

func (q *Queries) ListPayrollMonthEmployeesAll(ctx context.Context, arg ListPayrollMonthEmployeesAllParams) ([]ListPayrollMonthEmployeesAllRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthEmployeesAll, arg.EmployeeSearch, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthEmployeesAllRow{}
	for rows.Next() {
		var i ListPayrollMonthEmployeesAllRow
		if err := rows.Scan(&i.EmployeeID, &i.EmployeeFirstName, &i.EmployeeLastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthEmployeesPaginated = `-- name: ListPayrollMonthEmployeesPaginated :many
WITH month_employees AS (
    SELECT DISTINCT pp.employee_id
    FROM pay_periods pp
    WHERE pp.period_start = $4
      AND pp.period_end = $5

    UNION

    SELECT DISTINCT te.employee_id
    FROM time_entries te
    WHERE te.entry_date >= $4
      AND te.entry_date <= $5
      AND te.hour_type IN (
          'normal'::time_entry_hour_type_enum,
          'overtime'::time_entry_hour_type_enum,
          'travel'::time_entry_hour_type_enum,
          'training'::time_entry_hour_type_enum
      )
      AND te.status IN (
          'approved'::time_entry_status_enum,
          'draft'::time_entry_status_enum,
          'submitted'::time_entry_status_enum
      )
)
SELECT
    ep.id AS employee_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    COUNT(*) OVER() AS total_count
FROM month_employees me
JOIN employee_profile ep ON ep.id = me.employee_id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR ep.first_name ILIKE '%' || $1::text || '%'
    OR ep.last_name ILIKE '%' || $1::text || '%'
    OR (ep.first_name || ' ' || ep.last_name) ILIKE '%' || $1::text || '%'
    OR (ep.last_name || ' ' || ep.first_name) ILIKE '%' || $1::text || '%'
)
ORDER BY ep.first_name ASC, ep.last_name ASC, ep.id ASC
LIMIT $3 OFFSET $2
`

type ListPayrollMonthEmployeesPaginatedParams struct {
	EmployeeSearch *string     `json:"employee_search"`
	Offset         int32       `json:"offset"`
	Limit          int32       `json:"limit"`
	MonthStart     pgtype.Date `json:"month_start"`
	MonthEnd       pgtype.Date `json:"month_end"`
}

type ListPayrollMonthEmployeesPaginatedRow struct {
	EmployeeID        uuid.UUID `json:"employee_id"`
	EmployeeFirstName string    `json:"employee_first_name"`
	EmployeeLastName  string    `json:"employee_last_name"`
	TotalCount        int64     `json:"total_count"`
}

func (q *Queries) ListPayrollMonthEmployeesPaginated(ctx context.Context, arg ListPayrollMonthEmployeesPaginatedParams) ([]ListPayrollMonthEmployeesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthEmployeesPaginated,
		arg.EmployeeSearch,
		arg.Offset,
		arg.Limit,
		arg.MonthStart,
		arg.MonthEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthEmployeesPaginatedRow{}
	for rows.Next() {
		var i ListPayrollMonthEmployeesPaginatedRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthPendingEntriesByEmployeeIDs = `-- name: ListPayrollMonthPendingEntriesByEmployeeIDs :many
SELECT
    te.employee_id,
    GREATEST(
        0,
        (
            CASE
                WHEN te.end_time > te.start_time THEN
                    EXTRACT(EPOCH FROM te.end_time) - EXTRACT(EPOCH FROM te.start_time)
                ELSE
                    EXTRACT(EPOCH FROM te.end_time) + 86400 - EXTRACT(EPOCH FROM te.start_time)
            END
        ) / 60 - te.break_minutes
    )::INT AS worked_minutes,
    COALESCE(cc.contract_type, ep.contract_type) AS contract_type
FROM time_entries te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN LATERAL (
    SELECT
        c.contract_type
    FROM employee_contract_changes c
    WHERE c.employee_id = te.employee_id
      AND c.effective_from <= te.entry_date
    ORDER BY c.effective_from DESC, c.created_at DESC
    LIMIT 1
) cc ON TRUE
WHERE te.employee_id = ANY($1::uuid[])
  AND te.status IN (
      'draft'::time_entry_status_enum,
      'submitted'::time_entry_status_enum
  )
  AND te.hour_type IN (
      'normal'::time_entry_hour_type_enum,
      'overtime'::time_entry_hour_type_enum,
      'travel'::time_entry_hour_type_enum,
      'training'::time_entry_hour_type_enum
  )
  AND te.entry_date >= $2
  AND te.entry_date <= $3
ORDER BY te.employee_id ASC, te.entry_date ASC, te.start_time ASC, te.created_at ASC
`

type ListPayrollMonthPendingEntriesByEmployeeIDsParams struct {
	EmployeeIds []uuid.UUID `json:"employee_ids"`
	MonthStart  pgtype.Date `json:"month_start"`
	MonthEnd    pgtype.Date `json:"month_end"`
}

type ListPayrollMonthPendingEntriesByEmployeeIDsRow struct {
	EmployeeID    uuid.UUID                `json:"employee_id"`
	WorkedMinutes int32                    `json:"worked_minutes"`
	ContractType  EmployeeContractTypeEnum `json:"contract_type"`
}

func (q *Queries) ListPayrollMonthPendingEntriesByEmployeeIDs(ctx context.Context, arg ListPayrollMonthPendingEntriesByEmployeeIDsParams) ([]ListPayrollMonthPendingEntriesByEmployeeIDsRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthPendingEntriesByEmployeeIDs, arg.EmployeeIds, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthPendingEntriesByEmployeeIDsRow{}
	for rows.Next() {
		var i ListPayrollMonthPendingEntriesByEmployeeIDsRow
		if err := rows.Scan(&i.EmployeeID, &i.WorkedMinutes, &i.ContractType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollMonthPendingSummariesByEmployeeIDs = `-- name: ListPayrollMonthPendingSummariesByEmployeeIDs :many
SELECT
    te.employee_id,
    COUNT(*)::INT AS pending_entry_count,
    COALESCE(
        SUM(
            GREATEST(
                0,
                (
                    CASE
                        WHEN te.end_time > te.start_time THEN
                            EXTRACT(EPOCH FROM te.end_time) - EXTRACT(EPOCH FROM te.start_time)
                        ELSE
                            EXTRACT(EPOCH FROM te.end_time) + 86400 - EXTRACT(EPOCH FROM te.start_time)
                    END
                ) / 60 - te.break_minutes
            )
        ),
        0
    )::INT AS pending_worked_minutes
FROM time_entries te
WHERE te.employee_id = ANY($1::uuid[])
  AND te.status IN (
      'draft'::time_entry_status_enum,
      'submitted'::time_entry_status_enum
  )
  AND te.hour_type IN (
      'normal'::time_entry_hour_type_enum,
      'overtime'::time_entry_hour_type_enum,
      'travel'::time_entry_hour_type_enum,
      'training'::time_entry_hour_type_enum
  )
  AND te.entry_date >= $2
  AND te.entry_date <= $3
GROUP BY te.employee_id
ORDER BY te.employee_id ASC
`

type ListPayrollMonthPendingSummariesByEmployeeIDsParams struct {
	EmployeeIds []uuid.UUID `json:"employee_ids"`
	MonthStart  pgtype.Date `json:"month_start"`
	MonthEnd    pgtype.Date `json:"month_end"`
}

type ListPayrollMonthPendingSummariesByEmployeeIDsRow struct {
	EmployeeID           uuid.UUID `json:"employee_id"`
	PendingEntryCount    int32     `json:"pending_entry_count"`
	PendingWorkedMinutes int32     `json:"pending_worked_minutes"`
}

func (q *Queries) ListPayrollMonthPendingSummariesByEmployeeIDs(ctx context.Context, arg ListPayrollMonthPendingSummariesByEmployeeIDsParams) ([]ListPayrollMonthPendingSummariesByEmployeeIDsRow, error) {
	rows, err := q.db.Query(ctx, listPayrollMonthPendingSummariesByEmployeeIDs, arg.EmployeeIds, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollMonthPendingSummariesByEmployeeIDsRow{}
	for rows.Next() {
		var i ListPayrollMonthPendingSummariesByEmployeeIDsRow
		if err := rows.Scan(&i.EmployeeID, &i.PendingEntryCount, &i.PendingWorkedMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
