// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payroll_preview.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listNationalHolidaysInRange = `-- name: ListNationalHolidaysInRange :many
SELECT
    holiday_date,
    name
FROM national_holidays
WHERE country_code = $1
  AND is_national = TRUE
  AND holiday_date >= $2
  AND holiday_date <= $3
ORDER BY holiday_date ASC
`

type ListNationalHolidaysInRangeParams struct {
	CountryCode string      `json:"country_code"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

type ListNationalHolidaysInRangeRow struct {
	HolidayDate pgtype.Date `json:"holiday_date"`
	Name        string      `json:"name"`
}

func (q *Queries) ListNationalHolidaysInRange(ctx context.Context, arg ListNationalHolidaysInRangeParams) ([]ListNationalHolidaysInRangeRow, error) {
	rows, err := q.db.Query(ctx, listNationalHolidaysInRange, arg.CountryCode, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNationalHolidaysInRangeRow{}
	for rows.Next() {
		var i ListNationalHolidaysInRangeRow
		if err := rows.Scan(&i.HolidayDate, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollPreviewWorkItems = `-- name: ListPayrollPreviewWorkItems :many
WITH schedule_items AS (
    SELECT
        s.id AS source_id,
        s.employee_id,
        ep.first_name AS employee_first_name,
        ep.last_name AS employee_last_name,
        COALESCE(NULLIF(btrim(s.shift_name_snapshot), ''), 'Scheduled shift') AS label,
        DATE(s.start_datetime) AS work_date,
        s.start_datetime::time AS start_time_val,
        s.end_datetime::time AS end_time_val,
        0 AS break_minutes,
        EXTRACT(EPOCH FROM (s.end_datetime - s.start_datetime)) / 60 AS minutes_worked,
        'schedule'::text AS source_type,
        s.id AS schedule_id,
        NULL::uuid AS overtime_entry_id,
        NULL::uuid AS leave_payout_request_id,
        cc.contract_type,
        css.hourly_rate::double precision AS contract_rate,
        NULL::double precision AS gross_amount_override,
        'none'::text AS irregular_hours_profile
    FROM schedules s
    JOIN employee_profile ep ON ep.id = s.employee_id
    JOIN LATERAL (
        SELECT
            c.id,
            c.contract_type,
            c.contract_end_date
        FROM employee_contracts c
        WHERE c.employee_id = s.employee_id
          AND c.start_date <= DATE(s.start_datetime)
          AND (c.effective_end_date IS NULL OR c.effective_end_date >= DATE(s.start_datetime))
          AND (c.contract_end_date IS NULL OR c.contract_end_date >= DATE(s.start_datetime))
        ORDER BY c.start_date DESC, c.created_at DESC
        LIMIT 1
    ) cc ON TRUE
    JOIN LATERAL (
        SELECT esa.salary_scale_step_id
        FROM employee_salary_assignments esa
        WHERE esa.employee_id = s.employee_id
          AND (esa.contract_id IS NULL OR esa.contract_id = cc.id)
          AND esa.effective_from <= DATE(s.start_datetime)
          AND (esa.effective_to IS NULL OR esa.effective_to > DATE(s.start_datetime))
        ORDER BY
          (esa.contract_id = cc.id) DESC,
          esa.effective_from DESC,
          esa.created_at DESC
        LIMIT 1
    ) latest_salary ON TRUE
    JOIN cao_salary_scale_steps css ON css.id = latest_salary.salary_scale_step_id
    WHERE s.employee_id = $1
      AND DATE(s.start_datetime) >= $2
      AND DATE(s.start_datetime) <= $3
),
overtime_items AS (
    SELECT
        oe.id AS source_id,
        oe.employee_id,
        ep.first_name AS employee_first_name,
        ep.last_name AS employee_last_name,
        COALESCE(NULLIF(btrim(oe.reason::text), ''), 'Overtime') AS label,
        oe.entry_date AS work_date,
        NULL::time AS start_time_val,
        NULL::time AS end_time_val,
        0 AS break_minutes,
        oe.minutes::double precision AS minutes_worked,
        'overtime'::text AS source_type,
        NULL::uuid AS schedule_id,
        oe.id AS overtime_entry_id,
        NULL::uuid AS leave_payout_request_id,
        cc.contract_type,
        css.hourly_rate::double precision AS contract_rate,
        NULL::double precision AS gross_amount_override,
        'none'::text AS irregular_hours_profile
    FROM overtime_entries oe
    JOIN employee_profile ep ON ep.id = oe.employee_id
    JOIN LATERAL (
        SELECT
            c.id,
            c.contract_type,
            c.contract_end_date
        FROM employee_contracts c
        WHERE c.employee_id = oe.employee_id
          AND c.start_date <= oe.entry_date
          AND (c.effective_end_date IS NULL OR c.effective_end_date >= oe.entry_date)
          AND (c.contract_end_date IS NULL OR c.contract_end_date >= oe.entry_date)
        ORDER BY c.start_date DESC, c.created_at DESC
        LIMIT 1
    ) cc ON TRUE
    JOIN LATERAL (
        SELECT esa.salary_scale_step_id
        FROM employee_salary_assignments esa
        WHERE esa.employee_id = oe.employee_id
          AND (esa.contract_id IS NULL OR esa.contract_id = cc.id)
          AND esa.effective_from <= oe.entry_date
          AND (esa.effective_to IS NULL OR esa.effective_to > oe.entry_date)
        ORDER BY
          (esa.contract_id = cc.id) DESC,
          esa.effective_from DESC,
          esa.created_at DESC
        LIMIT 1
    ) latest_salary ON TRUE
    JOIN cao_salary_scale_steps css ON css.id = latest_salary.salary_scale_step_id
    WHERE oe.employee_id = $1
      AND oe.status = 'approved'::overtime_status_enum
      AND oe.paid_period_id IS NULL
      AND oe.entry_date >= $2
      AND oe.entry_date <= $3
),
leave_payout_items AS (
    SELECT
        lpr.id AS source_id,
        lpr.employee_id,
        ep.first_name AS employee_first_name,
        ep.last_name AS employee_last_name,
        'Leave payout'::text AS label,
        lpr.salary_month AS work_date,
        NULL::time AS start_time_val,
        NULL::time AS end_time_val,
        0 AS break_minutes,
        (lpr.requested_hours * 60)::double precision AS minutes_worked,
        'leave_payout'::text AS source_type,
        NULL::uuid AS schedule_id,
        NULL::uuid AS overtime_entry_id,
        lpr.id AS leave_payout_request_id,
        cc.contract_type,
        lpr.hourly_rate::double precision AS contract_rate,
        lpr.gross_amount::double precision AS gross_amount_override,
        'none'::text AS irregular_hours_profile
    FROM leave_payout_requests lpr
    JOIN employee_profile ep ON ep.id = lpr.employee_id
    JOIN LATERAL (
        SELECT c.contract_type
        FROM employee_contracts c
        WHERE c.employee_id = lpr.employee_id
          AND c.start_date <= lpr.salary_month
          AND (c.effective_end_date IS NULL OR c.effective_end_date >= lpr.salary_month)
          AND (c.contract_end_date IS NULL OR c.contract_end_date >= lpr.salary_month)
        ORDER BY c.start_date DESC, c.created_at DESC
        LIMIT 1
    ) cc ON TRUE
    WHERE lpr.employee_id = $1
      AND lpr.status = 'approved'::payout_request_status_enum
      AND lpr.paid_period_id IS NULL
      AND lpr.salary_month >= $2
      AND lpr.salary_month <= $3
)
SELECT source_id, employee_id, employee_first_name, employee_last_name, label, work_date, start_time_val, end_time_val, break_minutes, minutes_worked, source_type, schedule_id, overtime_entry_id, leave_payout_request_id, contract_type, contract_rate, gross_amount_override, irregular_hours_profile FROM schedule_items
UNION ALL
SELECT source_id, employee_id, employee_first_name, employee_last_name, label, work_date, start_time_val, end_time_val, break_minutes, minutes_worked, source_type, schedule_id, overtime_entry_id, leave_payout_request_id, contract_type, contract_rate, gross_amount_override, irregular_hours_profile FROM overtime_items
UNION ALL
SELECT source_id, employee_id, employee_first_name, employee_last_name, label, work_date, start_time_val, end_time_val, break_minutes, minutes_worked, source_type, schedule_id, overtime_entry_id, leave_payout_request_id, contract_type, contract_rate, gross_amount_override, irregular_hours_profile FROM leave_payout_items
ORDER BY work_date ASC, source_type ASC, source_id ASC
`

type ListPayrollPreviewWorkItemsParams struct {
	EmployeeID  uuid.UUID          `json:"employee_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type ListPayrollPreviewWorkItemsRow struct {
	SourceID              uuid.UUID                `json:"source_id"`
	EmployeeID            uuid.UUID                `json:"employee_id"`
	EmployeeFirstName     string                   `json:"employee_first_name"`
	EmployeeLastName      string                   `json:"employee_last_name"`
	Label                 interface{}              `json:"label"`
	WorkDate              pgtype.Date              `json:"work_date"`
	StartTimeVal          pgtype.Time              `json:"start_time_val"`
	EndTimeVal            pgtype.Time              `json:"end_time_val"`
	BreakMinutes          int32                    `json:"break_minutes"`
	MinutesWorked         int32                    `json:"minutes_worked"`
	SourceType            string                   `json:"source_type"`
	ScheduleID            uuid.UUID                `json:"schedule_id"`
	OvertimeEntryID       *uuid.UUID               `json:"overtime_entry_id"`
	LeavePayoutRequestID  *uuid.UUID               `json:"leave_payout_request_id"`
	ContractType          EmployeeContractTypeEnum `json:"contract_type"`
	ContractRate          float64                  `json:"contract_rate"`
	GrossAmountOverride   *float64                 `json:"gross_amount_override"`
	IrregularHoursProfile string                   `json:"irregular_hours_profile"`
}

func (q *Queries) ListPayrollPreviewWorkItems(ctx context.Context, arg ListPayrollPreviewWorkItemsParams) ([]ListPayrollPreviewWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, listPayrollPreviewWorkItems, arg.EmployeeID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPayrollPreviewWorkItemsRow{}
	for rows.Next() {
		var i ListPayrollPreviewWorkItemsRow
		if err := rows.Scan(
			&i.SourceID,
			&i.EmployeeID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.Label,
			&i.WorkDate,
			&i.StartTimeVal,
			&i.EndTimeVal,
			&i.BreakMinutes,
			&i.MinutesWorked,
			&i.SourceType,
			&i.ScheduleID,
			&i.OvertimeEntryID,
			&i.LeavePayoutRequestID,
			&i.ContractType,
			&i.ContractRate,
			&i.GrossAmountOverride,
			&i.IrregularHoursProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
