// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: performance.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPerformanceAssessment = `-- name: CreatePerformanceAssessment :one
INSERT INTO performance_assessments (
    employee_id,
    reviewer_employee_id,
    assessment_date,
    total_score,
    status,
    notes
)
VALUES ($1, $2, $3, $4, 'completed', $5)
RETURNING id, employee_id, reviewer_employee_id, assessment_date, total_score, status, notes, created_at
`

type CreatePerformanceAssessmentParams struct {
	EmployeeID         uuid.UUID   `json:"employee_id"`
	ReviewerEmployeeID uuid.UUID   `json:"reviewer_employee_id"`
	AssessmentDate     pgtype.Date `json:"assessment_date"`
	TotalScore         *float64    `json:"total_score"`
	Notes              *string     `json:"notes"`
}

type CreatePerformanceAssessmentRow struct {
	ID                 uuid.UUID                       `json:"id"`
	EmployeeID         uuid.UUID                       `json:"employee_id"`
	ReviewerEmployeeID uuid.UUID                       `json:"reviewer_employee_id"`
	AssessmentDate     pgtype.Date                     `json:"assessment_date"`
	TotalScore         *float64                        `json:"total_score"`
	Status             PerformanceAssessmentStatusEnum `json:"status"`
	Notes              *string                         `json:"notes"`
	CreatedAt          pgtype.Timestamptz              `json:"created_at"`
}

func (q *Queries) CreatePerformanceAssessment(ctx context.Context, arg CreatePerformanceAssessmentParams) (CreatePerformanceAssessmentRow, error) {
	row := q.db.QueryRow(ctx, createPerformanceAssessment,
		arg.EmployeeID,
		arg.ReviewerEmployeeID,
		arg.AssessmentDate,
		arg.TotalScore,
		arg.Notes,
	)
	var i CreatePerformanceAssessmentRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ReviewerEmployeeID,
		&i.AssessmentDate,
		&i.TotalScore,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createPerformanceAssessmentScore = `-- name: CreatePerformanceAssessmentScore :exec
INSERT INTO performance_assessment_scores (
    assessment_id,
    question_code,
    rating,
    remarks
)
VALUES ($1, $2, $3, $4)
`

type CreatePerformanceAssessmentScoreParams struct {
	AssessmentID uuid.UUID `json:"assessment_id"`
	QuestionCode string    `json:"question_code"`
	Rating       float64   `json:"rating"`
	Remarks      *string   `json:"remarks"`
}

func (q *Queries) CreatePerformanceAssessmentScore(ctx context.Context, arg CreatePerformanceAssessmentScoreParams) error {
	_, err := q.db.Exec(ctx, createPerformanceAssessmentScore,
		arg.AssessmentID,
		arg.QuestionCode,
		arg.Rating,
		arg.Remarks,
	)
	return err
}

const deletePerformanceAssessment = `-- name: DeletePerformanceAssessment :execrows
DELETE FROM performance_assessments WHERE id = $1
`

func (q *Queries) DeletePerformanceAssessment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePerformanceAssessment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveEmployeeNameForPerformance = `-- name: GetActiveEmployeeNameForPerformance :one
SELECT first_name, last_name
FROM employee_profile
WHERE id = $1
  AND is_archived = FALSE
  AND COALESCE(out_of_service, FALSE) = FALSE
`

type GetActiveEmployeeNameForPerformanceRow struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) GetActiveEmployeeNameForPerformance(ctx context.Context, id uuid.UUID) (GetActiveEmployeeNameForPerformanceRow, error) {
	row := q.db.QueryRow(ctx, getActiveEmployeeNameForPerformance, id)
	var i GetActiveEmployeeNameForPerformanceRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}

const getActivePerformanceQuestion = `-- name: GetActivePerformanceQuestion :one
SELECT code, domain_code, title_nl, title_en, description_nl, description_en, sort_order
FROM performance_questions
WHERE code = $1
  AND is_active = TRUE
`

type GetActivePerformanceQuestionRow struct {
	Code          string `json:"code"`
	DomainCode    string `json:"domain_code"`
	TitleNl       string `json:"title_nl"`
	TitleEn       string `json:"title_en"`
	DescriptionNl string `json:"description_nl"`
	DescriptionEn string `json:"description_en"`
	SortOrder     int32  `json:"sort_order"`
}

func (q *Queries) GetActivePerformanceQuestion(ctx context.Context, code string) (GetActivePerformanceQuestionRow, error) {
	row := q.db.QueryRow(ctx, getActivePerformanceQuestion, code)
	var i GetActivePerformanceQuestionRow
	err := row.Scan(
		&i.Code,
		&i.DomainCode,
		&i.TitleNl,
		&i.TitleEn,
		&i.DescriptionNl,
		&i.DescriptionEn,
		&i.SortOrder,
	)
	return i, err
}

const getPerformanceAssessmentByID = `-- name: GetPerformanceAssessmentByID :one
SELECT
    pa.id,
    pa.employee_id,
    ep.first_name,
    ep.last_name,
    pa.reviewer_employee_id,
    rev.first_name AS reviewer_first_name,
    rev.last_name AS reviewer_last_name,
    pa.assessment_date,
    pa.total_score,
    pa.status,
    pa.notes,
    pa.created_at
FROM performance_assessments pa
JOIN employee_profile ep ON ep.id = pa.employee_id
LEFT JOIN employee_profile rev ON rev.id = pa.reviewer_employee_id
WHERE pa.id = $1
`

type GetPerformanceAssessmentByIDRow struct {
	ID                 uuid.UUID                       `json:"id"`
	EmployeeID         uuid.UUID                       `json:"employee_id"`
	FirstName          string                          `json:"first_name"`
	LastName           string                          `json:"last_name"`
	ReviewerEmployeeID uuid.UUID                       `json:"reviewer_employee_id"`
	ReviewerFirstName  *string                         `json:"reviewer_first_name"`
	ReviewerLastName   *string                         `json:"reviewer_last_name"`
	AssessmentDate     pgtype.Date                     `json:"assessment_date"`
	TotalScore         *float64                        `json:"total_score"`
	Status             PerformanceAssessmentStatusEnum `json:"status"`
	Notes              *string                         `json:"notes"`
	CreatedAt          pgtype.Timestamptz              `json:"created_at"`
}

func (q *Queries) GetPerformanceAssessmentByID(ctx context.Context, id uuid.UUID) (GetPerformanceAssessmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceAssessmentByID, id)
	var i GetPerformanceAssessmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.FirstName,
		&i.LastName,
		&i.ReviewerEmployeeID,
		&i.ReviewerFirstName,
		&i.ReviewerLastName,
		&i.AssessmentDate,
		&i.TotalScore,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getPerformanceMineReviewContext = `-- name: GetPerformanceMineReviewContext :one
SELECT
    ep.id,
    ep.first_name,
    ep.last_name,
    ep.contract_start_date,
    (
        SELECT MAX(pa.assessment_date)::date
        FROM performance_assessments pa
        WHERE pa.employee_id = ep.id
          AND pa.status = 'completed'
    ) AS last_assessment_date
FROM employee_profile ep
WHERE ep.id = $1
  AND ep.is_archived = FALSE
  AND COALESCE(ep.out_of_service, FALSE) = FALSE
`

type GetPerformanceMineReviewContextRow struct {
	ID                 uuid.UUID   `json:"id"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	ContractStartDate  pgtype.Date `json:"contract_start_date"`
	LastAssessmentDate pgtype.Date `json:"last_assessment_date"`
}

func (q *Queries) GetPerformanceMineReviewContext(ctx context.Context, id uuid.UUID) (GetPerformanceMineReviewContextRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceMineReviewContext, id)
	var i GetPerformanceMineReviewContextRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.ContractStartDate,
		&i.LastAssessmentDate,
	)
	return i, err
}

const getPerformanceStats = `-- name: GetPerformanceStats :one
WITH active_employees AS (
    SELECT id
    FROM employee_profile
    WHERE is_archived = FALSE
      AND COALESCE(out_of_service, FALSE) = FALSE
),
completed AS (
    SELECT employee_id, assessment_date, total_score
    FROM performance_assessments
    WHERE status = 'completed'
)
SELECT
    (SELECT COUNT(*) FROM active_employees) AS total_employees,
    (SELECT COUNT(*) FROM completed) AS completed_count,
    (SELECT COUNT(*) FROM completed WHERE date_trunc('month', assessment_date) = date_trunc('month', CURRENT_DATE)) AS completed_this_month,
    (SELECT COALESCE(AVG(total_score), 0)::numeric FROM completed) AS average_score,
    (SELECT COUNT(DISTINCT employee_id) FROM completed) AS covered_count
`

type GetPerformanceStatsRow struct {
	TotalEmployees     int64   `json:"total_employees"`
	CompletedCount     int64   `json:"completed_count"`
	CompletedThisMonth int64   `json:"completed_this_month"`
	AverageScore       float64 `json:"average_score"`
	CoveredCount       int64   `json:"covered_count"`
}

func (q *Queries) GetPerformanceStats(ctx context.Context) (GetPerformanceStatsRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceStats)
	var i GetPerformanceStatsRow
	err := row.Scan(
		&i.TotalEmployees,
		&i.CompletedCount,
		&i.CompletedThisMonth,
		&i.AverageScore,
		&i.CoveredCount,
	)
	return i, err
}

const getPerformanceWorkAssignmentByID = `-- name: GetPerformanceWorkAssignmentByID :one
SELECT
    pwa.id,
    pwa.assessment_id,
    pa.assessment_date,
    pwa.employee_id,
    ep.first_name,
    ep.last_name,
    pwa.question_code,
    pwa.domain_code,
    pd.name_nl AS domain_name_nl,
    pd.name_en AS domain_name_en,
    pwa.question_text_nl,
    pwa.question_text_en,
    pwa.score,
    pwa.assignment_description,
    pwa.improvement_notes,
    pwa.expectations,
    pwa.advice,
    pwa.due_date,
    pwa.status,
    pwa.submitted_at,
    pwa.submission_text,
    pwa.feedback,
    pwa.reviewed_at
FROM performance_work_assignments pwa
JOIN employee_profile ep ON ep.id = pwa.employee_id
JOIN performance_assessments pa ON pa.id = pwa.assessment_id
JOIN performance_domains pd ON pd.code = pwa.domain_code
WHERE pwa.id = $1
`

type GetPerformanceWorkAssignmentByIDRow struct {
	ID                    uuid.UUID                           `json:"id"`
	AssessmentID          uuid.UUID                           `json:"assessment_id"`
	AssessmentDate        pgtype.Date                         `json:"assessment_date"`
	EmployeeID            uuid.UUID                           `json:"employee_id"`
	FirstName             string                              `json:"first_name"`
	LastName              string                              `json:"last_name"`
	QuestionCode          string                              `json:"question_code"`
	DomainCode            string                              `json:"domain_code"`
	DomainNameNl          string                              `json:"domain_name_nl"`
	DomainNameEn          string                              `json:"domain_name_en"`
	QuestionTextNl        string                              `json:"question_text_nl"`
	QuestionTextEn        string                              `json:"question_text_en"`
	Score                 float64                             `json:"score"`
	AssignmentDescription string                              `json:"assignment_description"`
	ImprovementNotes      *string                             `json:"improvement_notes"`
	Expectations          *string                             `json:"expectations"`
	Advice                *string                             `json:"advice"`
	DueDate               pgtype.Date                         `json:"due_date"`
	Status                PerformanceWorkAssignmentStatusEnum `json:"status"`
	SubmittedAt           pgtype.Timestamptz                  `json:"submitted_at"`
	SubmissionText        *string                             `json:"submission_text"`
	Feedback              *string                             `json:"feedback"`
	ReviewedAt            pgtype.Timestamptz                  `json:"reviewed_at"`
}

func (q *Queries) GetPerformanceWorkAssignmentByID(ctx context.Context, id uuid.UUID) (GetPerformanceWorkAssignmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPerformanceWorkAssignmentByID, id)
	var i GetPerformanceWorkAssignmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.AssessmentID,
		&i.AssessmentDate,
		&i.EmployeeID,
		&i.FirstName,
		&i.LastName,
		&i.QuestionCode,
		&i.DomainCode,
		&i.DomainNameNl,
		&i.DomainNameEn,
		&i.QuestionTextNl,
		&i.QuestionTextEn,
		&i.Score,
		&i.AssignmentDescription,
		&i.ImprovementNotes,
		&i.Expectations,
		&i.Advice,
		&i.DueDate,
		&i.Status,
		&i.SubmittedAt,
		&i.SubmissionText,
		&i.Feedback,
		&i.ReviewedAt,
	)
	return i, err
}

const getPerformanceWorkAssignmentStatusForUpdate = `-- name: GetPerformanceWorkAssignmentStatusForUpdate :one
SELECT status::text
FROM performance_work_assignments
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetPerformanceWorkAssignmentStatusForUpdate(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPerformanceWorkAssignmentStatusForUpdate, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listPerformanceAssessmentCatalog = `-- name: ListPerformanceAssessmentCatalog :many
SELECT
    d.code AS domain_code,
    d.name_nl AS domain_name_nl,
    d.name_en AS domain_name_en,
    d.sort_order AS domain_sort_order,
    q.code AS question_code,
    q.title_nl,
    q.title_en,
    q.description_nl,
    q.description_en,
    q.sort_order AS question_sort_order
FROM performance_domains d
JOIN performance_questions q ON q.domain_code = d.code
WHERE d.is_active = TRUE
  AND q.is_active = TRUE
ORDER BY d.sort_order, q.sort_order
`

type ListPerformanceAssessmentCatalogRow struct {
	DomainCode        string `json:"domain_code"`
	DomainNameNl      string `json:"domain_name_nl"`
	DomainNameEn      string `json:"domain_name_en"`
	DomainSortOrder   int32  `json:"domain_sort_order"`
	QuestionCode      string `json:"question_code"`
	TitleNl           string `json:"title_nl"`
	TitleEn           string `json:"title_en"`
	DescriptionNl     string `json:"description_nl"`
	DescriptionEn     string `json:"description_en"`
	QuestionSortOrder int32  `json:"question_sort_order"`
}

func (q *Queries) ListPerformanceAssessmentCatalog(ctx context.Context) ([]ListPerformanceAssessmentCatalogRow, error) {
	rows, err := q.db.Query(ctx, listPerformanceAssessmentCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPerformanceAssessmentCatalogRow{}
	for rows.Next() {
		var i ListPerformanceAssessmentCatalogRow
		if err := rows.Scan(
			&i.DomainCode,
			&i.DomainNameNl,
			&i.DomainNameEn,
			&i.DomainSortOrder,
			&i.QuestionCode,
			&i.TitleNl,
			&i.TitleEn,
			&i.DescriptionNl,
			&i.DescriptionEn,
			&i.QuestionSortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerformanceAssessmentScores = `-- name: ListPerformanceAssessmentScores :many
SELECT
    pas.id,
    pas.assessment_id,
    pas.question_code,
    pq.domain_code,
    pd.name_nl AS domain_name_nl,
    pd.name_en AS domain_name_en,
    pq.title_nl,
    pq.title_en,
    pq.description_nl,
    pq.description_en,
    pas.rating,
    pas.remarks
FROM performance_assessment_scores pas
JOIN performance_questions pq ON pq.code = pas.question_code
JOIN performance_domains pd ON pd.code = pq.domain_code
WHERE pas.assessment_id = $1
ORDER BY pq.domain_code, pq.sort_order
`

type ListPerformanceAssessmentScoresRow struct {
	ID            uuid.UUID `json:"id"`
	AssessmentID  uuid.UUID `json:"assessment_id"`
	QuestionCode  string    `json:"question_code"`
	DomainCode    string    `json:"domain_code"`
	DomainNameNl  string    `json:"domain_name_nl"`
	DomainNameEn  string    `json:"domain_name_en"`
	TitleNl       string    `json:"title_nl"`
	TitleEn       string    `json:"title_en"`
	DescriptionNl string    `json:"description_nl"`
	DescriptionEn string    `json:"description_en"`
	Rating        float64   `json:"rating"`
	Remarks       *string   `json:"remarks"`
}

func (q *Queries) ListPerformanceAssessmentScores(ctx context.Context, assessmentID uuid.UUID) ([]ListPerformanceAssessmentScoresRow, error) {
	rows, err := q.db.Query(ctx, listPerformanceAssessmentScores, assessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPerformanceAssessmentScoresRow{}
	for rows.Next() {
		var i ListPerformanceAssessmentScoresRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.QuestionCode,
			&i.DomainCode,
			&i.DomainNameNl,
			&i.DomainNameEn,
			&i.TitleNl,
			&i.TitleEn,
			&i.DescriptionNl,
			&i.DescriptionEn,
			&i.Rating,
			&i.Remarks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerformanceAssessments = `-- name: ListPerformanceAssessments :many
SELECT
    pa.id,
    pa.employee_id,
    ep.first_name,
    ep.last_name,
    pa.reviewer_employee_id,
    rev.first_name AS reviewer_first_name,
    rev.last_name AS reviewer_last_name,
    pa.assessment_date,
    pa.total_score,
    pa.status,
    pa.notes,
    pa.created_at,
    COUNT(*) OVER() AS total_count
FROM performance_assessments pa
JOIN employee_profile ep ON ep.id = pa.employee_id
LEFT JOIN employee_profile rev ON rev.id = pa.reviewer_employee_id
WHERE ($3::text IS NULL OR LOWER(ep.first_name || ' ' || ep.last_name) LIKE '%' || LOWER($3) || '%')
  AND ($4::uuid IS NULL OR pa.employee_id = $4)
  AND ($5::text IS NULL OR pa.status::text = $5)
  AND ($6::date IS NULL OR pa.assessment_date >= $6)
  AND ($7::date IS NULL OR pa.assessment_date <= $7)
ORDER BY pa.assessment_date DESC, pa.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPerformanceAssessmentsParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	Search     *string     `json:"search"`
	EmployeeID *uuid.UUID  `json:"employee_id"`
	Status     *string     `json:"status"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
}

type ListPerformanceAssessmentsRow struct {
	ID                 uuid.UUID                       `json:"id"`
	EmployeeID         uuid.UUID                       `json:"employee_id"`
	FirstName          string                          `json:"first_name"`
	LastName           string                          `json:"last_name"`
	ReviewerEmployeeID uuid.UUID                       `json:"reviewer_employee_id"`
	ReviewerFirstName  *string                         `json:"reviewer_first_name"`
	ReviewerLastName   *string                         `json:"reviewer_last_name"`
	AssessmentDate     pgtype.Date                     `json:"assessment_date"`
	TotalScore         *float64                        `json:"total_score"`
	Status             PerformanceAssessmentStatusEnum `json:"status"`
	Notes              *string                         `json:"notes"`
	CreatedAt          pgtype.Timestamptz              `json:"created_at"`
	TotalCount         int64                           `json:"total_count"`
}

func (q *Queries) ListPerformanceAssessments(ctx context.Context, arg ListPerformanceAssessmentsParams) ([]ListPerformanceAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, listPerformanceAssessments,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.EmployeeID,
		arg.Status,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPerformanceAssessmentsRow{}
	for rows.Next() {
		var i ListPerformanceAssessmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.FirstName,
			&i.LastName,
			&i.ReviewerEmployeeID,
			&i.ReviewerFirstName,
			&i.ReviewerLastName,
			&i.AssessmentDate,
			&i.TotalScore,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerformanceUpcoming = `-- name: ListPerformanceUpcoming :many
WITH employee_review_status AS (
    SELECT
        ep.id,
        ep.first_name,
        ep.last_name,
        ep.contract_start_date,
        (
            SELECT MAX(pa.assessment_date)::date
            FROM performance_assessments pa
            WHERE pa.employee_id = ep.id
              AND pa.status = 'completed'
        ) AS last_assessment_date
    FROM employee_profile ep
    WHERE ep.is_archived = FALSE
      AND COALESCE(ep.out_of_service, FALSE) = FALSE
),
employee_next_dates AS (
    SELECT
        id,
        first_name,
        last_name,
        last_assessment_date,
        CASE
            WHEN last_assessment_date IS NOT NULL
                THEN (last_assessment_date + INTERVAL '42 days')::date
            WHEN contract_start_date IS NOT NULL
                THEN (contract_start_date + INTERVAL '42 days')::date
        END::date AS next_assessment_date
    FROM employee_review_status
)
SELECT
    id,
    first_name,
    last_name,
    last_assessment_date,
    next_assessment_date
FROM employee_next_dates
WHERE next_assessment_date IS NOT NULL
  AND next_assessment_date <= CURRENT_DATE + $1::integer * INTERVAL '1 day'
ORDER BY next_assessment_date ASC
`

type ListPerformanceUpcomingRow struct {
	ID                 uuid.UUID   `json:"id"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	LastAssessmentDate pgtype.Date `json:"last_assessment_date"`
	NextAssessmentDate pgtype.Date `json:"next_assessment_date"`
}

func (q *Queries) ListPerformanceUpcoming(ctx context.Context, dollar_1 int32) ([]ListPerformanceUpcomingRow, error) {
	rows, err := q.db.Query(ctx, listPerformanceUpcoming, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPerformanceUpcomingRow{}
	for rows.Next() {
		var i ListPerformanceUpcomingRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.LastAssessmentDate,
			&i.NextAssessmentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerformanceWorkAssignments = `-- name: ListPerformanceWorkAssignments :many
SELECT
    pwa.id,
    pwa.assessment_id,
    pa.assessment_date,
    pwa.employee_id,
    ep.first_name,
    ep.last_name,
    pwa.question_code,
    pwa.domain_code,
    pd.name_nl AS domain_name_nl,
    pd.name_en AS domain_name_en,
    pwa.question_text_nl,
    pwa.question_text_en,
    pwa.score,
    pwa.assignment_description,
    pwa.improvement_notes,
    pwa.expectations,
    pwa.advice,
    pwa.due_date,
    pwa.status,
    pwa.submitted_at,
    pwa.submission_text,
    pwa.feedback,
    pwa.reviewed_at,
    COUNT(*) OVER() AS total_count
FROM performance_work_assignments pwa
JOIN employee_profile ep ON ep.id = pwa.employee_id
JOIN performance_assessments pa ON pa.id = pwa.assessment_id
JOIN performance_domains pd ON pd.code = pwa.domain_code
WHERE ($3::uuid IS NULL OR pwa.employee_id = $3)
  AND ($4::text IS NULL OR pwa.status::text = $4)
  AND ($5::date IS NULL OR pwa.due_date <= $5)
  AND ($6::date IS NULL OR pwa.due_date >= $6)
ORDER BY pwa.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPerformanceWorkAssignmentsParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	EmployeeID *uuid.UUID  `json:"employee_id"`
	Status     *string     `json:"status"`
	DueBefore  pgtype.Date `json:"due_before"`
	DueAfter   pgtype.Date `json:"due_after"`
}

type ListPerformanceWorkAssignmentsRow struct {
	ID                    uuid.UUID                           `json:"id"`
	AssessmentID          uuid.UUID                           `json:"assessment_id"`
	AssessmentDate        pgtype.Date                         `json:"assessment_date"`
	EmployeeID            uuid.UUID                           `json:"employee_id"`
	FirstName             string                              `json:"first_name"`
	LastName              string                              `json:"last_name"`
	QuestionCode          string                              `json:"question_code"`
	DomainCode            string                              `json:"domain_code"`
	DomainNameNl          string                              `json:"domain_name_nl"`
	DomainNameEn          string                              `json:"domain_name_en"`
	QuestionTextNl        string                              `json:"question_text_nl"`
	QuestionTextEn        string                              `json:"question_text_en"`
	Score                 float64                             `json:"score"`
	AssignmentDescription string                              `json:"assignment_description"`
	ImprovementNotes      *string                             `json:"improvement_notes"`
	Expectations          *string                             `json:"expectations"`
	Advice                *string                             `json:"advice"`
	DueDate               pgtype.Date                         `json:"due_date"`
	Status                PerformanceWorkAssignmentStatusEnum `json:"status"`
	SubmittedAt           pgtype.Timestamptz                  `json:"submitted_at"`
	SubmissionText        *string                             `json:"submission_text"`
	Feedback              *string                             `json:"feedback"`
	ReviewedAt            pgtype.Timestamptz                  `json:"reviewed_at"`
	TotalCount            int64                               `json:"total_count"`
}

func (q *Queries) ListPerformanceWorkAssignments(ctx context.Context, arg ListPerformanceWorkAssignmentsParams) ([]ListPerformanceWorkAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listPerformanceWorkAssignments,
		arg.Limit,
		arg.Offset,
		arg.EmployeeID,
		arg.Status,
		arg.DueBefore,
		arg.DueAfter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPerformanceWorkAssignmentsRow{}
	for rows.Next() {
		var i ListPerformanceWorkAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssessmentID,
			&i.AssessmentDate,
			&i.EmployeeID,
			&i.FirstName,
			&i.LastName,
			&i.QuestionCode,
			&i.DomainCode,
			&i.DomainNameNl,
			&i.DomainNameEn,
			&i.QuestionTextNl,
			&i.QuestionTextEn,
			&i.Score,
			&i.AssignmentDescription,
			&i.ImprovementNotes,
			&i.Expectations,
			&i.Advice,
			&i.DueDate,
			&i.Status,
			&i.SubmittedAt,
			&i.SubmissionText,
			&i.Feedback,
			&i.ReviewedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerformanceWorkAssignmentDecision = `-- name: UpdatePerformanceWorkAssignmentDecision :exec
UPDATE performance_work_assignments
SET status = $2,
    feedback = $3,
    reviewed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdatePerformanceWorkAssignmentDecisionParams struct {
	ID       uuid.UUID                           `json:"id"`
	Status   PerformanceWorkAssignmentStatusEnum `json:"status"`
	Feedback *string                             `json:"feedback"`
}

func (q *Queries) UpdatePerformanceWorkAssignmentDecision(ctx context.Context, arg UpdatePerformanceWorkAssignmentDecisionParams) error {
	_, err := q.db.Exec(ctx, updatePerformanceWorkAssignmentDecision, arg.ID, arg.Status, arg.Feedback)
	return err
}
