// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddEducationToEmployeeProfile(ctx context.Context, arg AddEducationToEmployeeProfileParams) (EmployeeEducation, error)
	AddEmployeeCertification(ctx context.Context, arg AddEmployeeCertificationParams) (Certification, error)
	AddEmployeeContractDetails(ctx context.Context, arg AddEmployeeContractDetailsParams) (EmployeeProfile, error)
	AddEmployeeExperience(ctx context.Context, arg AddEmployeeExperienceParams) (EmployeeExperience, error)
	// Bulk-insert permission IDs into a role (idempotent).
	AddPermissionsToRole(ctx context.Context, arg AddPermissionsToRoleParams) error
	// Bulk-insert explicit overrides for a user (idempotent by replacement flow).
	AddUserPermissionOverrides(ctx context.Context, arg AddUserPermissionOverridesParams) error
	ApplyLeaveBalanceDeduction(ctx context.Context, arg ApplyLeaveBalanceDeductionParams) (LeaveBalance, error)
	ApplyLeaveBalanceTotalAdjustment(ctx context.Context, arg ApplyLeaveBalanceTotalAdjustmentParams) (LeaveBalance, error)
	ApprovePayoutRequest(ctx context.Context, arg ApprovePayoutRequestParams) (LeavePayoutRequest, error)
	ApproveTimeEntry(ctx context.Context, arg ApproveTimeEntryParams) (ApproveTimeEntryRow, error)
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	AssignTimeEntriesToPayPeriod(ctx context.Context, arg AssignTimeEntriesToPayPeriodParams) error
	AssignTrainingToEmployee(ctx context.Context, arg AssignTrainingToEmployeeParams) (EmployeeTrainingAssignment, error)
	CancelTrainingAssignment(ctx context.Context, arg CancelTrainingAssignmentParams) (EmployeeTrainingAssignment, error)
	CheckAllShiftsExist(ctx context.Context, arg CheckAllShiftsExistParams) (bool, error)
	// ---------- 6. CHECK UTILITIES ----------
	// Returns true/false whether the user has the named permission.
	CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error)
	CloneHandbookTemplateToDraft(ctx context.Context, arg CloneHandbookTemplateToDraftParams) (CloneHandbookTemplateToDraftRow, error)
	CompleteEmployeeHandbookStep(ctx context.Context, arg CompleteEmployeeHandbookStepParams) (EmployeeHandbookStepProgress, error)
	ComputeLegalLeaveTotalForYear(ctx context.Context, arg ComputeLegalLeaveTotalForYearParams) (int32, error)
	CountEligibleEmployeesForHandbookAssignment(ctx context.Context, arg CountEligibleEmployeesForHandbookAssignmentParams) (int64, error)
	CountEmployeeContractChanges(ctx context.Context, employeeID uuid.UUID) (int64, error)
	CountEmployeeHandbookAssignments(ctx context.Context, arg CountEmployeeHandbookAssignmentsParams) (int64, error)
	CountEmployeeProfile(ctx context.Context, arg CountEmployeeProfileParams) (int64, error)
	CountHandbookStepsByTemplateID(ctx context.Context, templateID uuid.UUID) (int32, error)
	CountRemainingRequiredHandbookSteps(ctx context.Context, employeeHandbookID uuid.UUID) (int32, error)
	CountScheduleOverlapsForEmployee(ctx context.Context, arg CountScheduleOverlapsForEmployeeParams) (int64, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateEmployeeContractChange(ctx context.Context, arg CreateEmployeeContractChangeParams) (EmployeeContractChange, error)
	CreateEmployeeHandbookAssignmentHistory(ctx context.Context, arg CreateEmployeeHandbookAssignmentHistoryParams) (EmployeeHandbookAssignmentHistory, error)
	CreateEmployeeHandbookFromTemplate(ctx context.Context, arg CreateEmployeeHandbookFromTemplateParams) (CreateEmployeeHandbookFromTemplateRow, error)
	CreateEmployeeProfile(ctx context.Context, arg CreateEmployeeProfileParams) (EmployeeProfile, error)
	CreateHandbookStep(ctx context.Context, arg CreateHandbookStepParams) (HandbookStep, error)
	CreateHandbookTemplateForDepartment(ctx context.Context, arg CreateHandbookTemplateForDepartmentParams) (HandbookTemplate, error)
	CreateLateArrival(ctx context.Context, arg CreateLateArrivalParams) (LateArrival, error)
	CreateLeaveBalanceAdjustmentAudit(ctx context.Context, arg CreateLeaveBalanceAdjustmentAuditParams) (LeaveBalanceAdjustment, error)
	CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (LeaveRequest, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error)
	CreatePayPeriod(ctx context.Context, arg CreatePayPeriodParams) (PayPeriod, error)
	CreatePayPeriodLineItem(ctx context.Context, arg CreatePayPeriodLineItemParams) (PayPeriodLineItem, error)
	CreatePayoutRequest(ctx context.Context, arg CreatePayoutRequestParams) (LeavePayoutRequest, error)
	// ---------- 1. ROLES ----------
	// Insert a new role and return the created row.
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (CreateScheduleRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShift(ctx context.Context, arg CreateShiftParams) (LocationShift, error)
	CreateShiftSwapRequest(ctx context.Context, arg CreateShiftSwapRequestParams) (ShiftSwapRequest, error)
	CreateTemp2FaSecret(ctx context.Context, arg CreateTemp2FaSecretParams) (int64, error)
	CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (CreateTimeEntryRow, error)
	CreateTimeEntryUpdateAudit(ctx context.Context, arg CreateTimeEntryUpdateAuditParams) error
	CreateTrainingCatalogItem(ctx context.Context, arg CreateTrainingCatalogItemParams) (TrainingCatalogItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CustomUser, error)
	DeleteDepartment(ctx context.Context, id uuid.UUID) (Department, error)
	DeleteEmployeeCertification(ctx context.Context, id uuid.UUID) (Certification, error)
	DeleteEmployeeEducation(ctx context.Context, id uuid.UUID) (EmployeeEducation, error)
	DeleteEmployeeExperience(ctx context.Context, id uuid.UUID) (EmployeeExperience, error)
	DeleteHandbookStepByID(ctx context.Context, id uuid.UUID) error
	DeleteLocation(ctx context.Context, id uuid.UUID) (Location, error)
	DeleteOrganisation(ctx context.Context, id uuid.UUID) (Organisation, error)
	DeleteSchedule(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteShift(ctx context.Context, id uuid.UUID) error
	// Removes all explicit overrides for the given user.
	DeleteUserPermissionOverrides(ctx context.Context, userID uuid.UUID) error
	Enable2Fa(ctx context.Context, arg Enable2FaParams) (int64, error)
	EnsureLeaveBalanceForYear(ctx context.Context, arg EnsureLeaveBalanceForYearParams) error
	ExpirePendingShiftSwapRequests(ctx context.Context) error
	GetActiveEmployeeHandbookByEmployeeID(ctx context.Context, employeeID uuid.UUID) (GetActiveEmployeeHandbookByEmployeeIDRow, error)
	GetActiveHandbookTemplateByDepartment(ctx context.Context, departmentID uuid.UUID) (HandbookTemplate, error)
	GetActiveLeavePolicyByType(ctx context.Context, leaveType LeaveRequestTypeEnum) (LeavePolicy, error)
	// Returns the ID of the admin role.
	GetAdminRoleId(ctx context.Context) (uuid.UUID, error)
	GetAllAdminUsers(ctx context.Context) ([]CustomUser, error)
	GetAppOrganizationProfile(ctx context.Context) (GetAppOrganizationProfileRow, error)
	GetCurrentMonthTimeEntryStats(ctx context.Context) (GetCurrentMonthTimeEntryStatsRow, error)
	GetDepartment(ctx context.Context, id uuid.UUID) (Department, error)
	GetEmployeeContractDetails(ctx context.Context, id uuid.UUID) (GetEmployeeContractDetailsRow, error)
	GetEmployeeContractForLeave(ctx context.Context, employeeID uuid.UUID) (GetEmployeeContractForLeaveRow, error)
	GetEmployeeContractSnapshotForContractChange(ctx context.Context, id uuid.UUID) (GetEmployeeContractSnapshotForContractChangeRow, error)
	GetEmployeeCounts(ctx context.Context) (GetEmployeeCountsRow, error)
	GetEmployeeHandbookByID(ctx context.Context, id uuid.UUID) (EmployeeHandbook, error)
	GetEmployeeHandbookDetailsByID(ctx context.Context, id uuid.UUID) (GetEmployeeHandbookDetailsByIDRow, error)
	GetEmployeePayoutContract(ctx context.Context, id uuid.UUID) (GetEmployeePayoutContractRow, error)
	GetEmployeeProfileByID(ctx context.Context, id uuid.UUID) (GetEmployeeProfileByIDRow, error)
	GetEmployeeProfileByUserID(ctx context.Context, id uuid.UUID) (GetEmployeeProfileByUserIDRow, error)
	GetEmployeeSchedules(ctx context.Context, arg GetEmployeeSchedulesParams) ([]GetEmployeeSchedulesRow, error)
	GetEmployeeSchedulesByDay(ctx context.Context, arg GetEmployeeSchedulesByDayParams) ([]GetEmployeeSchedulesByDayRow, error)
	GetGlobalOrganisationCounts(ctx context.Context) (GetGlobalOrganisationCountsRow, error)
	GetHandbookStepByID(ctx context.Context, id uuid.UUID) (HandbookStep, error)
	GetHandbookTemplateByID(ctx context.Context, id uuid.UUID) (HandbookTemplate, error)
	GetLeaveRequestStats(ctx context.Context) (GetLeaveRequestStatsRow, error)
	GetLocation(ctx context.Context, id uuid.UUID) (Location, error)
	GetMyLeaveRequestStats(ctx context.Context, employeeID uuid.UUID) (GetMyLeaveRequestStatsRow, error)
	GetOrganisation(ctx context.Context, id uuid.UUID) (GetOrganisationRow, error)
	GetOrganisationCounts(ctx context.Context, id uuid.UUID) (GetOrganisationCountsRow, error)
	GetPayPeriodByEmployeePeriod(ctx context.Context, arg GetPayPeriodByEmployeePeriodParams) (GetPayPeriodByEmployeePeriodRow, error)
	GetPayPeriodByID(ctx context.Context, id uuid.UUID) (GetPayPeriodByIDRow, error)
	// Returns a single role by ID.
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetScheduleById(ctx context.Context, id uuid.UUID) (GetScheduleByIdRow, error)
	GetScheduleForSwapValidation(ctx context.Context, id uuid.UUID) (GetScheduleForSwapValidationRow, error)
	GetSchedulesByLocationInRange(ctx context.Context, arg GetSchedulesByLocationInRangeParams) ([]GetSchedulesByLocationInRangeRow, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetShiftByID(ctx context.Context, id uuid.UUID) (LocationShift, error)
	GetShiftSwapRequestByID(ctx context.Context, id uuid.UUID) (ShiftSwapRequest, error)
	GetShiftSwapRequestDetailsByID(ctx context.Context, id uuid.UUID) (GetShiftSwapRequestDetailsByIDRow, error)
	GetShiftsByLocationID(ctx context.Context, locationID uuid.UUID) ([]LocationShift, error)
	GetTemp2FaSecret(ctx context.Context, id uuid.UUID) (*string, error)
	GetTimeEntryByID(ctx context.Context, id uuid.UUID) (GetTimeEntryByIDRow, error)
	GetTrainingAssignmentByID(ctx context.Context, id uuid.UUID) (EmployeeTrainingAssignment, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserIDByEmployeeID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// ---------- 4. USER-ROLE MAPPING ----------
	// Returns every role granted to a user.
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error)
	ListActiveSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]ListActiveSessionsByUserIDRow, error)
	ListAllLocations(ctx context.Context) ([]Location, error)
	ListAllLocationsPaginated(ctx context.Context, arg ListAllLocationsPaginatedParams) ([]ListAllLocationsPaginatedRow, error)
	// ---------- 2. PERMISSIONS ----------
	// Returns every permission ordered by id.
	ListAllPermissions(ctx context.Context) ([]Permission, error)
	ListAssignedSchedulesForEmployeeOnDate(ctx context.Context, arg ListAssignedSchedulesForEmployeeOnDateParams) ([]ListAssignedSchedulesForEmployeeOnDateRow, error)
	ListDepartmentsPaginated(ctx context.Context, arg ListDepartmentsPaginatedParams) ([]ListDepartmentsPaginatedRow, error)
	ListEducations(ctx context.Context, employeeID uuid.UUID) ([]EmployeeEducation, error)
	// Returns effective permissions after applying role inheritance and overrides.
	ListEffectiveUserPermissions(ctx context.Context, userID uuid.UUID) ([]ListEffectiveUserPermissionsRow, error)
	ListEligibleEmployeesForHandbookAssignment(ctx context.Context, arg ListEligibleEmployeesForHandbookAssignmentParams) ([]ListEligibleEmployeesForHandbookAssignmentRow, error)
	ListEmployeeCertifications(ctx context.Context, employeeID uuid.UUID) ([]Certification, error)
	ListEmployeeContractChanges(ctx context.Context, employeeID uuid.UUID) ([]ListEmployeeContractChangesRow, error)
	ListEmployeeExperience(ctx context.Context, employeeID uuid.UUID) ([]EmployeeExperience, error)
	ListEmployeeHandbookAssignmentHistoryByEmployeeID(ctx context.Context, arg ListEmployeeHandbookAssignmentHistoryByEmployeeIDParams) ([]EmployeeHandbookAssignmentHistory, error)
	ListEmployeeHandbookAssignments(ctx context.Context, arg ListEmployeeHandbookAssignmentsParams) ([]ListEmployeeHandbookAssignmentsRow, error)
	ListEmployeeHandbookStepsByHandbookID(ctx context.Context, employeeHandbookID uuid.UUID) ([]ListEmployeeHandbookStepsByHandbookIDRow, error)
	ListEmployeeNamesByIDs(ctx context.Context, employeeIds []uuid.UUID) ([]ListEmployeeNamesByIDsRow, error)
	ListEmployeeProfile(ctx context.Context, arg ListEmployeeProfileParams) ([]ListEmployeeProfileRow, error)
	ListEmployeesEligibleForDepartmentHandbookSeed(ctx context.Context, arg ListEmployeesEligibleForDepartmentHandbookSeedParams) ([]uuid.UUID, error)
	ListEmployeesWithContractHours(ctx context.Context, dollar_1 []uuid.UUID) ([]ListEmployeesWithContractHoursRow, error)
	ListHandbookStepsByTemplate(ctx context.Context, templateID uuid.UUID) ([]HandbookStep, error)
	ListHandbookTemplatesByDepartment(ctx context.Context, departmentID uuid.UUID) ([]HandbookTemplate, error)
	// ---------- 5. USER-PERMISSION OVERRIDES ----------
	// Returns permissions inherited from the user's assigned role.
	ListInheritedUserPermissions(ctx context.Context, userID uuid.UUID) ([]ListInheritedUserPermissionsRow, error)
	ListLateArrivalsPaginated(ctx context.Context, arg ListLateArrivalsPaginatedParams) ([]ListLateArrivalsPaginatedRow, error)
	ListLeaveBalancesForEmployeeFromYearForUpdate(ctx context.Context, arg ListLeaveBalancesForEmployeeFromYearForUpdateParams) ([]LeaveBalance, error)
	ListLeaveBalancesPaginated(ctx context.Context, arg ListLeaveBalancesPaginatedParams) ([]ListLeaveBalancesPaginatedRow, error)
	ListLeaveCalendarRows(ctx context.Context, arg ListLeaveCalendarRowsParams) ([]ListLeaveCalendarRowsRow, error)
	ListLeaveRequestsPaginated(ctx context.Context, arg ListLeaveRequestsPaginatedParams) ([]ListLeaveRequestsPaginatedRow, error)
	ListLocations(ctx context.Context, organisationID uuid.UUID) ([]Location, error)
	ListLocationsPaginated(ctx context.Context, arg ListLocationsPaginatedParams) ([]ListLocationsPaginatedRow, error)
	ListLockedPayPeriodMultiplierSummaries(ctx context.Context, payPeriodIds []uuid.UUID) ([]ListLockedPayPeriodMultiplierSummariesRow, error)
	ListMyLateArrivalsPaginated(ctx context.Context, arg ListMyLateArrivalsPaginatedParams) ([]ListMyLateArrivalsPaginatedRow, error)
	ListMyLeaveBalancesPaginated(ctx context.Context, arg ListMyLeaveBalancesPaginatedParams) ([]ListMyLeaveBalancesPaginatedRow, error)
	ListMyLeaveRequestsPaginated(ctx context.Context, arg ListMyLeaveRequestsPaginatedParams) ([]ListMyLeaveRequestsPaginatedRow, error)
	ListMyPayoutRequestsPaginated(ctx context.Context, arg ListMyPayoutRequestsPaginatedParams) ([]ListMyPayoutRequestsPaginatedRow, error)
	ListMyShiftSwapRequests(ctx context.Context, requesterEmployeeID uuid.UUID) ([]ListMyShiftSwapRequestsRow, error)
	ListMyTimeEntriesPaginated(ctx context.Context, arg ListMyTimeEntriesPaginatedParams) ([]ListMyTimeEntriesPaginatedRow, error)
	ListNationalHolidaysInRange(ctx context.Context, arg ListNationalHolidaysInRangeParams) ([]ListNationalHolidaysInRangeRow, error)
	ListOrganisations(ctx context.Context) ([]ListOrganisationsRow, error)
	ListOrganisationsPaginated(ctx context.Context, arg ListOrganisationsPaginatedParams) ([]ListOrganisationsPaginatedRow, error)
	ListPayPeriodLineItemsByPayPeriodID(ctx context.Context, payPeriodID uuid.UUID) ([]PayPeriodLineItem, error)
	ListPayPeriodsByEmployeeIDsAndRange(ctx context.Context, arg ListPayPeriodsByEmployeeIDsAndRangeParams) ([]ListPayPeriodsByEmployeeIDsAndRangeRow, error)
	ListPayPeriodsPaginated(ctx context.Context, arg ListPayPeriodsPaginatedParams) ([]ListPayPeriodsPaginatedRow, error)
	ListPayoutRequestsPaginated(ctx context.Context, arg ListPayoutRequestsPaginatedParams) ([]ListPayoutRequestsPaginatedRow, error)
	ListPayrollMonthApprovedTimeEntriesByEmployeeIDs(ctx context.Context, arg ListPayrollMonthApprovedTimeEntriesByEmployeeIDsParams) ([]ListPayrollMonthApprovedTimeEntriesByEmployeeIDsRow, error)
	ListPayrollMonthEmployeesAll(ctx context.Context, arg ListPayrollMonthEmployeesAllParams) ([]ListPayrollMonthEmployeesAllRow, error)
	ListPayrollMonthEmployeesPaginated(ctx context.Context, arg ListPayrollMonthEmployeesPaginatedParams) ([]ListPayrollMonthEmployeesPaginatedRow, error)
	ListPayrollMonthPendingEntriesByEmployeeIDs(ctx context.Context, arg ListPayrollMonthPendingEntriesByEmployeeIDsParams) ([]ListPayrollMonthPendingEntriesByEmployeeIDsRow, error)
	ListPayrollMonthPendingSummariesByEmployeeIDs(ctx context.Context, arg ListPayrollMonthPendingSummariesByEmployeeIDsParams) ([]ListPayrollMonthPendingSummariesByEmployeeIDsRow, error)
	ListPayrollPreviewTimeEntries(ctx context.Context, arg ListPayrollPreviewTimeEntriesParams) ([]ListPayrollPreviewTimeEntriesRow, error)
	// ---------- 3. ROLE-PERMISSION MAPPING ----------
	// Returns all permissions attached to a single role.
	ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]ListRolePermissionsRow, error)
	// Returns every role ordered by id with count of permissions and employees.
	ListRoles(ctx context.Context) ([]ListRolesRow, error)
	ListShiftSwapRequestsPaginated(ctx context.Context, arg ListShiftSwapRequestsPaginatedParams) ([]ListShiftSwapRequestsPaginatedRow, error)
	ListTimeEntriesPaginated(ctx context.Context, arg ListTimeEntriesPaginatedParams) ([]ListTimeEntriesPaginatedRow, error)
	ListTrainingAssignmentsPaginated(ctx context.Context, arg ListTrainingAssignmentsPaginatedParams) ([]ListTrainingAssignmentsPaginatedRow, error)
	ListTrainingCatalogItemsPaginated(ctx context.Context, arg ListTrainingCatalogItemsPaginatedParams) ([]ListTrainingCatalogItemsPaginatedRow, error)
	ListUserIDsByEmployeeIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]uuid.UUID, error)
	// Returns explicit allow/deny overrides configured for a user.
	ListUserPermissionOverrides(ctx context.Context, userID uuid.UUID) ([]ListUserPermissionOverridesRow, error)
	LockLeaveBalanceByEmployeeYear(ctx context.Context, arg LockLeaveBalanceByEmployeeYearParams) (LeaveBalance, error)
	LockLeaveRequestByID(ctx context.Context, id uuid.UUID) (LeaveRequest, error)
	LockPayPeriodByID(ctx context.Context, id uuid.UUID) (PayPeriod, error)
	LockPayoutRequestByID(ctx context.Context, id uuid.UUID) (LeavePayoutRequest, error)
	LockPayrollPreviewTimeEntries(ctx context.Context, arg LockPayrollPreviewTimeEntriesParams) ([]LockPayrollPreviewTimeEntriesRow, error)
	LockSchedulesByIDsForSwap(ctx context.Context, dollar_1 []uuid.UUID) ([]LockSchedulesByIDsForSwapRow, error)
	LockShiftSwapRequestForAdminDecision(ctx context.Context, id uuid.UUID) (ShiftSwapRequest, error)
	LockTimeEntryByID(ctx context.Context, id uuid.UUID) (TimeEntry, error)
	MarkEmployeeHandbookCompleted(ctx context.Context, id uuid.UUID) (EmployeeHandbook, error)
	MarkEmployeeHandbookStarted(ctx context.Context, id uuid.UUID) (EmployeeHandbook, error)
	MarkPayPeriodPaid(ctx context.Context, id uuid.UUID) (PayPeriod, error)
	MarkPayoutRequestPaid(ctx context.Context, arg MarkPayoutRequestPaidParams) (LeavePayoutRequest, error)
	MarkShiftSwapConfirmed(ctx context.Context, arg MarkShiftSwapConfirmedParams) (ShiftSwapRequest, error)
	PublishHandbookTemplate(ctx context.Context, arg PublishHandbookTemplateParams) (HandbookTemplate, error)
	RejectPayoutRequest(ctx context.Context, arg RejectPayoutRequestParams) (LeavePayoutRequest, error)
	RejectTimeEntry(ctx context.Context, arg RejectTimeEntryParams) (RejectTimeEntryRow, error)
	// Removes *all* permissions from the given role.
	RemovePermissionsFromRole(ctx context.Context, roleID uuid.UUID) error
	SearchEmployeesByNameOrEmail(ctx context.Context, search *string) ([]SearchEmployeesByNameOrEmailRow, error)
	SetEmployeeProfilePicture(ctx context.Context, arg SetEmployeeProfilePictureParams) (CustomUser, error)
	SyncEmployeeProfileContractFromLatestChange(ctx context.Context, id uuid.UUID) (EmployeeProfile, error)
	UpdateAppOrganizationProfile(ctx context.Context, arg UpdateAppOrganizationProfileParams) (UpdateAppOrganizationProfileRow, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateEmployeeCertification(ctx context.Context, arg UpdateEmployeeCertificationParams) (Certification, error)
	UpdateEmployeeEducation(ctx context.Context, arg UpdateEmployeeEducationParams) (EmployeeEducation, error)
	UpdateEmployeeExperience(ctx context.Context, arg UpdateEmployeeExperienceParams) (EmployeeExperience, error)
	UpdateEmployeeIsSubcontractor(ctx context.Context, arg UpdateEmployeeIsSubcontractorParams) (EmployeeProfile, error)
	UpdateEmployeeProfile(ctx context.Context, arg UpdateEmployeeProfileParams) (EmployeeProfile, error)
	UpdateHandbookStepByID(ctx context.Context, arg UpdateHandbookStepByIDParams) (HandbookStep, error)
	UpdateHandbookStepSortOrder(ctx context.Context, arg UpdateHandbookStepSortOrderParams) error
	UpdateHandbookTemplateMetadata(ctx context.Context, arg UpdateHandbookTemplateMetadataParams) (HandbookTemplate, error)
	UpdateLeaveRequestDecision(ctx context.Context, arg UpdateLeaveRequestDecisionParams) (LeaveRequest, error)
	UpdateLeaveRequestEditableFields(ctx context.Context, arg UpdateLeaveRequestEditableFieldsParams) (LeaveRequest, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateOrganisation(ctx context.Context, arg UpdateOrganisationParams) (Organisation, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (UpdateScheduleRow, error)
	UpdateScheduleEmployeeAssignment(ctx context.Context, arg UpdateScheduleEmployeeAssignmentParams) error
	UpdateShift(ctx context.Context, arg UpdateShiftParams) (LocationShift, error)
	UpdateShiftSwapAdminDecision(ctx context.Context, arg UpdateShiftSwapAdminDecisionParams) (ShiftSwapRequest, error)
	UpdateShiftSwapStatusAfterRecipientResponse(ctx context.Context, arg UpdateShiftSwapStatusAfterRecipientResponseParams) (ShiftSwapRequest, error)
	UpdateTimeEntryByAdmin(ctx context.Context, arg UpdateTimeEntryByAdminParams) (UpdateTimeEntryByAdminRow, error)
	WaiveActiveEmployeeHandbooksByEmployeeID(ctx context.Context, employeeID uuid.UUID) error
	WaiveEmployeeHandbookByID(ctx context.Context, id uuid.UUID) (EmployeeHandbook, error)
}

var _ Querier = (*Queries)(nil)
