// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
WITH inserted_schedule AS (
    INSERT INTO schedules (
        employee_id,
        location_id,
        location_shift_id,
        shift_name_snapshot,
        shift_start_time_snapshot,
        shift_end_time_snapshot,
        is_custom,
        created_by_employee_id,
        start_datetime,
        end_datetime
    ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
    )
    RETURNING id, employee_id, location_id, location_shift_id, shift_name_snapshot, shift_start_time_snapshot, shift_end_time_snapshot, is_custom, start_datetime, end_datetime, created_by_employee_id, created_at, updated_at
)
SELECT 
    s.id, s.employee_id, s.location_id, s.location_shift_id, s.shift_name_snapshot, s.shift_start_time_snapshot, s.shift_end_time_snapshot, s.is_custom, s.start_datetime, s.end_datetime, s.created_by_employee_id, s.created_at, s.updated_at,
    l.name as location_name
FROM inserted_schedule s
JOIN location l ON s.location_id = l.id
`

type CreateScheduleParams struct {
	EmployeeID             uuid.UUID          `json:"employee_id"`
	LocationID             uuid.UUID          `json:"location_id"`
	LocationShiftID        *uuid.UUID         `json:"location_shift_id"`
	ShiftNameSnapshot      *string            `json:"shift_name_snapshot"`
	ShiftStartTimeSnapshot pgtype.Time        `json:"shift_start_time_snapshot"`
	ShiftEndTimeSnapshot   pgtype.Time        `json:"shift_end_time_snapshot"`
	IsCustom               bool               `json:"is_custom"`
	CreatedByEmployeeID    uuid.UUID          `json:"created_by_employee_id"`
	StartDatetime          pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime            pgtype.Timestamptz `json:"end_datetime"`
}

type CreateScheduleRow struct {
	ID                     uuid.UUID          `json:"id"`
	EmployeeID             uuid.UUID          `json:"employee_id"`
	LocationID             uuid.UUID          `json:"location_id"`
	LocationShiftID        *uuid.UUID         `json:"location_shift_id"`
	ShiftNameSnapshot      *string            `json:"shift_name_snapshot"`
	ShiftStartTimeSnapshot pgtype.Time        `json:"shift_start_time_snapshot"`
	ShiftEndTimeSnapshot   pgtype.Time        `json:"shift_end_time_snapshot"`
	IsCustom               bool               `json:"is_custom"`
	StartDatetime          pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime            pgtype.Timestamptz `json:"end_datetime"`
	CreatedByEmployeeID    uuid.UUID          `json:"created_by_employee_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	LocationName           string             `json:"location_name"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (CreateScheduleRow, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.EmployeeID,
		arg.LocationID,
		arg.LocationShiftID,
		arg.ShiftNameSnapshot,
		arg.ShiftStartTimeSnapshot,
		arg.ShiftEndTimeSnapshot,
		arg.IsCustom,
		arg.CreatedByEmployeeID,
		arg.StartDatetime,
		arg.EndDatetime,
	)
	var i CreateScheduleRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LocationID,
		&i.LocationShiftID,
		&i.ShiftNameSnapshot,
		&i.ShiftStartTimeSnapshot,
		&i.ShiftEndTimeSnapshot,
		&i.IsCustom,
		&i.StartDatetime,
		&i.EndDatetime,
		&i.CreatedByEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationName,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules
WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const getEmployeeNextShift = `-- name: GetEmployeeNextShift :one
SELECT
    s.id AS schedule_id,
    s.location_id,
    l.name AS location_name,
    l.street,
    l.house_number,
    l.house_number_addition,
    l.postal_code,
    l.city,
    s.start_datetime,
    s.end_datetime,
    s.is_custom,
    s.shift_name_snapshot AS shift_name,
    DATE(s.start_datetime AT TIME ZONE l.timezone) AS shift_date
FROM schedules s
JOIN location l ON l.id = s.location_id
LEFT JOIN location_shift ls ON ls.id = s.location_shift_id
WHERE s.employee_id = $1
  AND s.start_datetime > $2
ORDER BY s.start_datetime
LIMIT 1
`

type GetEmployeeNextShiftParams struct {
	EmployeeID uuid.UUID          `json:"employee_id"`
	Now        pgtype.Timestamptz `json:"now"`
}

type GetEmployeeNextShiftRow struct {
	ScheduleID          uuid.UUID          `json:"schedule_id"`
	LocationID          uuid.UUID          `json:"location_id"`
	LocationName        string             `json:"location_name"`
	Street              string             `json:"street"`
	HouseNumber         string             `json:"house_number"`
	HouseNumberAddition *string            `json:"house_number_addition"`
	PostalCode          string             `json:"postal_code"`
	City                string             `json:"city"`
	StartDatetime       pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime         pgtype.Timestamptz `json:"end_datetime"`
	IsCustom            bool               `json:"is_custom"`
	ShiftName           *string            `json:"shift_name"`
	ShiftDate           pgtype.Date        `json:"shift_date"`
}

func (q *Queries) GetEmployeeNextShift(ctx context.Context, arg GetEmployeeNextShiftParams) (GetEmployeeNextShiftRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeNextShift, arg.EmployeeID, arg.Now)
	var i GetEmployeeNextShiftRow
	err := row.Scan(
		&i.ScheduleID,
		&i.LocationID,
		&i.LocationName,
		&i.Street,
		&i.HouseNumber,
		&i.HouseNumberAddition,
		&i.PostalCode,
		&i.City,
		&i.StartDatetime,
		&i.EndDatetime,
		&i.IsCustom,
		&i.ShiftName,
		&i.ShiftDate,
	)
	return i, err
}

const getEmployeeScheduleManager = `-- name: GetEmployeeScheduleManager :one
SELECT
    mgr.first_name,
    mgr.last_name
FROM employee_profile employee
JOIN employee_profile mgr ON mgr.id = employee.manager_employee_id
WHERE employee.id = $1
LIMIT 1
`

type GetEmployeeScheduleManagerRow struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) GetEmployeeScheduleManager(ctx context.Context, employeeID uuid.UUID) (GetEmployeeScheduleManagerRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeScheduleManager, employeeID)
	var i GetEmployeeScheduleManagerRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}

const getEmployeeSchedules = `-- name: GetEmployeeSchedules :many
SELECT 
    s.id,
    s.start_datetime,
    s.end_datetime,
    s.location_id,
    l.name as location_name,
    'shift'::text as type
FROM schedules s
JOIN location l ON s.location_id = l.id
WHERE s.employee_id = $1
    AND s.start_datetime >= $2
    AND s.start_datetime < $3
ORDER BY s.start_datetime
`

type GetEmployeeSchedulesParams struct {
	EmployeeID  uuid.UUID          `json:"employee_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetEmployeeSchedulesRow struct {
	ID            uuid.UUID          `json:"id"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
	LocationID    uuid.UUID          `json:"location_id"`
	LocationName  string             `json:"location_name"`
	Type          string             `json:"type"`
}

func (q *Queries) GetEmployeeSchedules(ctx context.Context, arg GetEmployeeSchedulesParams) ([]GetEmployeeSchedulesRow, error) {
	rows, err := q.db.Query(ctx, getEmployeeSchedules, arg.EmployeeID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEmployeeSchedulesRow{}
	for rows.Next() {
		var i GetEmployeeSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.StartDatetime,
			&i.EndDatetime,
			&i.LocationID,
			&i.LocationName,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeSchedulesByDay = `-- name: GetEmployeeSchedulesByDay :many
SELECT
    s.id AS schedule_id,
    s.employee_id,
    s.location_id,
    l.name AS location_name,
    s.start_datetime,
    s.end_datetime,
    COALESCE(s.shift_name_snapshot, ls.shift_name, 'Custom Shift') AS shift_name,
    ls.id AS location_shift_id,
    s.is_custom
FROM schedules s
JOIN location l ON l.id = s.location_id
LEFT JOIN location_shift ls ON ls.id = s.location_shift_id
WHERE s.employee_id = $1
  AND DATE(s.start_datetime AT TIME ZONE l.timezone) = $2::date
ORDER BY s.start_datetime
`

type GetEmployeeSchedulesByDayParams struct {
	EmployeeID uuid.UUID   `json:"employee_id"`
	Date       pgtype.Date `json:"date"`
}

type GetEmployeeSchedulesByDayRow struct {
	ScheduleID      uuid.UUID          `json:"schedule_id"`
	EmployeeID      uuid.UUID          `json:"employee_id"`
	LocationID      uuid.UUID          `json:"location_id"`
	LocationName    string             `json:"location_name"`
	StartDatetime   pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime     pgtype.Timestamptz `json:"end_datetime"`
	ShiftName       string             `json:"shift_name"`
	LocationShiftID *uuid.UUID         `json:"location_shift_id"`
	IsCustom        bool               `json:"is_custom"`
}

func (q *Queries) GetEmployeeSchedulesByDay(ctx context.Context, arg GetEmployeeSchedulesByDayParams) ([]GetEmployeeSchedulesByDayRow, error) {
	rows, err := q.db.Query(ctx, getEmployeeSchedulesByDay, arg.EmployeeID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEmployeeSchedulesByDayRow{}
	for rows.Next() {
		var i GetEmployeeSchedulesByDayRow
		if err := rows.Scan(
			&i.ScheduleID,
			&i.EmployeeID,
			&i.LocationID,
			&i.LocationName,
			&i.StartDatetime,
			&i.EndDatetime,
			&i.ShiftName,
			&i.LocationShiftID,
			&i.IsCustom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeShiftOverviewStats = `-- name: GetEmployeeShiftOverviewStats :one
SELECT
    COUNT(*) FILTER (
        WHERE start_datetime >= $1
          AND start_datetime < $2
          AND start_datetime > $3
    )::bigint AS upcoming_count,
    COUNT(*) FILTER (
        WHERE start_datetime >= $1
          AND start_datetime < $2
          AND end_datetime <= $3
    )::bigint AS completed_count,
    COALESCE(SUM(
        EXTRACT(EPOCH FROM (end_datetime - start_datetime)) / 3600.0
    ) FILTER (
        WHERE start_datetime >= $4
          AND start_datetime < $5
          AND start_datetime > $3
    ), 0)::float8 AS planned_hours
FROM schedules
WHERE employee_id = $6
  AND start_datetime >= LEAST($4, $1)
  AND start_datetime < GREATEST($5, $2)
`

type GetEmployeeShiftOverviewStatsParams struct {
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
	Now        pgtype.Timestamptz `json:"now"`
	WeekStart  pgtype.Timestamptz `json:"week_start"`
	WeekEnd    pgtype.Timestamptz `json:"week_end"`
	EmployeeID uuid.UUID          `json:"employee_id"`
}

type GetEmployeeShiftOverviewStatsRow struct {
	UpcomingCount  int64   `json:"upcoming_count"`
	CompletedCount int64   `json:"completed_count"`
	PlannedHours   float64 `json:"planned_hours"`
}

func (q *Queries) GetEmployeeShiftOverviewStats(ctx context.Context, arg GetEmployeeShiftOverviewStatsParams) (GetEmployeeShiftOverviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeShiftOverviewStats,
		arg.MonthStart,
		arg.MonthEnd,
		arg.Now,
		arg.WeekStart,
		arg.WeekEnd,
		arg.EmployeeID,
	)
	var i GetEmployeeShiftOverviewStatsRow
	err := row.Scan(&i.UpcomingCount, &i.CompletedCount, &i.PlannedHours)
	return i, err
}

const getScheduleById = `-- name: GetScheduleById :one
SELECT s.id, s.employee_id, s.location_id, s.location_shift_id, s.shift_name_snapshot, s.shift_start_time_snapshot, s.shift_end_time_snapshot, s.is_custom, s.start_datetime, s.end_datetime, s.created_by_employee_id, s.created_at, s.updated_at,
    e.first_name AS employee_first_name,
    e.last_name AS employee_last_name,
    l.name AS location_name,
    COALESCE(s.shift_name_snapshot, ls.shift_name, 'Custom Shift') AS location_shift_name,
    ls.id AS location_shift_id
FROM schedules s
LEFT JOIN location_shift ls ON s.location_shift_id = ls.id
JOIN employee_profile e ON s.employee_id = e.id
JOIN location l ON s.location_id = l.id
WHERE s.id = $1
LIMIT 1
`

type GetScheduleByIdRow struct {
	ID                     uuid.UUID          `json:"id"`
	EmployeeID             uuid.UUID          `json:"employee_id"`
	LocationID             uuid.UUID          `json:"location_id"`
	LocationShiftID        *uuid.UUID         `json:"location_shift_id"`
	ShiftNameSnapshot      *string            `json:"shift_name_snapshot"`
	ShiftStartTimeSnapshot pgtype.Time        `json:"shift_start_time_snapshot"`
	ShiftEndTimeSnapshot   pgtype.Time        `json:"shift_end_time_snapshot"`
	IsCustom               bool               `json:"is_custom"`
	StartDatetime          pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime            pgtype.Timestamptz `json:"end_datetime"`
	CreatedByEmployeeID    uuid.UUID          `json:"created_by_employee_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	EmployeeFirstName      string             `json:"employee_first_name"`
	EmployeeLastName       string             `json:"employee_last_name"`
	LocationName           string             `json:"location_name"`
	LocationShiftName      string             `json:"location_shift_name"`
	LocationShiftID_2      *uuid.UUID         `json:"location_shift_id_2"`
}

func (q *Queries) GetScheduleById(ctx context.Context, id uuid.UUID) (GetScheduleByIdRow, error) {
	row := q.db.QueryRow(ctx, getScheduleById, id)
	var i GetScheduleByIdRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LocationID,
		&i.LocationShiftID,
		&i.ShiftNameSnapshot,
		&i.ShiftStartTimeSnapshot,
		&i.ShiftEndTimeSnapshot,
		&i.IsCustom,
		&i.StartDatetime,
		&i.EndDatetime,
		&i.CreatedByEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeFirstName,
		&i.EmployeeLastName,
		&i.LocationName,
		&i.LocationShiftName,
		&i.LocationShiftID_2,
	)
	return i, err
}

const getSchedulesByLocationInRange = `-- name: GetSchedulesByLocationInRange :many
SELECT 
  s.id AS shift_id,
  s.employee_id,
  s.location_id,
  s.start_datetime,
  s.end_datetime,
  s.is_custom,
  COALESCE(s.shift_name_snapshot, ls.shift_name, 'Custom Shift') AS shift_name,
  ls.id AS location_shift_id,
  DATE(s.start_datetime) AS day,
  e.first_name AS employee_first_name,
  e.last_name AS employee_last_name
FROM schedules s
LEFT JOIN location_shift ls 
  ON s.location_shift_id = ls.id
JOIN employee_profile e 
  ON s.employee_id = e.id
WHERE s.location_id = $1
  AND DATE(s.start_datetime) BETWEEN $2::date AND $3::date
ORDER BY day, s.start_datetime
`

type GetSchedulesByLocationInRangeParams struct {
	LocationID uuid.UUID   `json:"location_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

type GetSchedulesByLocationInRangeRow struct {
	ShiftID           uuid.UUID          `json:"shift_id"`
	EmployeeID        uuid.UUID          `json:"employee_id"`
	LocationID        uuid.UUID          `json:"location_id"`
	StartDatetime     pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime       pgtype.Timestamptz `json:"end_datetime"`
	IsCustom          bool               `json:"is_custom"`
	ShiftName         string             `json:"shift_name"`
	LocationShiftID   *uuid.UUID         `json:"location_shift_id"`
	Day               pgtype.Date        `json:"day"`
	EmployeeFirstName string             `json:"employee_first_name"`
	EmployeeLastName  string             `json:"employee_last_name"`
}

func (q *Queries) GetSchedulesByLocationInRange(ctx context.Context, arg GetSchedulesByLocationInRangeParams) ([]GetSchedulesByLocationInRangeRow, error) {
	rows, err := q.db.Query(ctx, getSchedulesByLocationInRange, arg.LocationID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSchedulesByLocationInRangeRow{}
	for rows.Next() {
		var i GetSchedulesByLocationInRangeRow
		if err := rows.Scan(
			&i.ShiftID,
			&i.EmployeeID,
			&i.LocationID,
			&i.StartDatetime,
			&i.EndDatetime,
			&i.IsCustom,
			&i.ShiftName,
			&i.LocationShiftID,
			&i.Day,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeMonthShiftCounts = `-- name: ListEmployeeMonthShiftCounts :many
SELECT
    EXTRACT(DAY FROM s.start_datetime AT TIME ZONE l.timezone)::int AS day,
    COUNT(*)::bigint AS shift_count
FROM schedules s
JOIN location l ON l.id = s.location_id
WHERE s.employee_id = $1
  AND s.start_datetime >= $2
  AND s.start_datetime < $3
GROUP BY day
ORDER BY day
`

type ListEmployeeMonthShiftCountsParams struct {
	EmployeeID uuid.UUID          `json:"employee_id"`
	MonthStart pgtype.Timestamptz `json:"month_start"`
	MonthEnd   pgtype.Timestamptz `json:"month_end"`
}

type ListEmployeeMonthShiftCountsRow struct {
	Day        int32 `json:"day"`
	ShiftCount int64 `json:"shift_count"`
}

func (q *Queries) ListEmployeeMonthShiftCounts(ctx context.Context, arg ListEmployeeMonthShiftCountsParams) ([]ListEmployeeMonthShiftCountsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeMonthShiftCounts, arg.EmployeeID, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeMonthShiftCountsRow{}
	for rows.Next() {
		var i ListEmployeeMonthShiftCountsRow
		if err := rows.Scan(&i.Day, &i.ShiftCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeePastShiftsPaginated = `-- name: ListEmployeePastShiftsPaginated :many
SELECT
    s.id AS schedule_id,
    s.location_id,
    l.name AS location_name,
    l.street,
    l.house_number,
    l.house_number_addition,
    l.postal_code,
    l.city,
    s.start_datetime,
    s.end_datetime,
    s.is_custom,
    COALESCE(s.shift_name_snapshot, ls.shift_name, 'Custom Shift') AS shift_name,
    DATE(s.start_datetime AT TIME ZONE l.timezone) AS shift_date,
    COUNT(*) OVER() AS total_count
FROM schedules s
JOIN location l ON l.id = s.location_id
LEFT JOIN location_shift ls ON ls.id = s.location_shift_id
WHERE s.employee_id = $1
  AND s.start_datetime < $2
ORDER BY s.start_datetime DESC
LIMIT $4 OFFSET $3
`

type ListEmployeePastShiftsPaginatedParams struct {
	EmployeeID  uuid.UUID          `json:"employee_id"`
	Now         pgtype.Timestamptz `json:"now"`
	OffsetCount int32              `json:"offset_count"`
	LimitCount  int32              `json:"limit_count"`
}

type ListEmployeePastShiftsPaginatedRow struct {
	ScheduleID          uuid.UUID          `json:"schedule_id"`
	LocationID          uuid.UUID          `json:"location_id"`
	LocationName        string             `json:"location_name"`
	Street              string             `json:"street"`
	HouseNumber         string             `json:"house_number"`
	HouseNumberAddition *string            `json:"house_number_addition"`
	PostalCode          string             `json:"postal_code"`
	City                string             `json:"city"`
	StartDatetime       pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime         pgtype.Timestamptz `json:"end_datetime"`
	IsCustom            bool               `json:"is_custom"`
	ShiftName           string             `json:"shift_name"`
	ShiftDate           pgtype.Date        `json:"shift_date"`
	TotalCount          int64              `json:"total_count"`
}

func (q *Queries) ListEmployeePastShiftsPaginated(ctx context.Context, arg ListEmployeePastShiftsPaginatedParams) ([]ListEmployeePastShiftsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listEmployeePastShiftsPaginated,
		arg.EmployeeID,
		arg.Now,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeePastShiftsPaginatedRow{}
	for rows.Next() {
		var i ListEmployeePastShiftsPaginatedRow
		if err := rows.Scan(
			&i.ScheduleID,
			&i.LocationID,
			&i.LocationName,
			&i.Street,
			&i.HouseNumber,
			&i.HouseNumberAddition,
			&i.PostalCode,
			&i.City,
			&i.StartDatetime,
			&i.EndDatetime,
			&i.IsCustom,
			&i.ShiftName,
			&i.ShiftDate,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeShiftColleagues = `-- name: ListEmployeeShiftColleagues :many
SELECT
    colleague.id AS employee_id,
    colleague.first_name,
    colleague.last_name
FROM schedules base
JOIN schedules shared
  ON shared.location_id = base.location_id
 AND shared.start_datetime = base.start_datetime
 AND shared.end_datetime = base.end_datetime
 AND (
    shared.location_shift_id IS NOT DISTINCT FROM base.location_shift_id
 )
JOIN employee_profile colleague ON colleague.id = shared.employee_id
WHERE base.id = $1
  AND shared.employee_id <> $2
ORDER BY colleague.first_name, colleague.last_name
`

type ListEmployeeShiftColleaguesParams struct {
	ScheduleID uuid.UUID `json:"schedule_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

type ListEmployeeShiftColleaguesRow struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
}

func (q *Queries) ListEmployeeShiftColleagues(ctx context.Context, arg ListEmployeeShiftColleaguesParams) ([]ListEmployeeShiftColleaguesRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeShiftColleagues, arg.ScheduleID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeShiftColleaguesRow{}
	for rows.Next() {
		var i ListEmployeeShiftColleaguesRow
		if err := rows.Scan(&i.EmployeeID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeUpcomingShifts = `-- name: ListEmployeeUpcomingShifts :many
SELECT
    s.id AS schedule_id,
    s.location_id,
    l.name AS location_name,
    l.street,
    l.house_number,
    l.house_number_addition,
    l.postal_code,
    l.city,
    s.start_datetime,
    s.end_datetime,
    s.is_custom,
    COALESCE(s.shift_name_snapshot, ls.shift_name, 'Custom Shift') AS shift_name,
    DATE(s.start_datetime AT TIME ZONE l.timezone) AS shift_date
FROM schedules s
JOIN location l ON l.id = s.location_id
LEFT JOIN location_shift ls ON ls.id = s.location_shift_id
WHERE s.employee_id = $1
  AND s.start_datetime > $2
  AND s.start_datetime < $3
ORDER BY s.start_datetime
`

type ListEmployeeUpcomingShiftsParams struct {
	EmployeeID uuid.UUID          `json:"employee_id"`
	Now        pgtype.Timestamptz `json:"now"`
	WindowEnd  pgtype.Timestamptz `json:"window_end"`
}

type ListEmployeeUpcomingShiftsRow struct {
	ScheduleID          uuid.UUID          `json:"schedule_id"`
	LocationID          uuid.UUID          `json:"location_id"`
	LocationName        string             `json:"location_name"`
	Street              string             `json:"street"`
	HouseNumber         string             `json:"house_number"`
	HouseNumberAddition *string            `json:"house_number_addition"`
	PostalCode          string             `json:"postal_code"`
	City                string             `json:"city"`
	StartDatetime       pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime         pgtype.Timestamptz `json:"end_datetime"`
	IsCustom            bool               `json:"is_custom"`
	ShiftName           string             `json:"shift_name"`
	ShiftDate           pgtype.Date        `json:"shift_date"`
}

func (q *Queries) ListEmployeeUpcomingShifts(ctx context.Context, arg ListEmployeeUpcomingShiftsParams) ([]ListEmployeeUpcomingShiftsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeUpcomingShifts, arg.EmployeeID, arg.Now, arg.WindowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeUpcomingShiftsRow{}
	for rows.Next() {
		var i ListEmployeeUpcomingShiftsRow
		if err := rows.Scan(
			&i.ScheduleID,
			&i.LocationID,
			&i.LocationName,
			&i.Street,
			&i.HouseNumber,
			&i.HouseNumberAddition,
			&i.PostalCode,
			&i.City,
			&i.StartDatetime,
			&i.EndDatetime,
			&i.IsCustom,
			&i.ShiftName,
			&i.ShiftDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeWeekShiftCounts = `-- name: ListEmployeeWeekShiftCounts :many
SELECT
    DATE(s.start_datetime AT TIME ZONE l.timezone) AS day,
    COUNT(*)::bigint AS shift_count
FROM schedules s
JOIN location l ON l.id = s.location_id
WHERE s.employee_id = $1
  AND s.start_datetime >= $2
  AND s.start_datetime < $3
GROUP BY day
ORDER BY day
`

type ListEmployeeWeekShiftCountsParams struct {
	EmployeeID uuid.UUID          `json:"employee_id"`
	WeekStart  pgtype.Timestamptz `json:"week_start"`
	WeekEnd    pgtype.Timestamptz `json:"week_end"`
}

type ListEmployeeWeekShiftCountsRow struct {
	Day        pgtype.Date `json:"day"`
	ShiftCount int64       `json:"shift_count"`
}

func (q *Queries) ListEmployeeWeekShiftCounts(ctx context.Context, arg ListEmployeeWeekShiftCountsParams) ([]ListEmployeeWeekShiftCountsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeWeekShiftCounts, arg.EmployeeID, arg.WeekStart, arg.WeekEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeWeekShiftCountsRow{}
	for rows.Next() {
		var i ListEmployeeWeekShiftCountsRow
		if err := rows.Scan(&i.Day, &i.ShiftCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftColleaguesByScheduleIDs = `-- name: ListShiftColleaguesByScheduleIDs :many
SELECT
    s.id AS schedule_id,
    colleague.id AS employee_id,
    colleague.first_name,
    colleague.last_name
FROM schedules s
JOIN schedules shared
  ON shared.location_id = s.location_id
 AND shared.start_datetime = s.start_datetime
 AND shared.end_datetime = s.end_datetime
 AND (shared.location_shift_id IS NOT DISTINCT FROM s.location_shift_id)
JOIN employee_profile colleague ON colleague.id = shared.employee_id
WHERE s.id = ANY($1::uuid[])
  AND shared.employee_id <> $2
ORDER BY s.id, colleague.first_name, colleague.last_name
`

type ListShiftColleaguesByScheduleIDsParams struct {
	ScheduleIds []uuid.UUID `json:"schedule_ids"`
	EmployeeID  uuid.UUID   `json:"employee_id"`
}

type ListShiftColleaguesByScheduleIDsRow struct {
	ScheduleID uuid.UUID `json:"schedule_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
}

func (q *Queries) ListShiftColleaguesByScheduleIDs(ctx context.Context, arg ListShiftColleaguesByScheduleIDsParams) ([]ListShiftColleaguesByScheduleIDsRow, error) {
	rows, err := q.db.Query(ctx, listShiftColleaguesByScheduleIDs, arg.ScheduleIds, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShiftColleaguesByScheduleIDsRow{}
	for rows.Next() {
		var i ListShiftColleaguesByScheduleIDsRow
		if err := rows.Scan(
			&i.ScheduleID,
			&i.EmployeeID,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
WITH updated_schedule AS (
    UPDATE schedules
    SET
        employee_id = $2,
        location_id = $3,
        location_shift_id = $4,
        start_datetime = $5,
        end_datetime = $6,
        shift_name_snapshot = $7,
        shift_start_time_snapshot = $8,
        shift_end_time_snapshot = $9,
        is_custom = $10,
        updated_at = NOW()
    WHERE schedules.id = $1
    RETURNING id, employee_id, location_id, location_shift_id, shift_name_snapshot, shift_start_time_snapshot, shift_end_time_snapshot, is_custom, start_datetime, end_datetime, created_by_employee_id, created_at, updated_at
)
SELECT 
    s.id, s.employee_id, s.location_id, s.location_shift_id, s.shift_name_snapshot, s.shift_start_time_snapshot, s.shift_end_time_snapshot, s.is_custom, s.start_datetime, s.end_datetime, s.created_by_employee_id, s.created_at, s.updated_at,
    l.name as location_name
FROM updated_schedule s
JOIN location l ON s.location_id = l.id
`

type UpdateScheduleParams struct {
	ID                     uuid.UUID          `json:"id"`
	EmployeeID             uuid.UUID          `json:"employee_id"`
	LocationID             uuid.UUID          `json:"location_id"`
	LocationShiftID        *uuid.UUID         `json:"location_shift_id"`
	StartDatetime          pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime            pgtype.Timestamptz `json:"end_datetime"`
	ShiftNameSnapshot      *string            `json:"shift_name_snapshot"`
	ShiftStartTimeSnapshot pgtype.Time        `json:"shift_start_time_snapshot"`
	ShiftEndTimeSnapshot   pgtype.Time        `json:"shift_end_time_snapshot"`
	IsCustom               bool               `json:"is_custom"`
}

type UpdateScheduleRow struct {
	ID                     uuid.UUID          `json:"id"`
	EmployeeID             uuid.UUID          `json:"employee_id"`
	LocationID             uuid.UUID          `json:"location_id"`
	LocationShiftID        *uuid.UUID         `json:"location_shift_id"`
	ShiftNameSnapshot      *string            `json:"shift_name_snapshot"`
	ShiftStartTimeSnapshot pgtype.Time        `json:"shift_start_time_snapshot"`
	ShiftEndTimeSnapshot   pgtype.Time        `json:"shift_end_time_snapshot"`
	IsCustom               bool               `json:"is_custom"`
	StartDatetime          pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime            pgtype.Timestamptz `json:"end_datetime"`
	CreatedByEmployeeID    uuid.UUID          `json:"created_by_employee_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	LocationName           string             `json:"location_name"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (UpdateScheduleRow, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.EmployeeID,
		arg.LocationID,
		arg.LocationShiftID,
		arg.StartDatetime,
		arg.EndDatetime,
		arg.ShiftNameSnapshot,
		arg.ShiftStartTimeSnapshot,
		arg.ShiftEndTimeSnapshot,
		arg.IsCustom,
	)
	var i UpdateScheduleRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LocationID,
		&i.LocationShiftID,
		&i.ShiftNameSnapshot,
		&i.ShiftStartTimeSnapshot,
		&i.ShiftEndTimeSnapshot,
		&i.IsCustom,
		&i.StartDatetime,
		&i.EndDatetime,
		&i.CreatedByEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationName,
	)
	return i, err
}
