// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppOrganizationProfile = `-- name: GetAppOrganizationProfile :one
SELECT
    name,
    default_timezone,
    email,
    phone_number,
    website,
    hq_street,
    hq_house_number,
    hq_house_number_addition,
    hq_postal_code,
    hq_city,
    created_at,
    updated_at
FROM app_organization_profile
WHERE singleton = TRUE
`

type GetAppOrganizationProfileRow struct {
	Name                  string             `json:"name"`
	DefaultTimezone       string             `json:"default_timezone"`
	Email                 *string            `json:"email"`
	PhoneNumber           *string            `json:"phone_number"`
	Website               *string            `json:"website"`
	HqStreet              *string            `json:"hq_street"`
	HqHouseNumber         *string            `json:"hq_house_number"`
	HqHouseNumberAddition *string            `json:"hq_house_number_addition"`
	HqPostalCode          *string            `json:"hq_postal_code"`
	HqCity                *string            `json:"hq_city"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAppOrganizationProfile(ctx context.Context) (GetAppOrganizationProfileRow, error) {
	row := q.db.QueryRow(ctx, getAppOrganizationProfile)
	var i GetAppOrganizationProfileRow
	err := row.Scan(
		&i.Name,
		&i.DefaultTimezone,
		&i.Email,
		&i.PhoneNumber,
		&i.Website,
		&i.HqStreet,
		&i.HqHouseNumber,
		&i.HqHouseNumberAddition,
		&i.HqPostalCode,
		&i.HqCity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppOrganizationProfile = `-- name: UpdateAppOrganizationProfile :one
UPDATE app_organization_profile
SET
    name = COALESCE($1, name),
    default_timezone = COALESCE($2, default_timezone),
    email = COALESCE($3, email),
    phone_number = COALESCE($4, phone_number),
    website = COALESCE($5, website),
    hq_street = COALESCE($6, hq_street),
    hq_house_number = COALESCE($7, hq_house_number),
    hq_house_number_addition = COALESCE(
        $8,
        hq_house_number_addition
    ),
    hq_postal_code = COALESCE($9, hq_postal_code),
    hq_city = COALESCE($10, hq_city),
    updated_at = NOW()
WHERE singleton = TRUE
RETURNING
    name,
    default_timezone,
    email,
    phone_number,
    website,
    hq_street,
    hq_house_number,
    hq_house_number_addition,
    hq_postal_code,
    hq_city,
    created_at,
    updated_at
`

type UpdateAppOrganizationProfileParams struct {
	Name                  *string `json:"name"`
	DefaultTimezone       *string `json:"default_timezone"`
	Email                 *string `json:"email"`
	PhoneNumber           *string `json:"phone_number"`
	Website               *string `json:"website"`
	HqStreet              *string `json:"hq_street"`
	HqHouseNumber         *string `json:"hq_house_number"`
	HqHouseNumberAddition *string `json:"hq_house_number_addition"`
	HqPostalCode          *string `json:"hq_postal_code"`
	HqCity                *string `json:"hq_city"`
}

type UpdateAppOrganizationProfileRow struct {
	Name                  string             `json:"name"`
	DefaultTimezone       string             `json:"default_timezone"`
	Email                 *string            `json:"email"`
	PhoneNumber           *string            `json:"phone_number"`
	Website               *string            `json:"website"`
	HqStreet              *string            `json:"hq_street"`
	HqHouseNumber         *string            `json:"hq_house_number"`
	HqHouseNumberAddition *string            `json:"hq_house_number_addition"`
	HqPostalCode          *string            `json:"hq_postal_code"`
	HqCity                *string            `json:"hq_city"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAppOrganizationProfile(ctx context.Context, arg UpdateAppOrganizationProfileParams) (UpdateAppOrganizationProfileRow, error) {
	row := q.db.QueryRow(ctx, updateAppOrganizationProfile,
		arg.Name,
		arg.DefaultTimezone,
		arg.Email,
		arg.PhoneNumber,
		arg.Website,
		arg.HqStreet,
		arg.HqHouseNumber,
		arg.HqHouseNumberAddition,
		arg.HqPostalCode,
		arg.HqCity,
	)
	var i UpdateAppOrganizationProfileRow
	err := row.Scan(
		&i.Name,
		&i.DefaultTimezone,
		&i.Email,
		&i.PhoneNumber,
		&i.Website,
		&i.HqStreet,
		&i.HqHouseNumber,
		&i.HqHouseNumberAddition,
		&i.HqPostalCode,
		&i.HqCity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
