// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sign_document.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSignDocument = `-- name: CancelSignDocument :one
UPDATE sign_documents
SET status = 'cancelled', cancelled_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status IN ('draft', 'sent', 'partially_signed')
RETURNING id, title, source_attachment_id, source_file_key, signed_file_key, status, created_by_employee_id, related_entity_type, related_entity_id, expires_at, sent_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) CancelSignDocument(ctx context.Context, id uuid.UUID) (SignDocument, error) {
	row := q.db.QueryRow(ctx, cancelSignDocument, id)
	var i SignDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SourceAttachmentID,
		&i.SourceFileKey,
		&i.SignedFileKey,
		&i.Status,
		&i.CreatedByEmployeeID,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.ExpiresAt,
		&i.SentAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUnsignedPriorSignDocumentRecipients = `-- name: CountUnsignedPriorSignDocumentRecipients :one
SELECT COUNT(*)::int
FROM sign_document_recipients current_recipient
JOIN sign_document_recipients prior_recipient
  ON prior_recipient.document_id = current_recipient.document_id
 AND prior_recipient.signing_order < current_recipient.signing_order
WHERE current_recipient.id = $1
  AND prior_recipient.status <> 'signed'
`

func (q *Queries) CountUnsignedPriorSignDocumentRecipients(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnsignedPriorSignDocumentRecipients, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnsignedSignDocumentRecipients = `-- name: CountUnsignedSignDocumentRecipients :one
SELECT COUNT(*)::int
FROM sign_document_recipients
WHERE document_id = $1 AND status <> 'signed'
`

func (q *Queries) CountUnsignedSignDocumentRecipients(ctx context.Context, documentID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnsignedSignDocumentRecipients, documentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createEmployeeSignatureProfile = `-- name: CreateEmployeeSignatureProfile :one
WITH reset_default AS (
    UPDATE employee_signature_profiles
    SET is_default = FALSE, updated_at = CURRENT_TIMESTAMP
    WHERE employee_signature_profiles.employee_id = $1
      AND $5::boolean
)
INSERT INTO employee_signature_profiles (
    employee_id,
    type,
    typed_name,
    image_file_key,
    is_default
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, employee_id, type, typed_name, image_file_key, is_default, created_at, updated_at
`

type CreateEmployeeSignatureProfileParams struct {
	EmployeeID   uuid.UUID                 `json:"employee_id"`
	Type         EmployeeSignatureTypeEnum `json:"type"`
	TypedName    *string                   `json:"typed_name"`
	ImageFileKey *string                   `json:"image_file_key"`
	IsDefault    bool                      `json:"is_default"`
}

func (q *Queries) CreateEmployeeSignatureProfile(ctx context.Context, arg CreateEmployeeSignatureProfileParams) (EmployeeSignatureProfile, error) {
	row := q.db.QueryRow(ctx, createEmployeeSignatureProfile,
		arg.EmployeeID,
		arg.Type,
		arg.TypedName,
		arg.ImageFileKey,
		arg.IsDefault,
	)
	var i EmployeeSignatureProfile
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Type,
		&i.TypedName,
		&i.ImageFileKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSignDocument = `-- name: CreateSignDocument :one
INSERT INTO sign_documents (
    title,
    source_attachment_id,
    source_file_key,
    created_by_employee_id,
    related_entity_type,
    related_entity_id,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, source_attachment_id, source_file_key, signed_file_key, status, created_by_employee_id, related_entity_type, related_entity_id, expires_at, sent_at, completed_at, cancelled_at, created_at, updated_at
`

type CreateSignDocumentParams struct {
	Title               string             `json:"title"`
	SourceAttachmentID  uuid.UUID          `json:"source_attachment_id"`
	SourceFileKey       string             `json:"source_file_key"`
	CreatedByEmployeeID uuid.UUID          `json:"created_by_employee_id"`
	RelatedEntityType   *string            `json:"related_entity_type"`
	RelatedEntityID     *uuid.UUID         `json:"related_entity_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSignDocument(ctx context.Context, arg CreateSignDocumentParams) (SignDocument, error) {
	row := q.db.QueryRow(ctx, createSignDocument,
		arg.Title,
		arg.SourceAttachmentID,
		arg.SourceFileKey,
		arg.CreatedByEmployeeID,
		arg.RelatedEntityType,
		arg.RelatedEntityID,
		arg.ExpiresAt,
	)
	var i SignDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SourceAttachmentID,
		&i.SourceFileKey,
		&i.SignedFileKey,
		&i.Status,
		&i.CreatedByEmployeeID,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.ExpiresAt,
		&i.SentAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSignDocumentEvent = `-- name: CreateSignDocumentEvent :one
INSERT INTO sign_document_events (
    document_id,
    recipient_id,
    actor_employee_id,
    event,
    ip_address,
    user_agent,
    metadata
)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, '{}'::jsonb))
RETURNING id, document_id, recipient_id, actor_employee_id, event, ip_address, user_agent, metadata, created_at
`

type CreateSignDocumentEventParams struct {
	DocumentID      uuid.UUID             `json:"document_id"`
	RecipientID     *uuid.UUID            `json:"recipient_id"`
	ActorEmployeeID *uuid.UUID            `json:"actor_employee_id"`
	Event           SignDocumentEventEnum `json:"event"`
	IpAddress       *string               `json:"ip_address"`
	UserAgent       *string               `json:"user_agent"`
	Column7         interface{}           `json:"column_7"`
}

func (q *Queries) CreateSignDocumentEvent(ctx context.Context, arg CreateSignDocumentEventParams) (SignDocumentEvent, error) {
	row := q.db.QueryRow(ctx, createSignDocumentEvent,
		arg.DocumentID,
		arg.RecipientID,
		arg.ActorEmployeeID,
		arg.Event,
		arg.IpAddress,
		arg.UserAgent,
		arg.Column7,
	)
	var i SignDocumentEvent
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RecipientID,
		&i.ActorEmployeeID,
		&i.Event,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createSignDocumentField = `-- name: CreateSignDocumentField :one
INSERT INTO sign_document_fields (
    document_id,
    recipient_id,
    type,
    page_number,
    x,
    y,
    width,
    height,
    required,
    label
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, document_id, recipient_id, type, page_number, x, y, width, height, required, label, value, created_at, updated_at
`

type CreateSignDocumentFieldParams struct {
	DocumentID  uuid.UUID                 `json:"document_id"`
	RecipientID uuid.UUID                 `json:"recipient_id"`
	Type        SignDocumentFieldTypeEnum `json:"type"`
	PageNumber  int32                     `json:"page_number"`
	X           float64                   `json:"x"`
	Y           float64                   `json:"y"`
	Width       float64                   `json:"width"`
	Height      float64                   `json:"height"`
	Required    bool                      `json:"required"`
	Label       *string                   `json:"label"`
}

func (q *Queries) CreateSignDocumentField(ctx context.Context, arg CreateSignDocumentFieldParams) (SignDocumentField, error) {
	row := q.db.QueryRow(ctx, createSignDocumentField,
		arg.DocumentID,
		arg.RecipientID,
		arg.Type,
		arg.PageNumber,
		arg.X,
		arg.Y,
		arg.Width,
		arg.Height,
		arg.Required,
		arg.Label,
	)
	var i SignDocumentField
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RecipientID,
		&i.Type,
		&i.PageNumber,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Required,
		&i.Label,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSignDocumentRecipient = `-- name: CreateSignDocumentRecipient :one
INSERT INTO sign_document_recipients (
    document_id,
    employee_id,
    name,
    email,
    signing_order
)
SELECT
    $1,
    ep.id,
    NULLIF(TRIM(CONCAT_WS(' ', ep.first_name, ep.last_name)), ''),
    cu.email,
    $2
FROM employee_profile ep
LEFT JOIN custom_user cu ON cu.id = ep.user_id
WHERE ep.id = $3
RETURNING id, document_id, employee_id, name, email, signing_order, status, viewed_at, signed_at, declined_at, decline_reason, created_at, updated_at
`

type CreateSignDocumentRecipientParams struct {
	DocumentID   uuid.UUID `json:"document_id"`
	SigningOrder int32     `json:"signing_order"`
	EmployeeID   uuid.UUID `json:"employee_id"`
}

func (q *Queries) CreateSignDocumentRecipient(ctx context.Context, arg CreateSignDocumentRecipientParams) (SignDocumentRecipient, error) {
	row := q.db.QueryRow(ctx, createSignDocumentRecipient, arg.DocumentID, arg.SigningOrder, arg.EmployeeID)
	var i SignDocumentRecipient
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.SigningOrder,
		&i.Status,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSignDocumentSignature = `-- name: CreateSignDocumentSignature :one
INSERT INTO sign_document_signatures (
    document_id,
    recipient_id,
    employee_id,
    signature_profile_id,
    signature_text,
    signature_image_file_key,
    consent_text,
    ip_address,
    user_agent,
    signature_hash
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, document_id, recipient_id, employee_id, signature_profile_id, signature_text, signature_image_file_key, consent_text, ip_address, user_agent, signature_hash, signed_at
`

type CreateSignDocumentSignatureParams struct {
	DocumentID            uuid.UUID  `json:"document_id"`
	RecipientID           uuid.UUID  `json:"recipient_id"`
	EmployeeID            uuid.UUID  `json:"employee_id"`
	SignatureProfileID    *uuid.UUID `json:"signature_profile_id"`
	SignatureText         *string    `json:"signature_text"`
	SignatureImageFileKey *string    `json:"signature_image_file_key"`
	ConsentText           string     `json:"consent_text"`
	IpAddress             *string    `json:"ip_address"`
	UserAgent             *string    `json:"user_agent"`
	SignatureHash         string     `json:"signature_hash"`
}

func (q *Queries) CreateSignDocumentSignature(ctx context.Context, arg CreateSignDocumentSignatureParams) (SignDocumentSignature, error) {
	row := q.db.QueryRow(ctx, createSignDocumentSignature,
		arg.DocumentID,
		arg.RecipientID,
		arg.EmployeeID,
		arg.SignatureProfileID,
		arg.SignatureText,
		arg.SignatureImageFileKey,
		arg.ConsentText,
		arg.IpAddress,
		arg.UserAgent,
		arg.SignatureHash,
	)
	var i SignDocumentSignature
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RecipientID,
		&i.EmployeeID,
		&i.SignatureProfileID,
		&i.SignatureText,
		&i.SignatureImageFileKey,
		&i.ConsentText,
		&i.IpAddress,
		&i.UserAgent,
		&i.SignatureHash,
		&i.SignedAt,
	)
	return i, err
}

const deleteSignDocumentFields = `-- name: DeleteSignDocumentFields :exec
DELETE FROM sign_document_fields
WHERE document_id = $1
`

func (q *Queries) DeleteSignDocumentFields(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSignDocumentFields, documentID)
	return err
}

const getDefaultEmployeeSignatureProfile = `-- name: GetDefaultEmployeeSignatureProfile :one
SELECT id, employee_id, type, typed_name, image_file_key, is_default, created_at, updated_at
FROM employee_signature_profiles
WHERE employee_id = $1 AND is_default
LIMIT 1
`

func (q *Queries) GetDefaultEmployeeSignatureProfile(ctx context.Context, employeeID uuid.UUID) (EmployeeSignatureProfile, error) {
	row := q.db.QueryRow(ctx, getDefaultEmployeeSignatureProfile, employeeID)
	var i EmployeeSignatureProfile
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Type,
		&i.TypedName,
		&i.ImageFileKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignDocumentByID = `-- name: GetSignDocumentByID :one
SELECT id, title, source_attachment_id, source_file_key, signed_file_key, status, created_by_employee_id, related_entity_type, related_entity_id, expires_at, sent_at, completed_at, cancelled_at, created_at, updated_at
FROM sign_documents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSignDocumentByID(ctx context.Context, id uuid.UUID) (SignDocument, error) {
	row := q.db.QueryRow(ctx, getSignDocumentByID, id)
	var i SignDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SourceAttachmentID,
		&i.SourceFileKey,
		&i.SignedFileKey,
		&i.Status,
		&i.CreatedByEmployeeID,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.ExpiresAt,
		&i.SentAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSignDocumentRecipientForEmployee = `-- name: GetSignDocumentRecipientForEmployee :one
SELECT id, document_id, employee_id, name, email, signing_order, status, viewed_at, signed_at, declined_at, decline_reason, created_at, updated_at
FROM sign_document_recipients
WHERE document_id = $1 AND employee_id = $2
LIMIT 1
`

type GetSignDocumentRecipientForEmployeeParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

func (q *Queries) GetSignDocumentRecipientForEmployee(ctx context.Context, arg GetSignDocumentRecipientForEmployeeParams) (SignDocumentRecipient, error) {
	row := q.db.QueryRow(ctx, getSignDocumentRecipientForEmployee, arg.DocumentID, arg.EmployeeID)
	var i SignDocumentRecipient
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.SigningOrder,
		&i.Status,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSignDocumentEvents = `-- name: ListSignDocumentEvents :many
SELECT id, document_id, recipient_id, actor_employee_id, event, ip_address, user_agent, metadata, created_at
FROM sign_document_events
WHERE document_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSignDocumentEvents(ctx context.Context, documentID uuid.UUID) ([]SignDocumentEvent, error) {
	rows, err := q.db.Query(ctx, listSignDocumentEvents, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignDocumentEvent{}
	for rows.Next() {
		var i SignDocumentEvent
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.RecipientID,
			&i.ActorEmployeeID,
			&i.Event,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignDocumentFields = `-- name: ListSignDocumentFields :many
SELECT id, document_id, recipient_id, type, page_number, x, y, width, height, required, label, value, created_at, updated_at
FROM sign_document_fields
WHERE document_id = $1
ORDER BY page_number ASC, created_at ASC
`

func (q *Queries) ListSignDocumentFields(ctx context.Context, documentID uuid.UUID) ([]SignDocumentField, error) {
	rows, err := q.db.Query(ctx, listSignDocumentFields, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignDocumentField{}
	for rows.Next() {
		var i SignDocumentField
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.RecipientID,
			&i.Type,
			&i.PageNumber,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Required,
			&i.Label,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignDocumentFieldsForRecipient = `-- name: ListSignDocumentFieldsForRecipient :many
SELECT id, document_id, recipient_id, type, page_number, x, y, width, height, required, label, value, created_at, updated_at
FROM sign_document_fields
WHERE document_id = $1 AND recipient_id = $2
ORDER BY page_number ASC, created_at ASC
`

type ListSignDocumentFieldsForRecipientParams struct {
	DocumentID  uuid.UUID `json:"document_id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) ListSignDocumentFieldsForRecipient(ctx context.Context, arg ListSignDocumentFieldsForRecipientParams) ([]SignDocumentField, error) {
	rows, err := q.db.Query(ctx, listSignDocumentFieldsForRecipient, arg.DocumentID, arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignDocumentField{}
	for rows.Next() {
		var i SignDocumentField
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.RecipientID,
			&i.Type,
			&i.PageNumber,
			&i.X,
			&i.Y,
			&i.Width,
			&i.Height,
			&i.Required,
			&i.Label,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignDocumentRecipients = `-- name: ListSignDocumentRecipients :many
SELECT id, document_id, employee_id, name, email, signing_order, status, viewed_at, signed_at, declined_at, decline_reason, created_at, updated_at
FROM sign_document_recipients
WHERE document_id = $1
ORDER BY signing_order ASC, created_at ASC
`

func (q *Queries) ListSignDocumentRecipients(ctx context.Context, documentID uuid.UUID) ([]SignDocumentRecipient, error) {
	rows, err := q.db.Query(ctx, listSignDocumentRecipients, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignDocumentRecipient{}
	for rows.Next() {
		var i SignDocumentRecipient
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.EmployeeID,
			&i.Name,
			&i.Email,
			&i.SigningOrder,
			&i.Status,
			&i.ViewedAt,
			&i.SignedAt,
			&i.DeclinedAt,
			&i.DeclineReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignDocumentSignatures = `-- name: ListSignDocumentSignatures :many
SELECT id, document_id, recipient_id, employee_id, signature_profile_id, signature_text, signature_image_file_key, consent_text, ip_address, user_agent, signature_hash, signed_at
FROM sign_document_signatures
WHERE document_id = $1
ORDER BY signed_at ASC
`

func (q *Queries) ListSignDocumentSignatures(ctx context.Context, documentID uuid.UUID) ([]SignDocumentSignature, error) {
	rows, err := q.db.Query(ctx, listSignDocumentSignatures, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignDocumentSignature{}
	for rows.Next() {
		var i SignDocumentSignature
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.RecipientID,
			&i.EmployeeID,
			&i.SignatureProfileID,
			&i.SignatureText,
			&i.SignatureImageFileKey,
			&i.ConsentText,
			&i.IpAddress,
			&i.UserAgent,
			&i.SignatureHash,
			&i.SignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignDocumentsByCreator = `-- name: ListSignDocumentsByCreator :many
SELECT id, title, source_attachment_id, source_file_key, signed_file_key, status, created_by_employee_id, related_entity_type, related_entity_id, expires_at, sent_at, completed_at, cancelled_at, created_at, updated_at
FROM sign_documents
WHERE created_by_employee_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSignDocumentsByCreatorParams struct {
	CreatedByEmployeeID uuid.UUID `json:"created_by_employee_id"`
	Limit               int32     `json:"limit"`
	Offset              int32     `json:"offset"`
}

func (q *Queries) ListSignDocumentsByCreator(ctx context.Context, arg ListSignDocumentsByCreatorParams) ([]SignDocument, error) {
	rows, err := q.db.Query(ctx, listSignDocumentsByCreator, arg.CreatedByEmployeeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignDocument{}
	for rows.Next() {
		var i SignDocument
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SourceAttachmentID,
			&i.SourceFileKey,
			&i.SignedFileKey,
			&i.Status,
			&i.CreatedByEmployeeID,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.ExpiresAt,
			&i.SentAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignDocumentsForEmployee = `-- name: ListSignDocumentsForEmployee :many
SELECT sd.id, sd.title, sd.source_attachment_id, sd.source_file_key, sd.signed_file_key, sd.status, sd.created_by_employee_id, sd.related_entity_type, sd.related_entity_id, sd.expires_at, sd.sent_at, sd.completed_at, sd.cancelled_at, sd.created_at, sd.updated_at
FROM sign_documents sd
JOIN sign_document_recipients sdr ON sdr.document_id = sd.id
WHERE sdr.employee_id = $1
ORDER BY sd.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSignDocumentsForEmployeeParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListSignDocumentsForEmployee(ctx context.Context, arg ListSignDocumentsForEmployeeParams) ([]SignDocument, error) {
	rows, err := q.db.Query(ctx, listSignDocumentsForEmployee, arg.EmployeeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignDocument{}
	for rows.Next() {
		var i SignDocument
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SourceAttachmentID,
			&i.SourceFileKey,
			&i.SignedFileKey,
			&i.Status,
			&i.CreatedByEmployeeID,
			&i.RelatedEntityType,
			&i.RelatedEntityID,
			&i.ExpiresAt,
			&i.SentAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSignDocumentCompleted = `-- name: MarkSignDocumentCompleted :one
UPDATE sign_documents
SET status = 'completed', signed_file_key = $2, completed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status IN ('sent', 'partially_signed')
RETURNING id, title, source_attachment_id, source_file_key, signed_file_key, status, created_by_employee_id, related_entity_type, related_entity_id, expires_at, sent_at, completed_at, cancelled_at, created_at, updated_at
`

type MarkSignDocumentCompletedParams struct {
	ID            uuid.UUID `json:"id"`
	SignedFileKey *string   `json:"signed_file_key"`
}

func (q *Queries) MarkSignDocumentCompleted(ctx context.Context, arg MarkSignDocumentCompletedParams) (SignDocument, error) {
	row := q.db.QueryRow(ctx, markSignDocumentCompleted, arg.ID, arg.SignedFileKey)
	var i SignDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SourceAttachmentID,
		&i.SourceFileKey,
		&i.SignedFileKey,
		&i.Status,
		&i.CreatedByEmployeeID,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.ExpiresAt,
		&i.SentAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSignDocumentPartiallySigned = `-- name: MarkSignDocumentPartiallySigned :one
UPDATE sign_documents
SET status = 'partially_signed', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status IN ('sent', 'partially_signed')
RETURNING id, title, source_attachment_id, source_file_key, signed_file_key, status, created_by_employee_id, related_entity_type, related_entity_id, expires_at, sent_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) MarkSignDocumentPartiallySigned(ctx context.Context, id uuid.UUID) (SignDocument, error) {
	row := q.db.QueryRow(ctx, markSignDocumentPartiallySigned, id)
	var i SignDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SourceAttachmentID,
		&i.SourceFileKey,
		&i.SignedFileKey,
		&i.Status,
		&i.CreatedByEmployeeID,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.ExpiresAt,
		&i.SentAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSignDocumentRecipientSigned = `-- name: MarkSignDocumentRecipientSigned :one
UPDATE sign_document_recipients
SET status = 'signed', signed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status IN ('pending', 'viewed')
RETURNING id, document_id, employee_id, name, email, signing_order, status, viewed_at, signed_at, declined_at, decline_reason, created_at, updated_at
`

func (q *Queries) MarkSignDocumentRecipientSigned(ctx context.Context, id uuid.UUID) (SignDocumentRecipient, error) {
	row := q.db.QueryRow(ctx, markSignDocumentRecipientSigned, id)
	var i SignDocumentRecipient
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.SigningOrder,
		&i.Status,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSignDocumentRecipientViewed = `-- name: MarkSignDocumentRecipientViewed :one
UPDATE sign_document_recipients
SET status = CASE WHEN status = 'pending' THEN 'viewed' ELSE status END,
    viewed_at = COALESCE(viewed_at, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status IN ('pending', 'viewed')
RETURNING id, document_id, employee_id, name, email, signing_order, status, viewed_at, signed_at, declined_at, decline_reason, created_at, updated_at
`

func (q *Queries) MarkSignDocumentRecipientViewed(ctx context.Context, id uuid.UUID) (SignDocumentRecipient, error) {
	row := q.db.QueryRow(ctx, markSignDocumentRecipientViewed, id)
	var i SignDocumentRecipient
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.EmployeeID,
		&i.Name,
		&i.Email,
		&i.SigningOrder,
		&i.Status,
		&i.ViewedAt,
		&i.SignedAt,
		&i.DeclinedAt,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sendSignDocument = `-- name: SendSignDocument :one
UPDATE sign_documents
SET status = 'sent', sent_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'draft'
RETURNING id, title, source_attachment_id, source_file_key, signed_file_key, status, created_by_employee_id, related_entity_type, related_entity_id, expires_at, sent_at, completed_at, cancelled_at, created_at, updated_at
`

func (q *Queries) SendSignDocument(ctx context.Context, id uuid.UUID) (SignDocument, error) {
	row := q.db.QueryRow(ctx, sendSignDocument, id)
	var i SignDocument
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SourceAttachmentID,
		&i.SourceFileKey,
		&i.SignedFileKey,
		&i.Status,
		&i.CreatedByEmployeeID,
		&i.RelatedEntityType,
		&i.RelatedEntityID,
		&i.ExpiresAt,
		&i.SentAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSignDocumentFieldValue = `-- name: UpdateSignDocumentFieldValue :one
UPDATE sign_document_fields
SET value = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND recipient_id = $2
RETURNING id, document_id, recipient_id, type, page_number, x, y, width, height, required, label, value, created_at, updated_at
`

type UpdateSignDocumentFieldValueParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
	Value       *string   `json:"value"`
}

func (q *Queries) UpdateSignDocumentFieldValue(ctx context.Context, arg UpdateSignDocumentFieldValueParams) (SignDocumentField, error) {
	row := q.db.QueryRow(ctx, updateSignDocumentFieldValue, arg.ID, arg.RecipientID, arg.Value)
	var i SignDocumentField
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RecipientID,
		&i.Type,
		&i.PageNumber,
		&i.X,
		&i.Y,
		&i.Width,
		&i.Height,
		&i.Required,
		&i.Label,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
