// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: time_entry.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeEntry = `-- name: CreateTimeEntry :one
WITH inserted_time_entry AS (
    INSERT INTO time_entries (
        employee_id,
        schedule_id,
        entry_date,
        hours,
        hour_type,
        project_name,
        project_number,
        client_name,
        activity_category,
        activity_description,
        notes
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11
    )
    RETURNING
        id,
        employee_id,
        schedule_id,
        entry_date,
        hours,
        hour_type,
        project_name,
        project_number,
        client_name,
        activity_category,
        activity_description,
        status,
        submitted_at,
        approved_at,
        approved_by_employee_id,
        rejection_reason,
        notes,
        created_at,
        updated_at
)
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.hours,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name
FROM inserted_time_entry te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
`

type CreateTimeEntryParams struct {
	EmployeeID          uuid.UUID             `json:"employee_id"`
	ScheduleID          *uuid.UUID            `json:"schedule_id"`
	EntryDate           pgtype.Date           `json:"entry_date"`
	Hours               float64               `json:"hours"`
	HourType            TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName         *string               `json:"project_name"`
	ProjectNumber       *string               `json:"project_number"`
	ClientName          *string               `json:"client_name"`
	ActivityCategory    *string               `json:"activity_category"`
	ActivityDescription *string               `json:"activity_description"`
	Notes               *string               `json:"notes"`
}

type CreateTimeEntryRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	Hours                float64               `json:"hours"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (CreateTimeEntryRow, error) {
	row := q.db.QueryRow(ctx, createTimeEntry,
		arg.EmployeeID,
		arg.ScheduleID,
		arg.EntryDate,
		arg.Hours,
		arg.HourType,
		arg.ProjectName,
		arg.ProjectNumber,
		arg.ClientName,
		arg.ActivityCategory,
		arg.ActivityDescription,
		arg.Notes,
	)
	var i CreateTimeEntryRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ScheduleID,
		&i.EntryDate,
		&i.Hours,
		&i.HourType,
		&i.ProjectName,
		&i.ProjectNumber,
		&i.ClientName,
		&i.ActivityCategory,
		&i.ActivityDescription,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByEmployeeID,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeFirstName,
		&i.EmployeeLastName,
		&i.ApprovedByFirstName,
		&i.ApprovedByLastName,
	)
	return i, err
}

const getTimeEntryByID = `-- name: GetTimeEntryByID :one
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.hours,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name
FROM time_entries te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
WHERE te.id = $1
LIMIT 1
`

type GetTimeEntryByIDRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	Hours                float64               `json:"hours"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
}

func (q *Queries) GetTimeEntryByID(ctx context.Context, id uuid.UUID) (GetTimeEntryByIDRow, error) {
	row := q.db.QueryRow(ctx, getTimeEntryByID, id)
	var i GetTimeEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ScheduleID,
		&i.EntryDate,
		&i.Hours,
		&i.HourType,
		&i.ProjectName,
		&i.ProjectNumber,
		&i.ClientName,
		&i.ActivityCategory,
		&i.ActivityDescription,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByEmployeeID,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeFirstName,
		&i.EmployeeLastName,
		&i.ApprovedByFirstName,
		&i.ApprovedByLastName,
	)
	return i, err
}

const listMyTimeEntriesPaginated = `-- name: ListMyTimeEntriesPaginated :many
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.hours,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name,
    COUNT(*) OVER() AS total_count
FROM time_entries te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
WHERE te.employee_id = $1
  AND (
    $2::time_entry_status_enum IS NULL
    OR te.status = $2::time_entry_status_enum
  )
ORDER BY te.entry_date DESC, te.created_at DESC
LIMIT $4 OFFSET $3
`

type ListMyTimeEntriesPaginatedParams struct {
	EmployeeID uuid.UUID               `json:"employee_id"`
	Status     NullTimeEntryStatusEnum `json:"status"`
	Offset     int32                   `json:"offset"`
	Limit      int32                   `json:"limit"`
}

type ListMyTimeEntriesPaginatedRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	Hours                float64               `json:"hours"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
	TotalCount           int64                 `json:"total_count"`
}

func (q *Queries) ListMyTimeEntriesPaginated(ctx context.Context, arg ListMyTimeEntriesPaginatedParams) ([]ListMyTimeEntriesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listMyTimeEntriesPaginated,
		arg.EmployeeID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyTimeEntriesPaginatedRow{}
	for rows.Next() {
		var i ListMyTimeEntriesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ScheduleID,
			&i.EntryDate,
			&i.Hours,
			&i.HourType,
			&i.ProjectName,
			&i.ProjectNumber,
			&i.ClientName,
			&i.ActivityCategory,
			&i.ActivityDescription,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByEmployeeID,
			&i.RejectionReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.ApprovedByFirstName,
			&i.ApprovedByLastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeEntriesPaginated = `-- name: ListTimeEntriesPaginated :many
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.hours,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name,
    COUNT(*) OVER() AS total_count
FROM time_entries te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
WHERE (
    $1::uuid IS NULL
    OR te.employee_id = $1::uuid
)
  AND (
    $2::time_entry_status_enum IS NULL
    OR te.status = $2::time_entry_status_enum
  )
  AND (
    $3::text IS NULL
    OR $3::text = ''
    OR ep.first_name ILIKE '%' || $3::text || '%'
    OR ep.last_name ILIKE '%' || $3::text || '%'
    OR (ep.first_name || ' ' || ep.last_name) ILIKE '%' || $3::text || '%'
    OR (ep.last_name || ' ' || ep.first_name) ILIKE '%' || $3::text || '%'
  )
ORDER BY te.entry_date DESC, te.created_at DESC
LIMIT $5 OFFSET $4
`

type ListTimeEntriesPaginatedParams struct {
	EmployeeID     *uuid.UUID              `json:"employee_id"`
	Status         NullTimeEntryStatusEnum `json:"status"`
	EmployeeSearch *string                 `json:"employee_search"`
	Offset         int32                   `json:"offset"`
	Limit          int32                   `json:"limit"`
}

type ListTimeEntriesPaginatedRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	Hours                float64               `json:"hours"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
	TotalCount           int64                 `json:"total_count"`
}

func (q *Queries) ListTimeEntriesPaginated(ctx context.Context, arg ListTimeEntriesPaginatedParams) ([]ListTimeEntriesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listTimeEntriesPaginated,
		arg.EmployeeID,
		arg.Status,
		arg.EmployeeSearch,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimeEntriesPaginatedRow{}
	for rows.Next() {
		var i ListTimeEntriesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ScheduleID,
			&i.EntryDate,
			&i.Hours,
			&i.HourType,
			&i.ProjectName,
			&i.ProjectNumber,
			&i.ClientName,
			&i.ActivityCategory,
			&i.ActivityDescription,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByEmployeeID,
			&i.RejectionReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.ApprovedByFirstName,
			&i.ApprovedByLastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
