// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_entry.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveTimeEntry = `-- name: ApproveTimeEntry :one
WITH updated_time_entry AS (
    UPDATE time_entries
    SET
        status = 'approved'::time_entry_status_enum,
        approved_at = NOW(),
        approved_by_employee_id = $1,
        rejection_reason = NULL,
        updated_at = NOW()
    WHERE time_entries.id = $2
    RETURNING
        id,
        employee_id,
        schedule_id,
        entry_date,
        start_time,
        end_time,
        break_minutes,
        hour_type,
        project_name,
        project_number,
        client_name,
        activity_category,
        activity_description,
        status,
        submitted_at,
        approved_at,
        approved_by_employee_id,
        rejection_reason,
        notes,
        created_at,
        updated_at,
        paid_period_id
)
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.start_time,
    te.end_time,
    te.break_minutes,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    te.paid_period_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name
FROM updated_time_entry te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
`

type ApproveTimeEntryParams struct {
	ApprovedByEmployeeID *uuid.UUID `json:"approved_by_employee_id"`
	ID                   uuid.UUID  `json:"id"`
}

type ApproveTimeEntryRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	StartTime            pgtype.Time           `json:"start_time"`
	EndTime              pgtype.Time           `json:"end_time"`
	BreakMinutes         int32                 `json:"break_minutes"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	PaidPeriodID         *uuid.UUID            `json:"paid_period_id"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
}

func (q *Queries) ApproveTimeEntry(ctx context.Context, arg ApproveTimeEntryParams) (ApproveTimeEntryRow, error) {
	row := q.db.QueryRow(ctx, approveTimeEntry, arg.ApprovedByEmployeeID, arg.ID)
	var i ApproveTimeEntryRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ScheduleID,
		&i.EntryDate,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.HourType,
		&i.ProjectName,
		&i.ProjectNumber,
		&i.ClientName,
		&i.ActivityCategory,
		&i.ActivityDescription,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByEmployeeID,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidPeriodID,
		&i.EmployeeFirstName,
		&i.EmployeeLastName,
		&i.ApprovedByFirstName,
		&i.ApprovedByLastName,
	)
	return i, err
}

const createTimeEntry = `-- name: CreateTimeEntry :one
WITH inserted_time_entry AS (
    INSERT INTO time_entries (
        employee_id,
        schedule_id,
        entry_date,
        start_time,
        end_time,
        break_minutes,
        hour_type,
        project_name,
        project_number,
        client_name,
        activity_category,
        activity_description,
        notes
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13
    )
    RETURNING
        id,
        employee_id,
        schedule_id,
        entry_date,
        start_time,
        end_time,
        break_minutes,
        hour_type,
        project_name,
        project_number,
        client_name,
        activity_category,
        activity_description,
        status,
        submitted_at,
        approved_at,
        approved_by_employee_id,
        rejection_reason,
        notes,
        created_at,
        updated_at,
        paid_period_id
)
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.start_time,
    te.end_time,
    te.break_minutes,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    te.paid_period_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name
FROM inserted_time_entry te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
`

type CreateTimeEntryParams struct {
	EmployeeID          uuid.UUID             `json:"employee_id"`
	ScheduleID          *uuid.UUID            `json:"schedule_id"`
	EntryDate           pgtype.Date           `json:"entry_date"`
	StartTime           pgtype.Time           `json:"start_time"`
	EndTime             pgtype.Time           `json:"end_time"`
	BreakMinutes        int32                 `json:"break_minutes"`
	HourType            TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName         *string               `json:"project_name"`
	ProjectNumber       *string               `json:"project_number"`
	ClientName          *string               `json:"client_name"`
	ActivityCategory    *string               `json:"activity_category"`
	ActivityDescription *string               `json:"activity_description"`
	Notes               *string               `json:"notes"`
}

type CreateTimeEntryRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	StartTime            pgtype.Time           `json:"start_time"`
	EndTime              pgtype.Time           `json:"end_time"`
	BreakMinutes         int32                 `json:"break_minutes"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	PaidPeriodID         *uuid.UUID            `json:"paid_period_id"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (CreateTimeEntryRow, error) {
	row := q.db.QueryRow(ctx, createTimeEntry,
		arg.EmployeeID,
		arg.ScheduleID,
		arg.EntryDate,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.HourType,
		arg.ProjectName,
		arg.ProjectNumber,
		arg.ClientName,
		arg.ActivityCategory,
		arg.ActivityDescription,
		arg.Notes,
	)
	var i CreateTimeEntryRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ScheduleID,
		&i.EntryDate,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.HourType,
		&i.ProjectName,
		&i.ProjectNumber,
		&i.ClientName,
		&i.ActivityCategory,
		&i.ActivityDescription,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByEmployeeID,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidPeriodID,
		&i.EmployeeFirstName,
		&i.EmployeeLastName,
		&i.ApprovedByFirstName,
		&i.ApprovedByLastName,
	)
	return i, err
}

const createTimeEntryUpdateAudit = `-- name: CreateTimeEntryUpdateAudit :exec
INSERT INTO time_entry_update_audits (
    time_entry_id,
    admin_employee_id,
    admin_update_note,
    before_snapshot,
    after_snapshot
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateTimeEntryUpdateAuditParams struct {
	TimeEntryID     uuid.UUID `json:"time_entry_id"`
	AdminEmployeeID uuid.UUID `json:"admin_employee_id"`
	AdminUpdateNote string    `json:"admin_update_note"`
	BeforeSnapshot  []byte    `json:"before_snapshot"`
	AfterSnapshot   []byte    `json:"after_snapshot"`
}

func (q *Queries) CreateTimeEntryUpdateAudit(ctx context.Context, arg CreateTimeEntryUpdateAuditParams) error {
	_, err := q.db.Exec(ctx, createTimeEntryUpdateAudit,
		arg.TimeEntryID,
		arg.AdminEmployeeID,
		arg.AdminUpdateNote,
		arg.BeforeSnapshot,
		arg.AfterSnapshot,
	)
	return err
}

const getCurrentMonthTimeEntryStats = `-- name: GetCurrentMonthTimeEntryStats :one
SELECT
    COALESCE(
        SUM(
            GREATEST(
                0,
                (
                    CASE
                        WHEN te.end_time > te.start_time THEN
                            EXTRACT(EPOCH FROM te.end_time) - EXTRACT(EPOCH FROM te.start_time)
                        ELSE
                            EXTRACT(EPOCH FROM te.end_time) + 86400 - EXTRACT(EPOCH FROM te.start_time)
                    END
                ) / 60 - te.break_minutes
            )
        ),
        0
    )::BIGINT AS total_worked_minutes,
    COUNT(*) FILTER (
        WHERE te.status = 'submitted'::time_entry_status_enum
    )::BIGINT AS total_awaiting_approval,
    COUNT(*) FILTER (
        WHERE te.status = 'approved'::time_entry_status_enum
    )::BIGINT AS total_approved,
    COUNT(*) FILTER (
        WHERE te.status = 'draft'::time_entry_status_enum
    )::BIGINT AS total_concepts
FROM time_entries te
WHERE te.entry_date >= DATE_TRUNC('month', NOW())::date
  AND te.entry_date < (DATE_TRUNC('month', NOW()) + INTERVAL '1 month')::date
`

type GetCurrentMonthTimeEntryStatsRow struct {
	TotalWorkedMinutes    int64 `json:"total_worked_minutes"`
	TotalAwaitingApproval int64 `json:"total_awaiting_approval"`
	TotalApproved         int64 `json:"total_approved"`
	TotalConcepts         int64 `json:"total_concepts"`
}

func (q *Queries) GetCurrentMonthTimeEntryStats(ctx context.Context) (GetCurrentMonthTimeEntryStatsRow, error) {
	row := q.db.QueryRow(ctx, getCurrentMonthTimeEntryStats)
	var i GetCurrentMonthTimeEntryStatsRow
	err := row.Scan(
		&i.TotalWorkedMinutes,
		&i.TotalAwaitingApproval,
		&i.TotalApproved,
		&i.TotalConcepts,
	)
	return i, err
}

const getTimeEntryByID = `-- name: GetTimeEntryByID :one
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.start_time,
    te.end_time,
    te.break_minutes,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    te.paid_period_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name
FROM time_entries te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
WHERE te.id = $1
LIMIT 1
`

type GetTimeEntryByIDRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	StartTime            pgtype.Time           `json:"start_time"`
	EndTime              pgtype.Time           `json:"end_time"`
	BreakMinutes         int32                 `json:"break_minutes"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	PaidPeriodID         *uuid.UUID            `json:"paid_period_id"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
}

func (q *Queries) GetTimeEntryByID(ctx context.Context, id uuid.UUID) (GetTimeEntryByIDRow, error) {
	row := q.db.QueryRow(ctx, getTimeEntryByID, id)
	var i GetTimeEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ScheduleID,
		&i.EntryDate,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.HourType,
		&i.ProjectName,
		&i.ProjectNumber,
		&i.ClientName,
		&i.ActivityCategory,
		&i.ActivityDescription,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByEmployeeID,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidPeriodID,
		&i.EmployeeFirstName,
		&i.EmployeeLastName,
		&i.ApprovedByFirstName,
		&i.ApprovedByLastName,
	)
	return i, err
}

const listMyTimeEntriesPaginated = `-- name: ListMyTimeEntriesPaginated :many
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.start_time,
    te.end_time,
    te.break_minutes,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    te.paid_period_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name,
    COUNT(*) OVER() AS total_count
FROM time_entries te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
WHERE te.employee_id = $1
  AND (
    $2::time_entry_status_enum IS NULL
    OR te.status = $2::time_entry_status_enum
  )
ORDER BY te.entry_date DESC, te.created_at DESC
LIMIT $4 OFFSET $3
`

type ListMyTimeEntriesPaginatedParams struct {
	EmployeeID uuid.UUID            `json:"employee_id"`
	Status     *TimeEntryStatusEnum `json:"status"`
	Offset     int32                `json:"offset"`
	Limit      int32                `json:"limit"`
}

type ListMyTimeEntriesPaginatedRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	StartTime            pgtype.Time           `json:"start_time"`
	EndTime              pgtype.Time           `json:"end_time"`
	BreakMinutes         int32                 `json:"break_minutes"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	PaidPeriodID         *uuid.UUID            `json:"paid_period_id"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
	TotalCount           int64                 `json:"total_count"`
}

func (q *Queries) ListMyTimeEntriesPaginated(ctx context.Context, arg ListMyTimeEntriesPaginatedParams) ([]ListMyTimeEntriesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listMyTimeEntriesPaginated,
		arg.EmployeeID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyTimeEntriesPaginatedRow{}
	for rows.Next() {
		var i ListMyTimeEntriesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ScheduleID,
			&i.EntryDate,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMinutes,
			&i.HourType,
			&i.ProjectName,
			&i.ProjectNumber,
			&i.ClientName,
			&i.ActivityCategory,
			&i.ActivityDescription,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByEmployeeID,
			&i.RejectionReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidPeriodID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.ApprovedByFirstName,
			&i.ApprovedByLastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeEntriesPaginated = `-- name: ListTimeEntriesPaginated :many
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.start_time,
    te.end_time,
    te.break_minutes,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    te.paid_period_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name,
    COUNT(*) OVER() AS total_count
FROM time_entries te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
WHERE (
    $1::uuid IS NULL
    OR te.employee_id = $1::uuid
)
  AND (
    $2::time_entry_status_enum IS NULL
    OR te.status = $2::time_entry_status_enum
  )
  AND (
    $3::text IS NULL
    OR $3::text = ''
    OR ep.first_name ILIKE '%' || $3::text || '%'
    OR ep.last_name ILIKE '%' || $3::text || '%'
    OR (ep.first_name || ' ' || ep.last_name) ILIKE '%' || $3::text || '%'
    OR (ep.last_name || ' ' || ep.first_name) ILIKE '%' || $3::text || '%'
  )
ORDER BY te.entry_date DESC, te.created_at DESC
LIMIT $5 OFFSET $4
`

type ListTimeEntriesPaginatedParams struct {
	EmployeeID     *uuid.UUID           `json:"employee_id"`
	Status         *TimeEntryStatusEnum `json:"status"`
	EmployeeSearch *string              `json:"employee_search"`
	Offset         int32                `json:"offset"`
	Limit          int32                `json:"limit"`
}

type ListTimeEntriesPaginatedRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	StartTime            pgtype.Time           `json:"start_time"`
	EndTime              pgtype.Time           `json:"end_time"`
	BreakMinutes         int32                 `json:"break_minutes"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	PaidPeriodID         *uuid.UUID            `json:"paid_period_id"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
	TotalCount           int64                 `json:"total_count"`
}

func (q *Queries) ListTimeEntriesPaginated(ctx context.Context, arg ListTimeEntriesPaginatedParams) ([]ListTimeEntriesPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listTimeEntriesPaginated,
		arg.EmployeeID,
		arg.Status,
		arg.EmployeeSearch,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTimeEntriesPaginatedRow{}
	for rows.Next() {
		var i ListTimeEntriesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ScheduleID,
			&i.EntryDate,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMinutes,
			&i.HourType,
			&i.ProjectName,
			&i.ProjectNumber,
			&i.ClientName,
			&i.ActivityCategory,
			&i.ActivityDescription,
			&i.Status,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.ApprovedByEmployeeID,
			&i.RejectionReason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidPeriodID,
			&i.EmployeeFirstName,
			&i.EmployeeLastName,
			&i.ApprovedByFirstName,
			&i.ApprovedByLastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTimeEntryByID = `-- name: LockTimeEntryByID :one
SELECT id, employee_id, schedule_id, entry_date, start_time, end_time, break_minutes, hour_type, project_name, project_number, client_name, activity_category, activity_description, status, submitted_at, approved_at, approved_by_employee_id, rejection_reason, notes, created_at, updated_at, paid_period_id
FROM time_entries
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockTimeEntryByID(ctx context.Context, id uuid.UUID) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, lockTimeEntryByID, id)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ScheduleID,
		&i.EntryDate,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.HourType,
		&i.ProjectName,
		&i.ProjectNumber,
		&i.ClientName,
		&i.ActivityCategory,
		&i.ActivityDescription,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByEmployeeID,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidPeriodID,
	)
	return i, err
}

const rejectTimeEntry = `-- name: RejectTimeEntry :one
WITH updated_time_entry AS (
    UPDATE time_entries
    SET
        status = 'rejected'::time_entry_status_enum,
        rejection_reason = $1::text,
        approved_at = NULL,
        approved_by_employee_id = NULL,
        updated_at = NOW()
    WHERE time_entries.id = $2
    RETURNING
        id,
        employee_id,
        schedule_id,
        entry_date,
        start_time,
        end_time,
        break_minutes,
        hour_type,
        project_name,
        project_number,
        client_name,
        activity_category,
        activity_description,
        status,
        submitted_at,
        approved_at,
        approved_by_employee_id,
        rejection_reason,
        notes,
        created_at,
        updated_at,
        paid_period_id
)
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.start_time,
    te.end_time,
    te.break_minutes,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    te.paid_period_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name
FROM updated_time_entry te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
`

type RejectTimeEntryParams struct {
	RejectionReason *string   `json:"rejection_reason"`
	ID              uuid.UUID `json:"id"`
}

type RejectTimeEntryRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	StartTime            pgtype.Time           `json:"start_time"`
	EndTime              pgtype.Time           `json:"end_time"`
	BreakMinutes         int32                 `json:"break_minutes"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	PaidPeriodID         *uuid.UUID            `json:"paid_period_id"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
}

func (q *Queries) RejectTimeEntry(ctx context.Context, arg RejectTimeEntryParams) (RejectTimeEntryRow, error) {
	row := q.db.QueryRow(ctx, rejectTimeEntry, arg.RejectionReason, arg.ID)
	var i RejectTimeEntryRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ScheduleID,
		&i.EntryDate,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.HourType,
		&i.ProjectName,
		&i.ProjectNumber,
		&i.ClientName,
		&i.ActivityCategory,
		&i.ActivityDescription,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByEmployeeID,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidPeriodID,
		&i.EmployeeFirstName,
		&i.EmployeeLastName,
		&i.ApprovedByFirstName,
		&i.ApprovedByLastName,
	)
	return i, err
}

const updateTimeEntryByAdmin = `-- name: UpdateTimeEntryByAdmin :one
WITH updated_time_entry AS (
    UPDATE time_entries
    SET
        schedule_id = COALESCE($1::uuid, schedule_id),
        entry_date = COALESCE($2::date, entry_date),
        start_time = COALESCE($3::time, start_time),
        end_time = COALESCE($4::time, end_time),
        break_minutes = COALESCE($5::integer, break_minutes),
        hour_type = COALESCE($6::time_entry_hour_type_enum, hour_type),
        project_name = COALESCE($7::text, project_name),
        project_number = COALESCE($8::text, project_number),
        client_name = COALESCE($9::text, client_name),
        activity_category = COALESCE($10::text, activity_category),
        activity_description = COALESCE(
            $11::text,
            activity_description
        ),
        notes = COALESCE($12::text, notes),
        status = CASE
            WHEN $13::boolean
                THEN 'submitted'::time_entry_status_enum
            ELSE status
        END,
        submitted_at = CASE
            WHEN $13::boolean THEN NOW()
            ELSE submitted_at
        END,
        approved_at = CASE
            WHEN $13::boolean THEN NULL
            ELSE approved_at
        END,
        approved_by_employee_id = CASE
            WHEN $13::boolean THEN NULL
            ELSE approved_by_employee_id
        END,
        rejection_reason = CASE
            WHEN $13::boolean THEN NULL
            ELSE rejection_reason
        END,
        updated_at = NOW()
    WHERE time_entries.id = $14
    RETURNING
        id,
        employee_id,
        schedule_id,
        entry_date,
        start_time,
        end_time,
        break_minutes,
        hour_type,
        project_name,
        project_number,
        client_name,
        activity_category,
        activity_description,
        status,
        submitted_at,
        approved_at,
        approved_by_employee_id,
        rejection_reason,
        notes,
        created_at,
        updated_at,
        paid_period_id
)
SELECT
    te.id,
    te.employee_id,
    te.schedule_id,
    te.entry_date,
    te.start_time,
    te.end_time,
    te.break_minutes,
    te.hour_type,
    te.project_name,
    te.project_number,
    te.client_name,
    te.activity_category,
    te.activity_description,
    te.status,
    te.submitted_at,
    te.approved_at,
    te.approved_by_employee_id,
    te.rejection_reason,
    te.notes,
    te.created_at,
    te.updated_at,
    te.paid_period_id,
    ep.first_name AS employee_first_name,
    ep.last_name AS employee_last_name,
    ap.first_name AS approved_by_first_name,
    ap.last_name AS approved_by_last_name
FROM updated_time_entry te
JOIN employee_profile ep ON ep.id = te.employee_id
LEFT JOIN employee_profile ap ON ap.id = te.approved_by_employee_id
`

type UpdateTimeEntryByAdminParams struct {
	ScheduleID          *uuid.UUID             `json:"schedule_id"`
	EntryDate           pgtype.Date            `json:"entry_date"`
	StartTime           pgtype.Time            `json:"start_time"`
	EndTime             pgtype.Time            `json:"end_time"`
	BreakMinutes        *int32                 `json:"break_minutes"`
	HourType            *TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName         *string                `json:"project_name"`
	ProjectNumber       *string                `json:"project_number"`
	ClientName          *string                `json:"client_name"`
	ActivityCategory    *string                `json:"activity_category"`
	ActivityDescription *string                `json:"activity_description"`
	Notes               *string                `json:"notes"`
	SetSubmitted        bool                   `json:"set_submitted"`
	ID                  uuid.UUID              `json:"id"`
}

type UpdateTimeEntryByAdminRow struct {
	ID                   uuid.UUID             `json:"id"`
	EmployeeID           uuid.UUID             `json:"employee_id"`
	ScheduleID           *uuid.UUID            `json:"schedule_id"`
	EntryDate            pgtype.Date           `json:"entry_date"`
	StartTime            pgtype.Time           `json:"start_time"`
	EndTime              pgtype.Time           `json:"end_time"`
	BreakMinutes         int32                 `json:"break_minutes"`
	HourType             TimeEntryHourTypeEnum `json:"hour_type"`
	ProjectName          *string               `json:"project_name"`
	ProjectNumber        *string               `json:"project_number"`
	ClientName           *string               `json:"client_name"`
	ActivityCategory     *string               `json:"activity_category"`
	ActivityDescription  *string               `json:"activity_description"`
	Status               TimeEntryStatusEnum   `json:"status"`
	SubmittedAt          pgtype.Timestamptz    `json:"submitted_at"`
	ApprovedAt           pgtype.Timestamptz    `json:"approved_at"`
	ApprovedByEmployeeID *uuid.UUID            `json:"approved_by_employee_id"`
	RejectionReason      *string               `json:"rejection_reason"`
	Notes                *string               `json:"notes"`
	CreatedAt            pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz    `json:"updated_at"`
	PaidPeriodID         *uuid.UUID            `json:"paid_period_id"`
	EmployeeFirstName    string                `json:"employee_first_name"`
	EmployeeLastName     string                `json:"employee_last_name"`
	ApprovedByFirstName  *string               `json:"approved_by_first_name"`
	ApprovedByLastName   *string               `json:"approved_by_last_name"`
}

func (q *Queries) UpdateTimeEntryByAdmin(ctx context.Context, arg UpdateTimeEntryByAdminParams) (UpdateTimeEntryByAdminRow, error) {
	row := q.db.QueryRow(ctx, updateTimeEntryByAdmin,
		arg.ScheduleID,
		arg.EntryDate,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.HourType,
		arg.ProjectName,
		arg.ProjectNumber,
		arg.ClientName,
		arg.ActivityCategory,
		arg.ActivityDescription,
		arg.Notes,
		arg.SetSubmitted,
		arg.ID,
	)
	var i UpdateTimeEntryByAdminRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ScheduleID,
		&i.EntryDate,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.HourType,
		&i.ProjectName,
		&i.ProjectNumber,
		&i.ClientName,
		&i.ActivityCategory,
		&i.ActivityDescription,
		&i.Status,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.ApprovedByEmployeeID,
		&i.RejectionReason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidPeriodID,
		&i.EmployeeFirstName,
		&i.EmployeeLastName,
		&i.ApprovedByFirstName,
		&i.ApprovedByLastName,
	)
	return i, err
}
