// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training_catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTrainingCatalogItem = `-- name: CreateTrainingCatalogItem :one
INSERT INTO training_catalog_items (
    title,
    description,
    category,
    estimated_duration_minutes,
    created_by_employee_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, title, description, category, estimated_duration_minutes, is_active, created_by_employee_id, created_at, updated_at
`

type CreateTrainingCatalogItemParams struct {
	Title                    string     `json:"title"`
	Description              *string    `json:"description"`
	Category                 *string    `json:"category"`
	EstimatedDurationMinutes *int32     `json:"estimated_duration_minutes"`
	CreatedByEmployeeID      *uuid.UUID `json:"created_by_employee_id"`
}

func (q *Queries) CreateTrainingCatalogItem(ctx context.Context, arg CreateTrainingCatalogItemParams) (TrainingCatalogItem, error) {
	row := q.db.QueryRow(ctx, createTrainingCatalogItem,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.EstimatedDurationMinutes,
		arg.CreatedByEmployeeID,
	)
	var i TrainingCatalogItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.EstimatedDurationMinutes,
		&i.IsActive,
		&i.CreatedByEmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
