DELETE FROM role_permissions
WHERE permission_id IN (
    SELECT id FROM permissions
    WHERE name IN (
        'PERFORMANCE.ASSESSMENT.CREATE',
        'PERFORMANCE.ASSESSMENT.VIEW',
        'PERFORMANCE.ASSESSMENT.VIEW_ALL',
        'PERFORMANCE.ASSESSMENT.DELETE',
        'PERFORMANCE.WORK_ASSIGNMENT.VIEW',
        'PERFORMANCE.WORK_ASSIGNMENT.VIEW_ALL',
        'PERFORMANCE.WORK_ASSIGNMENT.DECIDE',
        'PERFORMANCE.UPCOMING.INVITE',
        'PERFORMANCE.STATS.VIEW'
    )
);

DELETE FROM permissions
WHERE name IN (
    'PERFORMANCE.ASSESSMENT.CREATE',
    'PERFORMANCE.ASSESSMENT.VIEW',
    'PERFORMANCE.ASSESSMENT.VIEW_ALL',
    'PERFORMANCE.ASSESSMENT.DELETE',
    'PERFORMANCE.WORK_ASSIGNMENT.VIEW',
    'PERFORMANCE.WORK_ASSIGNMENT.VIEW_ALL',
    'PERFORMANCE.WORK_ASSIGNMENT.DECIDE',
    'PERFORMANCE.UPCOMING.INVITE',
    'PERFORMANCE.STATS.VIEW'
);

DROP TABLE IF EXISTS performance_work_assignments;
DROP TABLE IF EXISTS performance_assessment_scores;
DROP TABLE IF EXISTS performance_assessments;

DROP TYPE IF EXISTS performance_work_assignment_status_enum;
DROP TYPE IF EXISTS performance_assessment_status_enum;
